### ISSUE TITLE
horizontal bar which shows recept bandwidth does not change correct

### ISSUE THREAD

**Issue by df8oe** [df8oe/mchf-github#1]
Hi Clint,
if I change from 20m (where USB is selected) to 40m (where LSB is selected), the bar remains on the right side showing USB receiption (but LSB is heard correctly). I I change once to USB and then back to LSB, the bar changes correctly. It seems so that setting of the bar is only made when changing modes but must be done when changing bands, too.

vy 73
Andreas

**Comment by imoldovavan** [comment]
I think this is something I can fix. Would this be considered a "hotfix" branch? What is the proper way of starting this?

**Comment by df8oe** [comment]
Yes - start a "hotfix-branch". In this state everything which demonstrates our team-power is highly welcome.

vy 73
Andreas

**Comment by imoldovavan** [comment]
Understood. hotfix_bandwith_bar branch started. Once we get something working we will ask Clint to take a look at it. 

73's
Ion

**Comment by df8oe** [comment]
I have fixed this today in my devel branch.
