### ISSUE TITLE
FW 2.5.52 - PTT/USB does not work any more

### ISSUE THREAD

**Issue by s53dz** [df8oe/mchf-github#1000]
At using program WSJT-X the PTT does not release the TX after the TX sequence is finished.
By first press to the mcHF TUNE it goes to transmit and the second press on TUNE it releases the TX and returns to RX.

73 Bojan

**Comment by db4ple** [comment]
Congratulation, issue number 1000 !
Hope the committed fixes solve the problem.

**Comment by s53dz** [comment]
FW 2.5.54: this issue is solved.
PTT over USB works again. WSJT-X/linux.

TNX 73 Bojan
