### ISSUE TITLE
Outer RTTY marker line

### ISSUE THREAD

**Issue by s53dz** [df8oe/mchf-github#1018]
When using D2.5.63 (and ... 2.5.60) in digimodes and going out of digimode, the right RTTY marker stays on display until the next time when switched to digimodes.

73 Bojan

**Comment by DG9BFC** [comment]
also in newer version 2.5.68 is the same fault but it is not only the right marker
if you use rtty L it is the left marker so we should say outer marker stays on inner marker is off (like it should be for both markers)

**Comment by s53dz** [comment]
With D2.5.72 this issue is gone.
