### ISSUE TITLE
RX and TX marker lines

### ISSUE THREAD

**Issue by s53dz** [df8oe/mchf-github#1020]
Now, when the second marker line is so well introduced to the RTTY mode, why not extend the same principle also to other modes by adding an RX vertical marker line beside the TX one? I think this may help to have a clear overview when using RIT and/or SPLIT functions.

73 Bojan

**Comment by DG9BFC** [comment]
these marker lines are included now ... so ... in my view the issue can be closed or ... oh wait ... you mean you wanna have anther line  if rit is not zero???

**Comment by s53dz** [comment]
Sigi,
Until the end of this week unfortunately I can not test this markers but the only reason for having the RX marker is when it is different from the existing TX one, aye? (CW, SSB modes)

73 Bojan

**Comment by s53dz** [comment]
Sigi,
There is no RX marker line added but I can live also with a TX vertical marker line and an RX filter horizontal line as it is now.

73 Bojan
