### ISSUE TITLE
carrier marker line in mode ssb is not allways drawn correct

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#1044]
title says all but i have to explain what i mean ....
when i switch on the mchf in mode lsb the marker has full (normal) height) ... when i change mode (around the clock with pushing mode button a few times till i am back to lsb) then the marker of the carrier point only has about one box height .... all other marker lines are ok but in ssb it is not
change zoom factor brings it back but switching usb/lsb does not ... again mode change (around the clock) and it is again only drawn with one box height
fw is 2.5.80

**Comment by df8oe** [comment]
I just tried to reproduce - no success... Marker line is drawn from bottom to top with waterfall speed in every mode...

**Comment by db4ple** [comment]
Probably Sigi meant Scope Mode. Important to specify which mode the spectrum is in.
BTW, I cannot reproduce this in scope mode.

**Comment by g7jiq** [comment]
I have had a play with the software and I get the same problem,   (only in scope mode)
If you cycle thought the modes the tuning line disapears in the noise on LSB and USB then returning on the next mode.
From ver D2.5.72 to present ver this happens. (have tried them all)
From Ver D2.5.60 to D2.6.71 the left tuning line on DI-U disapears to the first box as before, and returns on next mode ( LSB.)
On ether case if the menu is selected and canceled the line retuns as expected at the screen is refreshed.
One other interesting thing is if left undisturbed the line slowly grows back...... 25 mins gave me 2 out of 4 boxes.
Hope this is of help..

**Comment by df8oe** [comment]
So it is - only in scope mode..... I haven't used scope mode since over 1 year :)

**Comment by g7jiq** [comment]
Yes its only in scope mode, 
I only use scope mode, as due to a very high noise level the waterfall is of no use, even after adustments.

**Comment by DG9BFC** [comment]
oh yes i should have mentioned that it is in scope mode ... a strong carrier draws it back (cw carrier as an example)

**Comment by g7jiq** [comment]
I have found after installing the latest update D2.5.88, if you select RTTY not FreeDV the tuning line remains throught out the mode cycling.
This is good enough for me......

**Comment by DG9BFC** [comment]
seems to be solved so can be closed (for now)
