### ISSUE TITLE
E2 second function - forced in RTTY when cycling modes

### ISSUE THREAD

**Issue by s53dz** [df8oe/mchf-github#1049]
When cycling thru modes (using G1 (S16)) and when passing the RTTY mode the M2 (S3) switch switches to its second function (RTTY SHIFT setting) and stays there.

(FW D2.5.82, but probably also before that.)

73 Bojan

**Comment by db4ple** [comment]
Yes. This is a  "work in progress" area since the old code lacks a little in that department (flexible switching encoder layouts between modes was all handcrafted code. This gets with each mode more difficult to maintain and change).

**Comment by s53dz** [comment]
Danilo,

I understand it is not easy to maintain all settings between switching modes, that is why I started this issue in an easy way: if it is possible just to remove pushing the second function when in RTTY mode it would release this issue then.

What happens is this: You switch modes across and end-up in SSB and try to change AGC / RF gain, but you are changing the RTTY shift. To get back to AGC you have to roll thru a few of E2 functions.

(D2.5.83)

EDIT:
Additional information: When changing between digital modes on a TouchScreen E2 function stays (which is ok).
(D2.5.87)

EDIT2:
When digital mode is FreeDV the E2 function does not change when cycling thru modes (which is ok). It happens only when chosen digital mode is RTTY.
(D2.5.92)

73 Bojan
