### ISSUE TITLE
After CAT band change, BAND +/- goes to wrong band

### ISSUE THREAD

**Issue by KS4L** [df8oe/mchf-github#1063]
After doing a band change through WSJTX (CAT), BAND +/- does not go to the correct band. Instead it acts as though the CAT band change had never occurred.  For example:
- Starting on 20m with VFO A
- Change to 17m through WSJTX (CAT)
- Press BAND- sets mcHF to 30m, not back to 20m

Also, the not-active VFO (B) is not changed by the CAT command as it is with BAND +/-.
Also, the sequence of bands for BAND +/- remains wrong until a power cycle.
Also, the text "Bndxxm" (e.g., Bnd40m) to the far right of the power (e.g., 5W) is not changed with the CAT command.

73,
Randy, KS4L

**Comment by db4ple** [comment]
Hi,

this is normal. You can achieve the same by dialing a different frequency by hand. Each band memory can be dialed to any frequency. The label (right , below meters) will show you the Band Memory Name.  For CAT you can set in the configuration menu "CAT in a sandbox" to "On". This will prevent the band memory from being overwritten by CAT commands. You'll see "CAT" in the label field then.
Switching bands manually makes the transceiver  "forget" the CAT frequency change.

73
Danilo

**Comment by KS4L** [comment]
Thanks! CAT in a sandbox works better.

**Comment by db4ple** [comment]
Please close the issue then. Thanks! Danilo

**Comment by KS4L** [comment]
Closed.
