### ISSUE TITLE
Warning low(weak) tension

### ISSUE THREAD

**Issue by ON5ZA** [df8oe/mchf-github#1086]
Hello Andreas,
I come by this circuit because I do not find the page to propose 
modifications.
He would not be interesting of indicate a voltage drop of the food to 
leave for example 11 volts or others by
  indicating him by one red blinking of "V" 
Thank you for the Gustave ON5ZA

**Comment by s53dz** [comment]
For better wording I would propose this issue name to be changed to "Warning on low supply voltage". It could also be an extension of an existing option "switch-off at low voltage" by just adding a warning level as an additional step in-between.

73 Bojan

**Comment by phaethon** [comment]
Existing voltage indicator implementation already change color based on thresholds which are calculated from switch off voltage. You can disable low voltage switch off, and play with with the switch off threshold to see how it works. Isn't this what you want?

**Comment by ON5ZA** [comment]
Thanks to all. I know that this change fe color of the tension exists. But I would wish that has to leave a certain low threshold "V" begins flashing in red. Simply that when you are qso there the change of color is not enough and your attention is not attracted. The blinking would be better a lot. ON5ZA

**Comment by phaethon** [comment]
Actually, it is flashing (also, green LED is flashing, as LED could be off), when the low power shutdown is scheduled. So, it is more a design decision when to flash. Current logic is that if it is important, then shutdown is enabled and then it is flashing. If it is not so important, then it is more informative and just a change of colour is more appropriate.
