### ISSUE TITLE
ExtIO.dll for HDSDR

### ISSUE THREAD

**Issue by WY5Y** [df8oe/mchf-github#1093]
Does anyone know which ExtIO.dll that the mcHF emulates? I've tried multiple .dll files, but no success yet. Any help would be greatly appreciated.

**Comment by DG9BFC** [comment]
no need for an extio driver
hdsdr works with omnirig driver ... that connects to mchf with selecting ft817 as the rig
in hdsdr set "sdr is on if output that is controlled by omnirig"
set "sync in both directions"
set 12000 in if frequency box and global offset to -12000 (i prefer low side mixing to see upwards from my own qrg)
set 700 hz in cw box (all other offsets set to zero)
select mchf soundcard as input for hdsdr and set mchf to iq in out (DIQ)
thats it :-)
now the hdsdr screen looks like the mchf screen (you see same spectrum and both stay in sync)
regardless if you turn vfo in mchf ... or change vfo qrg in hdsdr ... both are synced via omnirig driver
have fun ... sigi

ps iif you then use stereomix as input for any digital decoding soft then the audio from hdsdr is decoded properly ... you also can use multipsk cause it also can sync to rig via cat and can use iq in/out ... means multipsk has both in one sdr soft and digital soft ... and can sync to mchf :-)

**Comment by WY5Y** [comment]
Thank you so much. I was trying to connect to HDSDR using Ham Radio Deluxe at the same time. I could change frequencies and bands, but waterfall and spectrum scope wouldn't work properly. Thanks again.

**Comment by DG9BFC** [comment]
you are welcome :-)
if all is set properly then it sould work (it does here with hdsdr and multipsk)

**Comment by DG9BFC** [comment]
it is also explained in the wiki
https://github.com/df8oe/UHSDR/wiki/USB-CAT-and-AUDIO-Mode

scroll down to centre of page "sdr programs to use with i/q data"

there it says hdsdr ... "rig control via omnirig"

you can use any cat software to control the rig (be it via omnirig driver or or via hamlib driver)

only trouble you will get is if two different cat software wanna talk to the same comport (usb connector represents a virtual serial port in windoze)

that is the reason why you should stick with ONE ham suite and not mix two of them

means ... an good one is like dx lab suite ... spotcollector and logging ... both work fine with mchf (and my favourite digimode soft multipsk also talks to that same logboog dx keeper in the dx lab suite and does cat cntrol to mchf)

i never used ham radio deluxe so can not help you with the setup

**Comment by DG9BFC** [comment]
in my view ... issue can be closed

**Comment by undiplomatic** [comment]
I've been trying to configure mcHF to work with HDSDR but there is an issue with the offset. To get HDSDR to show the same spectrum the _RX TX Freq Xlate_ must be set to OFF in mcHF, which is not a recommended setting.

I followed Sieg's instructions and set the IF-Frequency in HDSDR to 12000 and the Global Offset to -12000 but now the tuned frequency in HDSDR does not match mcHF. I've spent quite a bit of time trying to configure this :/

**Comment by db4ple** [comment]
Hi,
what is your setting of CAT-DIQ-FREQ-XLAT ? See https://github.com/df8oe/UHSDR/wiki/USB-CAT-and-AUDIO-Mode#please-read-understanding-and-configuring-external-frequency-control-via-cat and https://github.com/df8oe/UHSDR/wiki/USB-CAT-and-AUDIO-Mode#sdr-programs-for-use-with-iq-data for a discussion on this topic.

**Comment by DG9BFC** [comment]
If you set offset in hdsdr abd mchf correct then they do match..If you have to set to minus or plus in hdsdr depends on how you set it in mchfI prefer to have the local above the rx cause then u see upwards from my own signal.. And dx stations usually work upwards split.Bo need for an extio driverOmnirig driver set to control the mchf via cat. Mchf soundcard select as input fir hdsdr... And set mchf to DIQ (digital raw iq data NOT AUDIO!)Try it.. Mchf and hdsdr can be well in sync... Clicking with mouse on screen in hdsdr or with finger on lcd of the rigIr tune vfo... In all cases all stays in syncDg9bfc sigiAm 01.01.2022 09:37 schrieb undiplomatic ***@***.***>:
I've been trying to configure mcHF to work with HDSDR but there is an issue with the offset. To get HDSDR to show the same spectrum the RX TX Freq Xlate must be set to OFF in mcHF, which is not a recommended setting.
I followed Sieg's instructions and set the IF-Frequency in HDSDR to 12000 and the Global Offset to -12000 but now the tuned frequency in HDSDR does not match mcHF. I've spent quite a bit of time trying to configure this :/

**Comment by DG9BFC** [comment]
Sorry for typos.. Typing on smartphone and pressed send a bit earlyAm 01.01.2022 15:23 schrieb ***@***.***:If you set offset in hdsdr abd mchf correct then they do match..If you have to set to minus or plus in hdsdr depends on how you set it in mchfI prefer to have the local above the rx cause then u see upwards from my own signal.. And dx stations usually work upwards split.Bo need for an extio driverOmnirig driver set to control the mchf via cat. Mchf soundcard select as input fir hdsdr... And set mchf to DIQ (digital raw iq data NOT AUDIO!)Try it.. Mchf and hdsdr can be well in sync... Clicking with mouse on screen in hdsdr or with finger on lcd of the rigIr tune vfo... In all cases all stays in syncDg9bfc sigiAm 01.01.2022 09:37 schrieb undiplomatic ***@***.***>:
I've been trying to configure mcHF to work with HDSDR but there is an issue with the offset. To get HDSDR to show the same spectrum the RX TX Freq Xlate must be set to OFF in mcHF, which is not a recommended setting.
I followed Sieg's instructions and set the IF-Frequency in HDSDR to 12000 and the Global Offset to -12000 but now the tuned frequency in HDSDR does not match mcHF. I've spent quite a bit of time trying to configure this :/

**Comment by undiplomatic** [comment]
It turned out to be a config issue in HDSDR, I had to reset all the HDSDR settings, start again, and it works.
It did take me several hours to get everything working, so to save anyone else the time, I put together a quick video, it's on YouTube now so should appear in any searches: https://youtu.be/cuMLVm1Uy3w
