### ISSUE TITLE
CW - red TX LED does not work right

### ISSUE THREAD

**Issue by s53dz** [df8oe/mchf-github#1098]
D2.5.111:
Issue is there probably already from the introduction of CW decoder, which uses the red LED.

When in the CW mode the red LED on receive is showing the CW code. When switching to TX the red LED remains in the state as it was in the moment of last received CW symbol for the whole period of transmission. It means it is lit or dark.

So, it can happen that in transmission the red TX LED remains dark.

73 Bojan

**Comment by DG9BFC** [comment]
an addition: if you push tune button it lights up for a short moment

**Comment by DG9BFC** [comment]
@correction ... now using 112 version ... and tx led is working when pushing tune button but only in "non cw modes" ... means ... in ssb, rtty, fm-n, am the tx led work with tune ... in sam and cw it does not

**Comment by df8oe** [comment]
I never never never have tried to TX in SAM - nice idea :)

**Comment by s53dz** [comment]
Frank,

D2.5.116: 
Now the red LED works ok when the TuneHelper is on and in CW mode going from RX to TX. I like this to be sure that the TX is on.
But, I have a question, or I did not get it right. The red LED now is dark on RX. Which does not bother me. But is it the TuneHelper now on AGC?

And when the "CW decoder display" is on, red LED still does not work on TX. Which I don't care.

73 Bojan

**Comment by DG9BFC** [comment]
tune button in sam now is disabled :-( ... in all other modes tune shows red led (txing)

**Comment by df8oe** [comment]
Why "sad smily"? What sense does TXing in SAM (please see ma post above)??

**Comment by s53dz** [comment]
D2.5.118,
The issue as in the headline is fixed.

TNX Bojan

**Comment by DG9BFC** [comment]
andreas ... that was a joke ;-) ... sure i will not try to do a qso in sync am ... but what if a user pushes that button (by accident)?!? ... now solved
