### ISSUE TITLE
Stuttering Tuning on USB/LSB after software update

### ISSUE THREAD

**Issue by g7jiq** [df8oe/mchf-github#1109]
After updating to the latest software D2.5.117.
When I tune USB or LSB the frequency readout momentary flashes red with a clunk in the sound.
This is worse the faster you tune or bigger steps taken.
AM is unaffected and this happens on any band.
Pria to the update all was fine, I have rolled back to a earlyer ver and the problem still exists.

Mayby the update upset something in the menu.
NB-: I am running the IC2bus 1 and 2 at 100khz as before.

I have just noticed this seems to only happen when the bandwidth is set to 2.3k / 1.7k

Has anyone any ideas ??? Is this normal.

**Comment by DG9BFC** [comment]
hmm ... i can select whatever filter ... and tune up and down ... and all is normal here
even very fast tune with dynamic tune switched on ... and i have no problem
i2c is running at 320 here (yes i know that is fast setting with red numbers ... but it works fine with NO FILTER CAPS ON THE BUS!!!)

**Comment by df8oe** [comment]
Maybe your config is corrupted by chance. Do you have backup in virtual EEPROM?

**Comment by df8oe** [comment]
Any progress?

**Comment by DG9BFC** [comment]
he should do a hard reset of the config (start with f1 f3 f5 pressed)

**Comment by g7jiq** [comment]
Will do a reset and let you know what happens.

**Comment by DG9BFC** [comment]
any progress?? (now we are at version 121)
