### ISSUE TITLE
LCD AFG No.

### ISSUE THREAD

**Issue by S52CQ** [df8oe/mchf-github#111]
I report another minor issue: if you check number at AFG, you will notice that when numbers are below 10 (i.e. 09, 08 etc.) the 0 number has one little vertical line on the left too much when RX to TX.. You can see that easily: set AFG to 08, press TUNE and you will see one tiny vertical white line that remains white, while the rest of the 08 number will become grey. This white line remains there also at RX until the AFG is changed to another number. Then number 0 becomes "normal" however as soon as you press TUNE, it gets this tiny vertical white line.

It's not a big problem that would disturb performance, mcHF is still functioning very good though.

73 de Jure, S52CQ

**Comment by df8oe** [comment]
Fixed already - this was an intermediate state. You got one or two versions where this was not corrected yet :) Thanks for the report!
