### ISSUE TITLE
Prioritizing issues

### ISSUE THREAD

**Issue by phaethon** [df8oe/mchf-github#1111]
I love that issues are categorized into enhancement, question, etc.
Can we add some sort of indication of priority - which issues are actively being worked on, which are planned for a distant future, and so on? Could be as a priority label or some virtual milestones.

**Comment by df8oe** [comment]
GitHub serves only the labels bug/duplicate/enhancement/help wanted/invalid/question/wontfix.
No further prioritizing possible. I have to edit each title manually to do so...

**Comment by db4ple** [comment]
You can use the milestones to implement priorities (Milestone "Urgent" , "Low Prio", ... ) or create labels for that purpose: https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

73
Danilo
I checked, and I could see a "New Label" button, so this will work.

**Comment by df8oe** [comment]
I have checked, too. No "new label" button. But I can use milestones.

**Comment by df8oe** [comment]
OK. I have found it. But I think we will better use milestones.

73
Andreas

**Comment by db4ple** [comment]
![2017-10-05_20-33-11](https://user-images.githubusercontent.com/17237769/31246055-833ef24c-aa0c-11e7-8ce2-4ba231ff7d6d.jpg)

When I click on the "Label" box, I get this
![2017-10-05_20-34-45](https://user-images.githubusercontent.com/17237769/31246130-add39b8e-aa0c-11e7-9f78-f311e5815e3a.jpg)

I think you were not looking in the right place. I am not saying it is intuitive but it was described in the link.

**Comment by phaethon** [comment]
Either priorities or milestones would work for me. Categories could be:

- "Immediate" (for critical bug fixes)
- "Next release" (for issues being worked on right now, expected to be ready within few weeks)
- "Medium term" (someone works on it, but it is either not simple or has dependencies on other unfinished issues, expected in 1-3 months)
- "Long term" (someone plans to do it, but not started, or it has many unmet dependencies)
- "Unplanned" (good idea, but not clear who and when will take it though most likely somebody will)
- "Undecided" (not clear if it has to be done at all, or nobody is interested to work on implementation)

**Comment by df8oe** [comment]
Hi phaeton,

this is a good base to start. I will think about it. But I think time spans must be shorter - think abut development speed of firmware:
"Urgent" == within next hours, max. 1...2 days
"Important" == within next 7 days
"Medium term" == within 1...4 weeks
"Long term, in work" ==  1...2 months
"Long term, noone is working on this" == someone who has the skill and time can fetch it :)
"Unplanned" == we must discuss if we will do it or not
"Dismissed" == we do not want to implement this

That is my proposal...

**Comment by phaethon** [comment]
Shorter time span ok for me.
For me the categories should express the expected delivery time and whether somebody has taken ownership of the issue and works on it. E.g. something can be important, but not possible to implement sooner than in a month. Something else can be not so important, but still somebody works on this and will soon be ready. Thus I would prefer "Short term" or "Next release" to "Important". Shorter alternative for "Long term, noone is working on this" could be "Unassigned". I don't see a need for "Dismissed", once it is dismissed it will soon be closed anyway.

**Comment by df8oe** [comment]
...and a new issue was opened every month again. We have had that in the past...

**Comment by phaethon** [comment]
Do you think people will carefully read the issue list before posting again? Also, the issue list might grow very long with time if we keep all dismissed issues. May be better have a Wiki section listing all requests, which we don't intend to implement, which might be requested multiple times?

**Comment by df8oe** [comment]
I have started "milestoning" ;) If that is satisfying your wish pse close issue.

**Comment by phaethon** [comment]
Milestoning is certainly an improvement. Closing the issue for now.
