### ISSUE TITLE
Do not turn off TX in WSJTX

### ISSUE THREAD

**Issue by UA9OLB** [df8oe/mchf-github#1113]
HI to All.
After upgrading to the latest software FW2.5.117 and FS2.5.118.The WSJTX program does not disable TX.
In FW2.5.15 everything works.
In FW2.5.16  not  checked (.

73!  Dmitry

**Comment by UA9OLB** [comment]
The same problem with the code was  issue number 1000

**Comment by UA9OLB** [comment]
HI to All.

What miracles I had with iron (computera.
Rechecked all the Fw from 115 to 119. Everything works !!!
The Issues  can be closed.
73! Dmitriy

**Comment by df8oe** [comment]
You have opened it - you are recommended to close it...
73
Andreas
