### ISSUE TITLE
Builds just a short .bin

### ISSUE THREAD

**Issue by s53dz** [df8oe/mchf-github#1133]
FW 2.5.122, from 17.10.2017
F4
CLI
make (all, bootloader)

Make returns just a 144 bytes long binary. Same for bootloader and firmware builds.

73 Bojan

**Comment by db4ple** [comment]
Thanks! So we shrunk the code a little more than expected.  I did not check the size after my make changes since build process looked good, with all files being compiled.

**Comment by s53dz** [comment]
Danilo,

I am good with 144 bytes, as long everything works, hi.

73 Bojan

**Comment by df8oe** [comment]
All object files are built - but not linked together...

**Comment by db4ple** [comment]
Yes, I already found my mistake. Will correct soon.

**Comment by s53dz** [comment]
FW now builds ok, but not so the BL.

**Comment by db4ple** [comment]
You are right. But luckily no longer. If Andreas would have been right, the fix would have worked, but for the bootloader we did not build all the required files...
