### ISSUE TITLE
Firmware question

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1138]
Is there a place that will tell us what is changed in each new firmware update??

If there is , I do not find it.
I do know of the auto generated menu document, but that doesn't really do what I am asking.

Something like: this version adds etc...

Thanks, Chuck WD8BXS

**Comment by df8oe** [comment]
Hi Chuck,

there is a short comment at each commit. You can find them here:
https://github.com/df8oe/UHSDR/commits/active-devel
Just click on a commit and you can see the comment which usually tells you what was changed by this commit.

73
Andreas

**Comment by WD8BXS** [comment]
Chuck

**Comment by db4ple** [comment]
Hi, I took the liberty to put Q and A into the FAQ section of the Wiki: https://github.com/df8oe/UHSDR/wiki/Firmware-FAQ

**Comment by WD8BXS** [comment]
Thank you!!
