### ISSUE TITLE
Windows 10 Fall Creators and Ubuntu 17.10

### ISSUE THREAD

**Issue by K2AAE** [df8oe/mchf-github#1140]
Windows 10 Fall Creators 1709 works with existing setup, still. Ubuntu 17.10 with gcc-arm-none-eabi-6-2017-q2-update works (the q2 hurt a little) with make. 
Note and question: After build there were bin, elf, dfu files in root, the Wiki shows only bin and how to generate the dfu, did I do something different?

**Comment by df8oe** [comment]
The dfu is ceated only by Makefile and uses small python script which resides in support/hex2dfu/.

**Comment by df8oe** [comment]
Please close issue if answer is satisfying.
