### ISSUE TITLE
No power out/ RF  Seems all else is working all bands. Just no power out.  

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1152]
All functions  are working correctly except there is no power out. I do I check to see if the RF transistor is working?  Please help.

WM0I #Pull-Request

**Comment by s53dz** [comment]
Hi there,

Have you done the PA configuration per this Wiki:
https://github.com/df8oe/UHSDR/wiki/Adjustment-and-Configuration-Manual#pa-power-calibration
?
I doubt it is a FW issue.

73 Bojan S53DZ

**Comment by WM0I** [comment]
Pull-Request

**Comment by df8oe** [comment]
If you have done all neccessary adjustments which are discribed in WIKI and you still do not have any output please take schematics and track the signal from the beginning (LO / quadrature divider) to the finals. It is a straight signal processing and easy to track.

73
Andreas
