### ISSUE TITLE
Rf Gain in Configuration menu showing error!

### ISSUE THREAD

**Issue by Derek1965** [df8oe/mchf-github#1165]
Rf Gain in Configuration menu showing error!. regards Derek.

**Comment by Derek1965** [comment]
Rf Gain in Configure menu showing error!. Regards Derek.

**Comment by DD4WH** [comment]
Hi Derek,
1. try the newest version, you seem to have a version which existed only 10 min and contained a small bug with Rf Gain
2. Where can you see Rf Gain in System Info??

**Comment by df8oe** [comment]
Thanks for reporting. We have noticed that already and fixed it. "Max RF Gain" was an obsolete entry of old AGC which is gone now.

If it is ok for you now pse close issue.

73
Andreas

**Comment by DD4WH** [comment]
Hi Derek, hi Andreas,
our comments crossed ;-)
Please Derek, could you try the very newest version and report whether the issue has disappeared or not?
Thanks in advance!
73 Frank

**Comment by Derek1965** [comment]
Just loaded 2.5.133 issue has now gone, Thank you everybody for your hard work. Derek
