### ISSUE TITLE
New Bootloader

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1168]
I believe that I read that you did not need P6 to load the newer bootloaders.

How exactly is that accomplished?

De Chuck WD8BXS

**Comment by df8oe** [comment]
Press&hold BAND+ and then power on mcHF. If the screen tells you you can release BAND+ **while power is pushed continuously the whole following time until the end of the process.** Now you are in DFU mode and can update Bootloader (and of course firmware, too) using DFU tools and related .dfu-file.

73
Andreas

**Comment by df8oe** [comment]
I have created page in WIKI: https://github.com/df8oe/UHSDR/wiki/Bootloader-Upgrades

73
Andreas

**Comment by WD8BXS** [comment]
Thanks
