### ISSUE TITLE
Error Code 4

### ISSUE THREAD

**Issue by Tibet4690** [df8oe/mchf-github#1169]
I am getting Error Code 4 when trying to upgrade to the latest firmware [2.5.134]. I am currently running 2.5.130.

I am attempting to use a Kingston Data Traveler which is USB 3.0 with a capacity of 32GB.

Any suggestions?

**Comment by Tibet4690** [comment]
As I submitted this I realized I am running bootloader version 3.4.1, the latest version is 3.4.2. Will see if this is the issue.

**Comment by df8oe** [comment]
Please use an USB 2.0 stick. STM32F4 does not support USB3.0

73
Andreas

**Comment by Tibet4690** [comment]
Thanks for the info, I must have used a 2.0 stick without realizing it previously!

**Comment by df8oe** [comment]
Please close issue if this solves your problem.

73
Andreas

**Comment by Tibet4690** [comment]
Ended up using the DFU method as I did not have a USB 2.0 stick available. Worked as expected.

Thanks again for the help and will be sure to mark closed.

**Comment by db4ple** [comment]
Hi, you don't need a stick with USB 2.0, but it has to be formatted using FAT/FAT32 (not exFAT, not NTFS).
