### ISSUE TITLE
Spectrum scope light mode not showing grid lines like they do when in scope mode. 

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1172]
When I set up the display to be in the spectrum light mode I don't see the grid lines. When I set the grid lines to any color all I get is a color bar on each side of the spectrum part of the display. Am I missing a setting for this function.

**Comment by db4ple** [comment]
Hi,
the spectrum light has no grid lines, I think, the  idea behind that was to have the most lightweight implementation of a scope, especially concerning the amount of graphical data to be sent to the display. 

73
Danilo
