### ISSUE TITLE
USB / Wireless / interface    for a keyboard?

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1173]
Is anyone working on doing firmware to get a keyboard interface and the software to use with it?

**Comment by df8oe** [comment]
Keyboard support via USB is already implemented. Actually it is used for RTTY and BPSK transmitting. Wireless keyboards with USB dongle are supported, too. BUT: only devices with ONE configuration can be used.

73
Andreas

**Comment by WD8BXS** [comment]
I got one of the small wireless keyboards that were recommended, it works, but my simple small usb keyboard that I use on my icom  does not.

Chuck WD8BXS

**Comment by WM0I** [comment]
Hi Chuck, which keyboard is that?

Richard WM0I

**Comment by WD8BXS** [comment]
Hi Richard,

I got this one:  https://www.ebay.com/itm/Rii-Mini-X1-2-4G-Wireless-Air-Keyboard-with-Mouse-Touchpad-NEW/253208748356?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649


Chuck
