### ISSUE TITLE
When keying the transmitter mcHF emits short chirp noise whith the PA at FULL power

### ISSUE THREAD

**Issue by isenburg** [df8oe/mchf-github#1182]
When I press the PTT with the PA set to FULL a short chirp sound is being sent. This also happens when using digi modes via USB. If you press the PTT a few times in quick succession, the problem does not arise. It does not occur using lower power settings. Firmware 2.5.130

**Comment by df8oe** [comment]
I am nearly sure it is a hardware issue. That can be:
- oscillating driver or PA
- influence via power supply (inner resistant of power supply and/or cables too high)

Of course there are other possibilities.

**Comment by stefendy** [comment]
I also added a 100 watt homebrew PA but did not get short chirp noise or other noise in the modulation, check: wiring, PA self oscilation, LPF on PA, shielding the middle between uiboard and rfboard

**Comment by df8oe** [comment]
Do you have solved your porblem? If so: please close this issue.

**Comment by isenburg** [comment]
I noticed that the adjustment and configuration settings are all back to default… I will run through the setup again. 

Am 27.11.2017 um 06:18 schrieb DF8OE <notifications@github.com>:

Do you have solved your porblem? If so: please close this issue.
