### ISSUE TITLE
PTT via virtual RTS

### ISSUE THREAD

**Issue by stefendy** [df8oe/mchf-github#1211]
When ptt via virtual rts then on external ptt pa / accesories not active, is it so or i missed a setting ?

-Bootloader 3.4.4
-Firmware 2.7.11

*Sorry for my bad english

**Comment by df8oe** [comment]
Sorry - cannot understand.... You can find this menu option in configuration menu. When activated you can key mcHF via RTS line.

For keying external devices you can use the ACC connector. But optocoupler which is used in mcHF by default works very poor. Maybe you need an additional switching transistor or replace optocoupler by opto relay.

73
Andreas

**Comment by stefendy** [comment]
I have activated ptt via virtual rts in configuration, and have replaced optocopuler, when ptt via virtual rts is turned on (by software) mchF has transmitting but on external ptt pin is unactivate  (not grounded) but when transmitting using ptt in mchf (uiboard J3) then on external ptt is also active (connected with ground)

**Comment by df8oe** [comment]
Thank you for clarification. Now it is clear. We will take a look at it.
