### ISSUE TITLE
2.7.26: LCD issue

### ISSUE THREAD

**Issue by df8oe** [df8oe/mchf-github#1238]
OVI40, 3.5" LCD: when switching to menu lower waterfall is not cleared. Cosmetical.

**Comment by df8oe** [comment]
In 2.7.28 problem is much bigger. Now parts of S-meter box is erased and not correctly redrawn after leaving menu.

**Comment by sp9bsl** [comment]
I see it too

**Comment by db4ple** [comment]
Ok, my fault. The I mixed the coordinates. Sorry. One more.

**Comment by df8oe** [comment]
fixed now.

**Comment by sp9bsl** [comment]
Hi Danilo,
now better but frames around function buttons are disapearing sometimes after menu exit

**Comment by db4ple** [comment]
Hm. Can't reproduce with 320x240 @ OVI40, but I have currently no 480x320 display / no mcHF for test. But I use the "official" screen area of the waterfall.

**Comment by sp9bsl** [comment]
it happens always after the second menu display. Voltage indicator disapears also for a while. I'll try to debug it.

**Comment by db4ple** [comment]
Hm. No clue yet, have a go.

**Comment by sp9bsl** [comment]
Have something, for the second call of UiSpectrum_Clear the sd.wfall_disp_lines changes from 70 to 140

**Comment by db4ple** [comment]
Hm. I think I know the problem then.

**Comment by db4ple** [comment]
Well this can only happen it ts.spectrum_size is neither SPECTRUM_NORMAL (0) nor SPECTRUM_BIG (1).
Please check that. But how this is changed?

**Comment by db4ple** [comment]
I have found the problem. It is the sequence of events. I will do a commit tomorrow morning to fix the problem.
In a nutshell: we calculate wfall_disp_lines before we actually calculate the correct size. And with that, we get the right result in the first call and wrong (doubled) results in all subsequent calls. 

Thanks for the hint.

**Comment by sp9bsl** [comment]
Ok, I always use SPECTRUM_BIG
