### ISSUE TITLE
Can the time delay from TX to RX be adjustable?  Question

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1246]
I would to try and adjust the time delay between TX to RX to see if one of the problems with audio blasting or muting From when you let up on the PTT.    I hope I am not asking to much.

WM0I

**Comment by db4ple** [comment]
It is adjustable. Just go to Configuration menu. 

While you are waiting for us to answer, have a look at
https://github.com/df8oe/UHSDR/wiki/Operating-Manual---Menu#menu-overview-automatically-generated . The document linked there explains all menu entries and is up-to-date.
