### ISSUE TITLE
Trying to do the entire Adjustment and Configuration manual. Help

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1266]
First:  Setting the PA Bias I get different results that can be between 31 to 81 depending which band you are making the PA Bias in. This causes the attempt of setting each band to 5 watts hard to do. If you can't back the power down to 5 watts you have to go back to the PA Bias and lower the value so you can set the power to 5 watts. This happens to every band and changing the PA bias level for one band makes the other bands wrong.

Is there a better method in setting the PA Bias that will satisfy all the bands without this problem. 
This problem also makes setting the TX IQ's correctly.

I need help with this please!

**Comment by sp9bsl** [comment]
Hi Richard,
there is no need to have bias setting for every band. This is the first step of callibration at the very beginning of work with PA. This is simply the first rule for the mosfets! Then you set the apropriate level of signal for 5W and maximum power. If you start to change the bias instead of signal level, you enter in very non linear mode. I have bad feeling that there is something wrong with your PA if you need to do it for every band.

73 Slawek

**Comment by WM0I** [comment]
Yes I now see a problem with the PA. I need a schematic of the PA board. Where do I find one?

WM0I

**Comment by sp9bsl** [comment]
You have to check the pcb version number on RF board and visit M0NKA site, he has schematics for all available versions in download tab, please search there. If you have a clone - RF board is more or less similar to v0.4.

**Comment by Harry-ei6ku** [comment]
I have simular problems with the RF power across the bands, ( its a clone radio ), RF power varies widly across the bands, in excess of 15W on low bands, and lower power settings have little effect on actual RF output. I suspect the RF mosfets are the problem (not genuine parts).

Update: re did the PA bias cal as per the guide, and also set the "reduce power option" for both low & hi bands (in PA settings) I was then able to correctly adj the power to 5W on all bands, and full power is also now approx 10W all bands (8Watts on 10meters) measured on a LP100A. (I didnt need change the mosfets).

**Comment by Tibet4690** [comment]
Have a clone myself, following this topic with interest! Been meaning to go through and verify my TX power settings, you have me worried about what I'll find when I get around to it.
