### ISSUE TITLE
Does not work  "DSP A-NOCH"

### ISSUE THREAD

**Issue by ly2bok** [df8oe/mchf-github#1270]
In the latest versions, the SDRmcHF does not work a "DSP A-NOCH" filter.
LY2BOK Justas

**Comment by DD4WH** [comment]
yes it does work!

but not very good at the moment, that is right.

Have a look at the Wiki:
https://github.com/df8oe/UHSDR/wiki/Noise-reduction

Currently there is much work going on in this field. Until we have finished it, you have two options:
1. take the release version or an older version of the daily builds OR
2. live with the recent functionality

73 Frank

**Comment by ly2bok** [comment]
Ok .Thanks, Frank.
We are waiting.  73!
