### ISSUE TITLE
No power out on out-of-band

### ISSUE THREAD

**Issue by stefendy** [df8oe/mchf-github#1277]
There is no power out when transmiting on the outside of band, on menu configuration tx on out-of-band is ON ( ptt switch can be active but not out power ), request for power to get out on out-of-band.
Thanks in advance

de YF9RAK

**Comment by db4ple** [comment]
The power out of band is minimal (in the mW region for most of bands). Lower bands have slightly higher output. Out-of-band-TX is not supposed to be used for radio transmission (this is clearly against the laws for amateur radio), only as a signal generator for measurement purposes. 
In case you don't like this: This discussion we already had. And no, we are not going to change that. It is all open source, if you don't like it, you can break the laws for yourself but don't ask us to do it for you.

73
Danilo
