### ISSUE TITLE
Future enhancement if possible. Bluetooth headset. 

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1278]
Will there be in the near future the ability to plug in a bluetooth dongle to connect a headset or keyboard?

**Comment by db4ple** [comment]
Short: No.
Longer: Someone has to write or port a USB bluetooth stack to do this. Nothing for the faint of hearted people like the current developers and the current software architecture of UHSDR :-( . 
You will have to use the analog line in/out connectors for that purpose.

**Comment by WM0I** [comment]
I think I am going to look into using a raspberry pie to interface to the mchf.  I would like to use the rtty function for passing traffic.

Thanks
best regards
WM0I

**Comment by SergiuEpure** [comment]
I can connect a keyboard adapter and keyboard itself direct to usb port of mchf and write text
