### ISSUE TITLE
UHSDR Wiki - dead link to KA7OEI SW summary

### ISSUE THREAD

**Issue by DF9TS** [df8oe/mchf-github#1279]
Wiki ( https://github.com/df8oe/UHSDR/wiki ) contains dead link. See section "Using the UHSDR firmware",  "... you can find here ..." Underlying hyperlink is dead (https://github.com/df8oe/UHSDR/raw/active-devel/mchf-eclipse/useful_manuals/mcHF_Operators_Manual_firmware_ver_0_0_219_26.pdf )

KA7EOI doc can be fand in mchf-eclipse->useful manuals->old manuals.

Minor detail, but consider with low prio. Any newcomer in the project will stumble on such things...

73

Gerd.

**Comment by db4ple** [comment]
Hi Gerd, 
you are invited to fix that: the problem is the rename of the repository I think: mchf-eclipse is now UHSDR. And we moved the document to a sub folder in addition (oldguides).

Thank you,
Danilo

EDIT: You just have to click on EDIT while you are on a wiki page to change it.

**Comment by DF9TS** [comment]
Done.
