### ISSUE TITLE
Noise floor dramatically increases with digital out but not DIG I/Q?

### ISSUE THREAD

**Issue by Tibet4690** [df8oe/mchf-github#1281]
If this is a noob question feel free to tell me so, I'm still learning.

When using fldigi or wsjt-x my noise floor increases dramatically. 

This seems to be tied to using the mic/line select "digital" setting.

I at first thought this was due to RFI from my laptop, but now my novice opinion has changed... I fooled around with HDSDR with omrig. When using this setup I did not experience the same change in my noise floor even though I am using the same laptop, usb cable, radio, etc. 

Can anyone explain this to me? 

Thanks for the input

**Comment by df8oe** [comment]
Sorry - I do not undrstand.

If you use SDR software like HDSDR or QUISK you need to set DIQ (which means "digital out i/q") and if you want to use digital modes software like fldigi, MSSTV and so on you must use DIG (which means "analog audio via USB"). Of course you cannot compare the noise floor of both because one is audio and the other one is I/Q.

73
Andreas

**Comment by Tibet4690** [comment]
Thanks for the reply, perhaps it is an issue of using the wrong terminology on my part. I'll try to better clarify what I am saying.

> If you use SDR software like HDSDR or QUISK you need to set DIQ (which means "digital out i/q") and if you want to use digital modes software like fldigi, MSSTV and so on you must use DIG (which means "analog audio via USB").

That bit I understand.

The issue I am having, when I use DIQ to HDSDR/omni-rig I see no interference from my laptop. However, when I use DIG to send analog audio to fldigi, wsjt-x, etc the ambient background noise (that I assume is RFI from my laptop) increases substantially. Say without fldigi running but the USB plugged into both my laptop and transceiver there is 1 s-unit of background noise, the second I open fldigi this climbs to 2-3 s-units.

Does that make more sense?

Thanks again for the help.

**Comment by DG9BFC** [comment]
hmm just a guess ... in fldigi the cat is used for ptt and frequency??? maybe the cat commands are producing traffic on usb cable (polling of freq each half second or so) ... do you also use cat in hdsdr (sync frequency of mchf and hdsdr)??? there you have the omnirig settings (where you can select poll intervals etc.)
if you do not use cat in hdsdr ... then we found the noise source (usb traffic)
try with some ferrites ... a longer cable and some distance plus ferrites may help a bit
... i can only tell that from my tests with different sdr on usb port of my laptop
best results (lowest noise) was with a bit longer cable, some ferrite cores ... and the sdr grounded on the antenna input (and laptop floating rf wise cause it has no direct ground connectin elsewhere)

**Comment by Tibet4690** [comment]
After experimenting some more last night I think you are right, this has to do with rig control, the interference appears to be there on hdsdr when using omnirig

I had some clip on ferrites on the cable but the noise still was there. I'm going to try looping the cable through some larger clip on ferrites to see if that has any effect.

You mentioned the polling rate can be changed... should I be playing with that to see if I can mitigate the interference that way?

I am in an apartment so grounding can be a little interesting... outside of that, I'm operating portable.

**Comment by DG9BFC** [comment]
so at least we found the noise source :)
to get rid of that noise ... is then on your end
if ferrites plus longer cable does nothing ... then your usb noise gets into the rig via the antenna (you said you live in an apartment so i am guessing your antenna is close to shack??)
good luck
ps an you test with another pc?? other laptop borrowed from a friend??

**Comment by Tibet4690** [comment]
Great info thanks, lots to learn.

Yeah, I've tested with my desktop and laptop. So doesn't seem to be machine specific. 

I've been playing around with a random antenna to an MFJ QRP tuner, but I've also played around with other antennas with the same result.

**Comment by DG9BFC** [comment]
also checked with a dummy??? does it get into mchf via the usb cable (common mode current/noise) or via antenna ??? ... you said you tested that vith a random wire plus tuner ... that is the worst setup for noise cause antenna is as close as it can get with such a setup
is it the same on all bands?? same on upper and lower end of a band with high noise ??
if you have that noise ... with a dummy load and ferrites on the cable ... then i am guessing you have to live with it ...

**Comment by DG9BFC** [comment]
can we close that issue?!?
