### ISSUE TITLE
Version 2.7.45   "fonts"   Some like / some don't .  

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1292]
Version 2.7.45   "fonts"   Some like / some don't. All in the eye of the beholder I guess.I personally like the old font. But after reading a few of the comments from McHF groups the new font is what they like. I know there is not enough room in the ram to do both. Question can two releases be made for each font?  2.7.45a and 2.7.45b. Just a thought.

Best regards
WM0I

**Comment by sp9bsl** [comment]
I vote to revert to old fonts. It doesn't look good on 480x320 screen (hard readable).

73 Slawek

**Comment by WM0I** [comment]
I agree, New font is hard to read. I vote to keep the older font.

**Comment by maaberu** [comment]
I hope,Who add Font switch in menu Item.
Old fonts are smart, but There is no personality.
New fonts are 90's video game like ,"KAWAII".
The Source code into New and Old fonts selectable at building.

**Comment by KJ6ZH** [comment]
Do not like that new font.  Terrible on the eyes.
Previous version is clean, easy and quick to read.

**Comment by df8oe** [comment]
I was much exited about the reactions (of course it is absolutely simple to switch back). There will be much more features in future which "some like and some don't". I am thinking about how to handle this. Actually we need a decision and proceed with one of the alternatatives. But that must not be forever this way ;)

**Comment by db4ple** [comment]
I vote to disable the new font (not to remove it). With fixed-size fonts we can make the font set dynamically selectable via menu relatively easily (as long as the new font set uses the same character sizes). 

If someone wants to do this as a learning excercise for UHSDR development/GitHub, I am happy to help...
73
Danilo

**Comment by df8oe** [comment]
I have already done that.

**Comment by db4ple** [comment]
What? Dynamic selection of font set via menu or switching of the new font?

**Comment by df8oe** [comment]
Disabling the new font.

**Comment by db4ple** [comment]
Ok, of course 👍 My offer was for the second part (dynamic selection of font sets via menu).

**Comment by sp9bsl** [comment]
I think if woludn't be good to have a folder (for example in official release zip file) with pre alfa when we want to publish something contentious (like the visual aspect) or have some kind of sanbox, just to make some kind of survey to know what most users prefer

**Comment by maaberu** [comment]
Thank you all.

**Comment by DF9TS** [comment]
@Danilo: Can volunteer to do this (dynamic selection of font sets via menu) in case this can wait a bit.
Waiting for the pending hardware delivery (OVI40 UI kit &  dispay). So could start in January.

**Comment by db4ple** [comment]
Let me know when you're ready.
73
Danilo

**Comment by DG9BFC** [comment]
nice would be if we had an online firmware builder and a homepage where a user can select what gimmicks he wants in the fw and what not and maybe also what cpu he has ... select the functions ... press on "build now" ... and then he gets a binfile built for his needs (and if he has selected too many thingys with a warning that it will only work in bigger cpu') ....
