### ISSUE TITLE
If you are for more Ram room here is a suggestion. 

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1293]
Here is something I never understood From the time I did a lot of CW. I grew up on learning the code so I could upgrade. The only time I used a code reader was to make my fist more readable. Never used it to hold a conversation did believe it didn't helped increase my CW speed. so on my part if you deleted all the functions that was there to help the code reader save a lot of space and save processing time for other things such as NR and notch filters. I know I should have my hands slapped for typing such a thing. To me code reading is no more than RTTY and we already have that.

Best regards
WM0I

**Comment by db4ple** [comment]
Hi,
most functions do not use processing power if not used. So from that point of view simply don't use the CW decoder. 
Many functions do use RAM (which is the most precious resoure) even if not in use. Only a few of them use significant amounts of RAM. Most of the RAM is used by the main functions (spectrum, audio processing) with one exception, that is FreeDV. This uses a lot of RAM. And at the moment that would be the only candidate which would make difference.
Another resource is non-volatile memory in the form of flash. This is were code and read-only data such as font information is stored. Some units have only 512k which is not much. But we still have about 70k or so available. 

And you can be sure, that we monitor the growth of use of resources carefully. 
Please close this issue. Thank you.
