### ISSUE TITLE
CW Beacon

### ISSUE THREAD

**Issue by iw2fiv** [df8oe/mchf-github#1296]
May be a good improvement add a function to send a "mycall/b" msg to operate on reverse beacon service

**Comment by DF9TS** [comment]
"mycall/b" not required for RBN. Normal "cq cq cq de mycall mycall mycall" works nicely with RBN.

**Comment by S52CQ** [comment]
Or you can program one of the CW memories...

**Comment by RightRudder** [comment]
Where are these CW memories?  I can't find them or documentation about them.

**Comment by df8oe** [comment]
Thea are alpha stage - not yet documented and not yet ready. And no official documentation available. Because of I don not use CW actually I do not know, too. But someone will answer - I am sure ;)

**Comment by phaethon** [comment]
@RightRudder See memory description under Digimodes in Wiki. 
I suggest we close the issue as it can be done using memories. What we miss at this point is 1) saving memories to EEPROM; 2) repeating beacon. Both are in other issues, so no use to keep this as a separate issue.
