### ISSUE TITLE
PTT switch problem

### ISSUE THREAD

**Issue by stefendy** [df8oe/mchf-github#1303]
Please help,
When transmitting via ptt switch the radio does not transmit ( always rx ), but if tranmitting via usb virtual rts the radio can transmit normally.

**Comment by df8oe** [comment]
Hi,

I am nearly sure this is not a firmware problem but a hardware problem. Only not-hardware related problem may be an operational issue (e.g. disabling TX in menu - don't know if this disables TX by USB, too).

GitHub issues are only responsible for handling firmware problems of UHSDR and bootloader.

In case of hardware issues there are two websites for getting support:

- the [official Yahoo monka newsgroup](https://uk.groups.yahoo.com/neo/groups/M0NKA-mcHF/)
- the [discussion board of theGerman mcHF project group](https://www.amateurfunk-sulingen.de/forum/index.php?board=15)

Many thanks for your understanding!

73
Andreas
