### ISSUE TITLE
New touch calibration: drawing test on 3,2" TFT does not work correctly

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1305]
with 3,2" TFT the touch calibration works ufb but the drawing test at the end does not work correctly.
It only works on the upper half of the display and the drawing line is havy speckled (dotted)

There is no problem with 2,8" or 3,5" displays

Forum:
https://www.amateurfunk-sulingen.de/forum/index.php?board=19;action=display;threadid=905;start=0

![drawing](https://user-images.githubusercontent.com/34752440/34339649-3aa5f698-e977-11e7-9565-daa2ce17b287.jpg)

**Comment by sp9bsl** [comment]
Hi Thomas,
I found something, let's see if it helps.  #1307 

73 Slawek

**Comment by ghost** [comment]
Hi Sławek,
yessss, it helps!
Drawing test now works over the complete display area.
It's still speckled, but this is only cosmetic.
Touch is very precise at all points of the TFT
many thanks
Thomas

![drawing2](https://user-images.githubusercontent.com/34752440/34356061-aaab62de-ea3a-11e7-9a38-e91f944f5ed8.jpg)

**Comment by df8oe** [comment]
Please close this issue.
