### ISSUE TITLE
2.7.49? What is the purpose of the update?

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1306]
I read all the comments for each line of code and all I could get out of it was new documentation for the menu structure. Did I miss something? I just went back the code and saw nothing other than menu structure.

**Comment by df8oe** [comment]
We are discussing UHSDR related themes in our discussion forum - section "UHSDR". You can read there - and if you want to write something feel free to register...

https://www.amateurfunk-sulingen.de/forum/index.php?board=19;action=display;threadid=905

**Comment by DG9BFC** [comment]
or in short ... version 2.7.49 adds touch screen calibration

**Comment by sp9bsl** [comment]
I explained the purpose of the changes here: #1310 .
Please close this issue.
