### ISSUE TITLE
New touchscreen functionality

### ISSUE THREAD

**Issue by sp9bsl** [df8oe/mchf-github#1310]
Hi, 
starting from the 2.7.49 we implemented completelly different approach to touchscreen. It is now mandatory to use calibration at powerup before use, the old calibration will not work.
So please:

**TO ENTER CALIBRATION, PRESS AND HOLD THE TOUCHSCREEN AT POWERUP** 

and follow the steps shown on the  screen. After the calibration finished and the rig works normal, save the settings with holding the MENU button as usual.

Purpose of this change is to enable new functionality to the rig, including resizing the waterfall/spectrum "on the fly" and more like virtual keyboard... So please be patient and report issues here, we'll work on it.
BTW the zeroing the least significant digits of frequency display works from now by taping on it (removed from the TUNE button).

73 Slawek

**Comment by sp9bsl** [comment]
Hi,
since 2.7.69 we have ability to change the ratio of Spectrum to Waterfall display. To enter this mode please press and hold the graticule (frequency bar) and select new position for it, then press |SAVE|.
To store it permanently, do it as usual: long MENU press. Have fun.

73 Slawek

**Comment by ghost** [comment]
Hello Sławek,
thanks for that nice feature, I test it this afternoon

**Comment by df8oe** [comment]
This has been described in GitHub WIKI and amateurfunk-sulingen WIKI now and can be closed.
