### ISSUE TITLE
Spurs when xlate is ON

### ISSUE THREAD

**Issue by sh123** [df8oe/mchf-github#1313]
Hello, 

I'm new to MCHF, latest HW, device is calibrated according to the tutorial, using it with firmware version 2.6.0, when XLATE is ON there are spurious emissions present and especially strong signal at -12 kHz XLATE. Is it something related to the firmware or some construction mistake?

![](https://i62.servimg.com/u/f62/19/62/65/46/spurio10.png)

**Comment by df8oe** [comment]
-12KHz seems to be the LO frequency. This supr cannot be suppressed by firmware - only by hardware. Normally it is suppressed 50dB or better. If so: everything is fine. If not: hardware issue...

**Comment by sh123** [comment]
Problem was solved some time ago. Just note, that it turned out to be excessive bias on the finals. After proper additional tuning all is good enough.
