### ISSUE TITLE
Slow Scan receive filter and bandwidth functions would be great.

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1315]
I think all that would be needed would be filtering adjustments and bandwidth settings.

No need for the display to decode the slow scan. There are a few great decoders already for window and android computer and tablets.
Best  regards
WM0I

**Comment by DG9BFC** [comment]
filtering adjustment (free setable by user) is not easy .... but adding some more precalculated filters could do the trick ... as far as i remember one of the programmers is/was working on this .. but maybe he has something different in his view right now ... 
he promised to add more filters ... so just wait a bit :-)
you can use the "normal" ssb filters for sstv ... no need for a special filter in most cases (cause the sstv sf also has some filtering) ... only if you have some signals close to the sstv qrg that spread inside the receiving filter ... only then a narrow filter does help a bit

**Comment by df8oe** [comment]
Filtering needs horse power. The better the filter is designed the more horse power it needs. So in my view the only way to go is:
- implementing a base set of filters which are neccessary for "standalone working" covering all implemented (!!) digital modes
- leaving "better" filters to the PCs, tablets and smartphones which are connected to radio

"Great decoders" normally do have their own implementation of very special filtering - no need for adding something for external programs to UHSDR.
