### ISSUE TITLE
Ver 7 display

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1320]
Will all of the latest firmware work on the v7 units, as it does not have SPI display?

**Comment by sp9bsl** [comment]
Hi,
yes. Noone complained as yet. This is the same interface like in the OVI40 board (same 3.2" display).

73 Slawek

**Comment by df8oe** [comment]
A short view on schematics does not show any difference in signal connections. So I do not see any reason why it should not work.

73
Andreas

**Comment by Harry-ei6ku** [comment]
Any thoughts on how the front panel buttons will work between version 0.6 and 0.7?
0.6 supports 17 front panel buttons, and the tuning encoder push button makes 18.
0.7 seems to only have 14 front panel buttons and an encoder push button, so Im assuming 15 in total.

73
Harry

**Comment by db4ple** [comment]
The UHSDR firmware right now supports 17 buttons and 4 encoders as in the original mcHF layout.
No matter how many buttons you see, right now the 17 supported button connections have fixed meaning as seen in the mcHF 0.4 - 0.6 button layout. You should check the 0.7 schematic and probably you'll find that the 3 side encoders also have push buttons internally and are connected to M1 to M3 GPIOs: 14+3 = 17 buttons

73
Danilo

**Comment by WD8BXS** [comment]
Well, Andreas, that sounds nice, but I have no idea what you said! 

Sorry,
Chuck

**Comment by db4ple** [comment]
Hi Chuck,
this comment was a response to the comment made by Harry, hazzer23 regarding buttons, not your original question regarding displays. Harry should  have asked this in a separate issue or in the available forums and we would not have confused you.

73
Danilo

**Comment by WD8BXS** [comment]
Thank you, sorry about my other reply to the post on the buttons, as I was confused...hihi

Chuck

**Comment by WD8BXS** [comment]
Roger that, It had my head spinning, LOL,,,Have a Great New Year my Friend,


de Chuck WD8BXS

**Comment by DG9BFC** [comment]
so issue can be closed???

**Comment by WD8BXS** [comment]
Yes, thank You all!!
