### ISSUE TITLE
Red LED has tooo many functions

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#1322]
if we use noise reduction (threshold is controlled via red led) plus cw decoder (also on red led) we have two functions on same led on receive (plus tx led) .... should we not move one of the two to the green led?!?
ok then in cw mode both led would flicker ... but that way we could finetune cw decoder AND noise reduction .... now we have both on red led so you can only set noise reduction without cw decoder ... or cw decoder without noise reduction (or it is difficult to find the right setpoint)

**Comment by df8oe** [comment]
Red LED is only needed for developing purposes.

Please ignore it if you don't like it.

**Comment by DG9BFC** [comment]
i know that the led is for developing ... but it is difficult to use if you have two functions on same led (cw decoder thershold and nr vad threshold) ... thats why i asked to move one of the two to the green led (also only for development not for permanent usage) ... then setting nr and setting cw decoder could be finetuned for perfect (or near perfect ) decode

**Comment by df8oe** [comment]
It is recommended NOT to activate NR during CW - so no impact of both functions.
