### ISSUE TITLE
missing Display refresh while XVTR Offset changing

### ISSUE THREAD

**Issue by OE1FHB** [df8oe/mchf-github#1332]

**Comment by OE1FHB** [comment]
STEP from 1Hz to 100kHz the underline Marker Change correct the Position if you select lower or higher
STEP.
Choose STEP 1MHz , new Marker is placed correct , reduce STEP to 100 kHz ,1MHz Marker is not removed, now you have to Markers !
Leave Menu : 1MHz Marker still exist , 1MHz and 10 MHz Step can selected once , then only 1Hz to 100kHz as normal.
1MHz Marker can only replaced when switching OFF.

**Comment by DG9BFC** [comment]
in version 2.7.60 i can not set 1mhz step ... biggest is 100kc

**Comment by ghost** [comment]
2.7.60 up to 10MHz !

**Comment by df8oe** [comment]
This is fixed with commit #4c4290c (version 2.9.38)
