### ISSUE TITLE
3,5" TFT: "waterfall only" used only half area. 

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1339]
If we switch to "waterfall only" we can see only a waterfall in the upper half of the area.
"spectrum only" used the full area.

only a minor bug with low priority

73!
Thomas

Thread on OV I40 Forum:
https://www.amateurfunk-sulingen.de/forum/index.php?board=19;action=display;threadid=943;start=0#lastPost

![water](https://user-images.githubusercontent.com/34752440/34919833-4a8391ea-f969-11e7-9f80-39af2ff3b351.jpg)

**Comment by sp9bsl** [comment]
Hi,
I think this should work since 2.7.69

73 Slawek

**Comment by df8oe** [comment]
so it is...
