### ISSUE TITLE
CW Via Keyboard

### ISSUE THREAD

**Issue by ei2gyb** [df8oe/mchf-github#1341]
Are you able to send CW via the keyboard like with RTTY ?

Thanks

EI2GYB

**Comment by ei2gyb** [comment]
Any update on this ?

**Comment by db4ple** [comment]
Hi,
I thought I answered that one already, seems I was wrong: Answer is no. CW is via keyer. And as far as I know no one is working on using a keyboard for CW. 

73
Danilo

**Comment by ei2gyb** [comment]
Ahh thats a shame - I dont know CW but it would be a handy feature to have on the radio so i could do Sota activation's as well as ssb voice

Thanks again Danilo.
Steve - EI2GYB
