### ISSUE TITLE
Free DV 700c Mode?

### ISSUE THREAD

**Issue by ei2gyb** [df8oe/mchf-github#1347]
Are there any plans to add the FreeDV 700c Mode to the radio?

Steve EI2GYB

**Comment by DG9BFC** [comment]
as far as i know the 700 modes need too much ram (for the forward error coding/ decoding) ... 
but i can not say precisely ... the clever programmers may better give a correct answer (and maybe the code could be added cause deleting old notch and nr freed up some ram)?!?

**Comment by df8oe** [comment]
Yes we will add it. But it will not work on mcHF due to MCU lack. But on OVI40 it will work :)

**Comment by db4ple** [comment]
Hi,
btw, I don't think it is much more RAM for 700c but for sure more cpu power. That is why the STM32F4 is very likely to be not sufficient for 700c. 

73
Danilo

**Comment by DG9BFC** [comment]
david rowe is working on a 700 d mode
he wrote ... low cpu power and low ram needed ... he just needs some "coders" to work with him
maybe we can get the 700d mode inside mchf'?!?

**Comment by db4ple** [comment]
I am pretty sure we can. At least in the OVI40 there should be no issue. However, low ram and low power are fairly relative. For the mcHF anything with more ram or performance requirement, even slightly more. is almost too much.

**Comment by DG9BFC** [comment]
if the 700 d mode does not need more as the 1600 mode it should be possible

**Comment by df8oe** [comment]
If you are satisfied with the informations: please close this issue. Thank you!
