### ISSUE TITLE
Can not turn waterfall off and scope on. 2.7.65

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1351]
After loading version 2.7.65 I was not able find where to switch waterfall over to scope in the menu's. I went to the code to see if it was taken out of the firmware. It was not, it was still in the code. Also so when I went back to version 2.7.31 the menu structure was not updated back.  I had to do a backup from the menu to reset the menu structure. I was then able to get back to what I had before.

I was not able to do more testing on the new version.

Regards

WM0I

**Comment by sp9bsl** [comment]
Hi,
I see the problem. I was focused on touch actions, not on the menu item, sorry. Fixup will follow today.
For now you can switch it by touch action (selecting from the upper bar).

73 Slawek
