### ISSUE TITLE
2.7.68 test report.

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1360]
High noise as soon as I turned on the new firmware. Red light on all the time even after cycling a couple of times. I opened up the DEBUG menu and made several adjustment even did the release. No help.

One step backwards. 
regards

WM0I

**Comment by df8oe** [comment]
**I cannot confirm your report in any way.**

Hmmmmm..... Maybe not good test?

There has absolutely nothing changed that can influence the noise level.

Staying on "bleeding edge".

73
Andreas

**Comment by Harry-ei6ku** [comment]
Im not seeing a higher noise floor on my mcHF using 2.7.69. If anything the noise floor is lower on the recent firmware releases ... -114 dbm (uncalibrated internal meter and no antenna attached).

73
Harry

**Comment by RightRudder** [comment]
I can also confirm I have seen no difference in noise level with 2.7.69 FW on my v0.7 machine.

**Comment by df8oe** [comment]
I will correct topic naming because it does not show reality.
