### ISSUE TITLE
2.7.69 problems on RS918

### ISSUE THREAD

**Issue by lb5va** [df8oe/mchf-github#1366]
V2.7.48 seems to work nice with mine 918. Tried 2.7.69 today. Not good. To small spectrum/big waterfall. Touch does not work when trying to change digital mode. Touch did also not work for changing scope/waterfall view, or jumping in frequency.

**Comment by sp9bsl** [comment]
Did you calibrate the touchscreen (#1310)?

**Comment by lb5va** [comment]
NICE!
Reloaded the .69 and did calibration. All working ok.
Thank you. 

 #LB5VA_Stig_______73_ 
Vennlig hilsen Stig Rasmussen 

      Fra: sp9bsl <notifications@github.com>
 Til: df8oe/UHSDR <UHSDR@noreply.github.com> 
Kopi: lb5va <lb5va@yahoo.no>; Author <author@noreply.github.com>
 Sendt: Lørdag, 27. januar 2018 12.20
 Emne: Re: [df8oe/UHSDR] 2.7.69 problems on RS918 (#1366)
   
Did you calibrate touchscreen (#1310)?—

**Comment by lb5va** [comment]
All problems mentioned is ok after calibration of touch. Thanks!!!  Also loaded the .70 from today.  
:-)
