### ISSUE TITLE
Radio Rebooting (Cycling) on power down Fixed.

### ISSUE THREAD

**Issue by ei2gyb** [df8oe/mchf-github#1373]
Hi there, 

just an update for you.
I have a mcHF clone (RS918) i have had problems with the radio rebooting or cycling at power down.
I have just updated to the latest Firmware & Boot loader (2.7.72 / 3.4.6) and this stopped the cycling issue.

Just thought id let you guys know
Best regards

Steve EI2GYB

**Comment by df8oe** [comment]
Thank you for reporting. That was the reason I reeimplemented old code. No idea what goes wrong at your radios and at hundred others not using bootloader without additional time loops. It is a workaround without knowledge what is the issue.
