### ISSUE TITLE
2.7.74 is not loading on 512k flash and 192K ram

### ISSUE THREAD

**Issue by Harry-ei6ku** [df8oe/mchf-github#1375]
Morning

2.7.74 is not loading on mcHF with 512K flash and 192K ram, reports error as too small.
2.7.73 loads OK

73
Harry

**Comment by sp9bsl** [comment]
Hi Harry,
did you try the right version? (MCU_512KB folder)

73 Slawek

**Comment by Harry-ei6ku** [comment]
Ah...  yes my fault.... thats it loaded.

73
H

**Comment by df8oe** [comment]
Many thanks for your testing if detection of wrong binary works ;)

73
Andreas
