### ISSUE TITLE
DSP A-NOTCH

### ISSUE THREAD

**Issue by ly2bok** [df8oe/mchf-github#1376]
I want to ask the respected programmer.Est in terms of making the DSP A-NOTCH filtr at a level as in version 1.5.130. There it works perfectly, and in the latest versions it does not work at all. Very useful feature when working on the air.
Thank you,
Justas LY2BOK

**Comment by df8oe** [comment]
We are actually working on NR feature which is bundeled with manual and automatic notch filter. So this area is "under construction" at the time. Old notch filter must be switched off because it is part of old NR (which never worked). Please stay tuned.

vy 73
Andreas

**Comment by ly2bok** [comment]
OK. Will wait.
Justas LY2BOK

**Comment by df8oe** [comment]
finished.
