### ISSUE TITLE
bug in coupling adjustment

### ISSUE THREAD

**Issue by ac0ax** [df8oe/mchf-github#1378]
I see in the coupling adjustment a setting for 23cm and no 10m setting.

**Comment by db4ple** [comment]
What do you see AFTER the 15m Coupling entry?

**Comment by sp9bsl** [comment]
Hi, 
yes, you probably switched on the RF/VHF/UHF mod (pressed the +40 or +60db on meter when in menu). There is no 10m coupling adjustment, please check the current menu structure [here](https://github.com/df8oe/UHSDR/blob/active-devel/mchf-eclipse/support/ui/menu/ui_menu_structure_mdtable.md)

This functionality is documented in wiki, just below the touchscreen description table.
73 Slawek

**Comment by df8oe** [comment]
There is no 10m coupling adjust. The value for 15m is used. There are some other coupling adjusts missing, too. In this case the values of the nearby bands are used.
