### ISSUE TITLE
2.7.75 2018-01-30 18:04  454K  Version not loading

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1381]
I think I mite be up against the memory problem on this version. Got an error about not enough memory.

MCU_512K 2018-01-30 18:04  268K  Version loads with calibrating screen But in going into the menus to adjust DEBUG menus, again the adjustments do not seem to effect anything. Still high noise. Setting to release to DEVEL1/ or 2 Does not change the noise floor.

I went back to the code to see what I am doing wrong But all I got was the code for the larger BIN.

Regards RIchard

**Comment by df8oe** [comment]
- If you do have an (outdated) 512KB MCU you _m*u*s*t_ use 512KB version of firmware.
- If you have not calibrated touchscreeen before _and have not saved the calibration_ you will be asked again on every start.
- I cannot confirm your report about NR. It is working very fine. Stupid question: do you have activated NR with press on G2? Without activation you can turn in debug menu everything without any effect...

vy 73
Andreas
