### ISSUE TITLE
on v D2.7.74

### ISSUE THREAD

**Issue by G4IOG** [df8oe/mchf-github#1382]
Since I moved to this version, on v7 mchf I have big freq readout characters, and when I look at dual scope/waterfall, the scope is so small it is unuseable. Any one else have this same problem?
The scope mode or waterfall mode by themselves work fine. This has only occured on dual mode since large frequency digits

**Comment by df8oe** [comment]
You must adjust percentage of waterfall / scope. And yes: big frequency digits are a new feeature.

**Comment by G4IOG** [comment]
Go on then Andreas, give me a clue where to find the adjustment. The only percent I see is the one for the filter bandwidth background brightness. Thanks, I see a lot of new programming in the code now. Its working really well.

**Comment by sp9bsl** [comment]
Hi,
the very first thing you must do is touchscreen calibration. Then simply press and hold the frequency ruler to adjust its location. After this, save your setting with MENU long press.
You can read more here: #1310, and ofcourse by reading the wiki in the part where you find the touchscreen description table.

73
Slawek

**Comment by G4IOG** [comment]
screen calibration is fine. I did it again just now. I did not know there was a drag and drop option on the bar. I found it now and it is back to how I like it. Many thanks for your help Slawek. Super work.
73, Bob
