### ISSUE TITLE
Mic Pinouts?

### ISSUE THREAD

**Issue by ei2gyb** [df8oe/mchf-github#1391]
Hi All, 

Does anyone know where I can get the pin outs for the mic plug?
i'm looking to use a PC headset or something similar with the radio but i have not found any pin outs for the mic.

Any help would be great

Steve EI2GYB

**Comment by sp9bsl** [comment]
Hi,
[here](https://ea3hzz.gitbooks.io/mchf-manual/content/en/installation/microphoneptt-j3-ui-.html)
73, Slawek

**Comment by ei2gyb** [comment]
Thats fantastic  thanks for the info.
Steve - EI2GYB
