### ISSUE TITLE
mcHF 2.7.83 (512K small build) unable to remove FW from the mode selection

### ISSUE THREAD

**Issue by Harry-ei6ku** [df8oe/mchf-github#1398]
In FW 2.7.83 (512K - small build) Im now unable to remove FW from the mode selection using the menu "FM off option", this worked previously.

73
MM0MHP
Harry

**Comment by db4ple** [comment]
Hi,
please explain:
The menu item cannot be switched off 
OR
The menu item is switched off but FM still appears in list.

If the second choice is yours:

Make sure to NOT to be in the 10m band when testing. Here special rules apply and FM may appear even with FM switched off.

**Comment by Harry-ei6ku** [comment]
Thanks - yes I was testing in the 10 meter band, sorry I hadn't relaised it had special rules,
all good now.

73
H
