### ISSUE TITLE
Digital mode touch-problem.

### ISSUE THREAD

**Issue by lb5va** [df8oe/mchf-github#1401]
Why does it not respond when I press the touch field for Digital mode.
I may press 3-10 time before it changes the mode. It beeps every time. Touch-panel IS calibrated.
Is this just the way it is?  (Tried 2.7.83 today.)

**Comment by sp9bsl** [comment]
Hi,
definitely no. Make a simple test: powerup your rig with any key except touchscreen pressed - you will enter the key test screen. In this mode you should be able to draw pixels by pressing the screen. You should see precise line when you drag across the screen. Please check the area where the DIGITAL item is placed for accuracy. I suspect bad quality of your touchscreen.

73, Slawek

**Comment by lb5va** [comment]
Thanks for this tips. I did and it had some glitches. I did new calibration, and it became much better.
Also line-drawing became more consistent lines. 
Does not respond every time but almost now.  Thanks again.

**Comment by lb5va** [comment]
Is it wise to do new touch calibration after every fw-upgrade?  It was some versions back I did it last. Therefor this problem I think.

**Comment by sp9bsl** [comment]
Hi,
we did not change anything with this since end of December. You do not need to recalibrate the touchscreen unless you use back to deafult settings, because only this will desroy all touchscreen calibration data.

73, Slawek
