### ISSUE TITLE
Scrolling text message sometimes prints a character on  the next line

### ISSUE THREAD

**Issue by phaethon** [df8oe/mchf-github#1406]
CW, PSK, RTTY decoding (i.e. UiDriver_TextMsgPutChar function) sometimes instead of scrolling a message prints a character on the next line. The character stays even if message cleared until overwritten by another character if it happens.

**Comment by sp9bsl** [comment]
Hi Eriks,
yes, we know this annoying problem:) Will try to fix it in the near future ;-)

73, Slawek

**Comment by db4ple** [comment]
I am very sure this is a race condition.

**Comment by sp9bsl** [comment]
Yes, I think so, because there is nothing from "logical" check of this simple code.

**Comment by sp9bsl** [comment]
I think, found it.

**Comment by phaethon** [comment]
Please share the insights.

**Comment by sp9bsl** [comment]
You will laugh... #1415

**Comment by sp9bsl** [comment]
Works for 15 min without extra characters on CW.

**Comment by phaethon** [comment]
If it is really the solution then I am not understanding something. TextMsg_buffer_max is ui_txt_msg_buffer_size - 1 already.

**Comment by sp9bsl** [comment]
Yes, you're right. It is defined separatelly but -1 like you said. So, we have the buffer overwrite for last"/0" somewhere.

**Comment by sp9bsl** [comment]
Try something like [that](https://github.com/sp9bsl/UHSDR/commit/968e41569b521420446b4a4a8ca0d24c70ff4cd7). It also works for me...

**Comment by df8oe** [comment]
What of both solutions should be merged?

**Comment by sp9bsl** [comment]
Not sure for 100% it needs testing. I closed my yesterdays too early pull for this reason. Will sit at this today evening.

**Comment by db4ple** [comment]
To be honest, I like none of these as these fight the symptoms not the cause. Some piece of code is overwriting the end of the data structure (which should read '\0') in some situations it seems.

**Comment by sp9bsl** [comment]
yes - I think the same. Have to debug it more "deeply".

**Comment by sp9bsl** [comment]
Hi,
I want to inform you that I still working on it. The good thing is, I can catch every occurence and debug it, the bad is that it is very rare and time consuming. Still analyzing the cause. One thing seems found: it is caused by "\n" somewhere...

**Comment by db4ple** [comment]
Good finding, "\n". I'll have a look at it.

**Comment by sp9bsl** [comment]
Hi,
I changed text print function a bit (#1428). Tested it for two days and didn't notice this problem again. Available starting with 2.7.95.

73 
Slawek

**Comment by sp9bsl** [comment]
Is the last change resolved the problem? Please report.

**Comment by phaethon** [comment]
After limited testing - issue seems to be gone.
