### ISSUE TITLE
2.8.0 VS 2.9.0 report

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1436]
Version 2.8.0  has great audio noise reduction just as soon as it is loaded. Version 2.9.0 is noisier as soon as it is loaded and it is harder to hear weaker stations. Was unable to adjust it so that is was like version 2.8.0. Both was with the DSP A-NOTCH filter set to on. 

Went back to version 2.8.0. 

regards Richard WM0I

**Comment by df8oe** [comment]
I want to tell you honestly that the only difference between these two versions is the possibility to swap the encoder directions for menu. No other changings. So it is **absolutely impossible** what you describe.

For not filling GitHub issues up please write test reports to our discussion group as mentioned in issue 1383.

Thank you.
