### ISSUE TITLE
Encoders

### ISSUE THREAD

**Issue by oz8gw** [df8oe/mchf-github#144]
A lot of times when I turn one of the encoders (for example change the frequency) the radio does not change the frequency on the first step. Sometimes even change one step to the wrong side. This also happens in the other three encoders. Therefore I guess it is a software and not an encoder issue.
Vy 73 de OZ8GW, Leif

**Comment by db4ple** [comment]
Yes. Most likely an interaction between software and hardware. DL2FW is looking into this I think, as part of his dynamic encoder "code tuning".

**Comment by db4ple** [comment]
DL2FW committed his code today, and it seems to work much better than the code before. Did not notice "reverse" steps anymore.

**Comment by oz8gw** [comment]
Hi again.
Nice to hear.
Now I look forward to see the next uddate with the improvements.
Vy 73 de OZ8GW, Leif.
