### ISSUE TITLE
Wishlist enhancement for 512kb/192kb small build. 

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1461]
This is not a report.

Now that you have reduced the firm size down to 257kb can you implement a external USB bluetooth adaptor for the audio to be exported to a laptop/smart phone/tablet/PC. Just the audio out not audio input.  This would help us hams to use software such as SSTV .

Best regards
RIchard **WM0I**

**Comment by df8oe** [comment]
Hi Rich,

this wish means to implement a full bluetooth stack and the neccessary USB handling, and there are different USB BT devices out in the wilderness which all need different USB handling. I by myself will not do this. But if anyone wants to do it: go!

BTW:
Main firmware development will focus on 1MB devices - not on outdated 512KB versions. Possibly this will fit on 1MB devices additionally. But it is huge work.
