### ISSUE TITLE
Question about WHITE color bar changing to RED color bar with strong S meter indication. 

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1462]
## Your Issue Data goes here:
2.9.8
3.4.6 and up
Your firmware version:
Your bootloader version: 

### Hardware 
 * UI Board: mcHF clone 
 * RF Board: mcHF clone

### Describe the issue:
S meter changes from white to red with strong audio. (see pictures).

No settings change, this happens a startup. 
Audio set at 22  AGC set at 30.

![red barn](https://user-images.githubusercontent.com/33020824/36630135-3ab41ad6-1927-11e8-97bb-c26de488e6a6.jpg)
![white bar](https://user-images.githubusercontent.com/33020824/36630136-3ac8d43a-1927-11e8-8b72-d28ab59e92ca.jpg)

**Comment by df8oe** [comment]
Clint's very old manual tells us: "red is overload situation of A/D converter,.

My addition: mostly due to spikes on the I/Q-audio signals.
