### ISSUE TITLE
Version S2.9.10 hangs/locks up. 

### ISSUE THREAD

**Issue by lb5va** [df8oe/mchf-github#1466]
Happens when mode is changed to SAM and if DSP is activated. Tested on my clone, 512MB. 
Screen and all freezes and sound also gets funny.  Spectrum form in 2x looks a little strange. Lower levels on right side. 
Back to S2.9.9 all is ok.  Tried it all two times, included new download. 
Stig

**Comment by db4ple** [comment]
Hi Sti,
please fill out the relevant details in form in #1465 and close this duplicate issue. Thank you.

**Comment by jelafond** [comment]
I also experienced this as well on Version 6 Original Kit. The MCU has been changed to the 429.
Works well under S2.9.9 There was no IO at the time of lockup. Press DSP twice and locks every time.
Yes - its timing me thinks.  Some optimizing will solve. 
john  K0VFR

**Comment by df8oe** [comment]
duplicate #1465 - closed.
