### ISSUE TITLE
Confused by new Firmware file size of 257K going in with 448K FW-MCHF.OLD.

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1488]
IF only 257K going in what is coming out as 448K file size?

WM0I

73

**Comment by sp9bsl** [comment]
`448 x 1024=458752 Code size for application (mcHF)`
`64 x 1024=65536 For bootloader`
`458752+65536=524288= 512kB of flash`

I think you asked for flash dump to pendrive. This is all application memory dumped as a file.

73 Slawek

**Comment by db4ple** [comment]
Hi,
explained here as well: https://github.com/df8oe/UHSDR/blob/active-devel/mchf-eclipse/useful_manuals/bootloader_doc.md#flashing-new-firmware-and-saving-old-firmware

**Comment by df8oe** [comment]
This behaviour never changed since the apperance of the first USB key bootloader in 2015. It is not easily possible to detect the "end of the firmware code" when it is flashed so when saing old firmware the complete possible size is saved.
