### ISSUE TITLE
Slowing down the meter of power from the FW 2.9.8

### ISSUE THREAD

**Issue by EA3BDD** [df8oe/mchf-github#1492]
# Slowing down the meter of power from the FW 2.9.8
Please fill out the appropriate values.  Remove inapproriate/irrelevant values, but be prepare to provide more data. This template contains the most often asked questions.
We may adjust the template over time.

Please give as much information as necessary. At the same time, try to be concise. If you want to report something else than a defect, consider using a forum first. If you want report anything else but a defect remove the template if it does not make sense for your issue. Thank you!

## Your Issue Data goes here:

Your firmware version: 2.9.22
Your bootloader version: 4.0.0

### Hardware 
 * UI Board: mcHF 0.6 
 * RF Board: mcHF 0.6

### Describe the issue:

Hi all.
Why from the fw ver: 2.9.8,  the reading of the power  in the instrument ( s-meter ), has been slowed down and the S-meter does not mark correctly, slow, not exactly values...
The power output, it´s OK,  and with TUNE the power marks well and output it´s correct.
The fw 2.9.7, works correctly.
Thank´s
Josep

### Your relevant settings
Hint: most of the information can be seen on a screenshot of the main display.

You have audio related problems:
 * DEMODULATION MODE: All
 * Filter:  2K7 LPF
 * Noise blanker setting: 0
 * Noise reduction: ON/OFF

You have display (also fill if audio problem) related problems:
 * Display resolution: 320x240  
 * Display connected via: Parallel / SPI
 * Touchscreen: Yes 
 * Magnify: 1x  
 * Spectrum:  Scope 
 
Other settings you consider as relevant:

 * ...

**Comment by db4ple** [comment]
Hi Josep,

indeed we moved the TXMeter update around a bit which should result in limiting the update rate to no more than 25 times per second, which should be plenty in theory.
We'll have a look at it.

**Comment by EA3BDD** [comment]
Hi.
Thank´s
It´s important for me in order to teaching the Radioclub novices 
Josep

**Comment by EA3BDD** [comment]
Hi. 
Excellently solved. My recognitions for his work.
We are to his disposition for what he needs.
EA3BDD  and 3BFE, 3CW,3 FDY, 3CC, 3OA, 3BDQ

**Comment by EA3BDD** [comment]
Hi.
Thank´ssssss
Josep
