### ISSUE TITLE
Can't get into default settings

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1498]
Your firmware version: latest
Your bootloader version: latest

### Hardware 
 * UI Board: mcHF 7
 * RF Board: mcHF 7

### Describe the issue:

I can't seem to load the default values. When I press F1 F3 F5 it just goes to the blue test screen.

Also when I touch  he screen it beeps but doesn't do anything. I have performed the touchscreen calibration .

It will not let me into the touchscreen calibration again, just bluescreen telling me that I am touching the screen.

Also in Blue test screen the touchscreen value do change.

Any ideas??

**Comment by ase-2017stud** [comment]
Hi,
post the values for Keys Initial & Keys Current shown when you press nothing. Or simply attach a screenshot to your issue. 

BTW, the word "latest" is not a good reference to version 2.9.25, so please use the numbers. If someone looks at this a month or so later, latest is not the same anymore. Thank you!

**Comment by df8oe** [comment]
Refactored button test impacts loading of default settings and touchscreen calibration...

**Comment by db4ple** [comment]
Hi Andreas,
can you reproduce the problem?

73
Danilo

**Comment by WD8BXS** [comment]
Andreas, does this meant there is an issue?? I saw that statement on the last daily build. Don't understand it, but I was it hihi

**Comment by WD8BXS** [comment]
Here is the pic you requested

**Comment by df8oe** [comment]
Yes. I can reproduce.

**Comment by df8oe** [comment]
fixed now.
