### ISSUE TITLE
possible bigger font cw decoder text

### ISSUE THREAD

**Issue by pe1jzq** [df8oe/mchf-github#1504]
Your firmware version:2.9.1
Your bootloader version: 4.0.0

### Hardware 
 * UI Board: mcHF 0.4
 * RF Board: mcHF 0.4
### Describe the issue:

Hi, 

I am learning cw with cw-ops and use the mchf as a keyer. When i try to read the text I have sent it is a litte small. Is it possible to haven a bigger font?

73's
Hans-Willem
pa0hw ex pe1jzq

Place tell us what does not work and how others can reproduce the issue (list related settings, steps to do, etc.):

### Your relevant settings
Hint: most of the information can be seen on a screenshot of the main display.

You have audio related problems:
 * DEMODULATION MODE: cw
 * Filter:  400-700
 * Noise blanker setting: 0
 * Noise reduction: OFF

You have display (also fill if audio problem) related problems:
 * Display resolution: 320x240 
 * Display connected via: Parallel 
 * Touchscreen: Yes
 * Magnify: 4x
 * Spectrum: Waterfall
 
Other settings you consider as relevant:

 * ...

**Comment by df8oe** [comment]
The only possibility to get a free line on LCD for text output purposes was to choose a very small font. Bigger fonts do not fit.

vy 73
Andreas

**Comment by df8oe** [comment]
If you are satisfied with the informations: please close this issue. Thank you!
