### ISSUE TITLE
A couple of questions.

### ISSUE THREAD

**Issue by Tibet4690** [df8oe/mchf-github#1505]
Haven't had the time to play with my clone recently, but have a couple of question.

I have a clone with 512kb of memory, looks like the FW has split since I last updated. I went with the 512kb version of the latest firmware and updated to the latest bootloader... everything seems to be working. Is there anything should be keeping in mind when updating with my limited memory? (other than just selecting the firmware found under the 512kb subfolder)

Second, after updating I received a warning to calibrate my touchscreen... I calibrated it, but truthfully I don't use it. Is it possible to just disable to avoid receiving a warning / delaying my boot after updating in the future?

Thanks

**Comment by sp9bsl** [comment]
Hi,
if you calibrate the touchscreen once and then save to eeprom, it will not bother you again. The other option is to disable the touchscreen controller on LCD by hardware (do not recommend it anyway).

73
Slawek

**Comment by df8oe** [comment]
Difference in firmware version 512KB and "standard" is that we must cut some features at small builds because they do not fit to outdated MCU. Actually this is only digital voice mode "freeDV" but be sure in future there must be cut off more new features so that growing firmware fits to small MCU.

**Comment by Tibet4690** [comment]
Thanks for the replies!

**Comment by df8oe** [comment]
If you are satisfied with the informations: please close this issue. Thank you!

**Comment by Tibet4690** [comment]
Sorry for the delay, closed.
