### ISSUE TITLE
No power out from 17m to 10m bands

### ISSUE THREAD

**Issue by iw5bms** [df8oe/mchf-github#1513]
# UHSDR Firmare Defect Issue (Bug) Template 1.0

Please fill out the appropriate values.  Remove inapproriate/irrelevant values, but be prepare to provide more data. This template contains the most often asked questions.
We may adjust the template over time.

Please give as much information as necessary. At the same time, try to be concise. If you want to report something else than a defect, consider using a forum first. If you want report anything else but a defect remove the template if it does not make sense for your issue. Thank you!

## Your Issue Data goes here:

Your firmware version: D2.5.106
Your bootloader version: M0NKA 0.0.0.14

### Hardware 
 * UI Board: mcHF 0.7
 * RF Board: mcHF 0.7
 * Logic Board: mcHF 0.7

### Describe the issue:
Full power and 5W power adjustment work well from 160m to 20m only.
From 17m to 10m bands I'm able to change setting values during Tuning but no RF out is present.
Latch relays of lowpass filter are ok.

Thank you, regards
Maurizio iw5bms

Place tell us what does not work and how others can reproduce the issue (list related settings, steps to do, etc.):

### Your relevant settings
Hint: most of the information can be seen on a screenshot of the main display.

You have audio related problems:
 * DEMODULATION MODE: LSB/...
 * Filter:  2K7 LPF
 * Noise blanker setting: 0
 * Noise reduction: ON/OFF

You have display (also fill if audio problem) related problems:
 * Display resolution: 320x240 / 480x320
 * Display connected via: Parallel / SPI
 * Touchscreen: Yes/No
 * Magnify: 1x / 32x
 * Spectrum: Waterfall/Scope/Dual
 
Other settings you consider as relevant:
Tune power level :5W
Reduce power on Low band :OFF
Reduce power on High band :OFF 
 * ...

**Comment by db4ple** [comment]
Hi,
please update to newest firmware. If problem persists, it is almost certainly a hardware issue since the affected bands are exactly one of the four lpf / bpf groups. Check continuity through the LPF and BPF (btw, BPF does not use the relays but analog switching ICs).

**Comment by iw5bms** [comment]
Hi Danilo, I solved the problem just resoldering U1 pins. Thank's a lot for your suggestion.
73 Maurizio

**Comment by db4ple** [comment]
Thanks Maurizio,
please close the issue now.

73
Danilo
