### ISSUE TITLE
Firmware release Documentation

### ISSUE THREAD

**Issue by Groc-1** [df8oe/mchf-github#1515]
In April 2018 there were 10 releases in the archive. But no text file to state what was changed with each release.
Is it possible in the future to include a "changes" file with the archived .bin..

**Comment by df8oe** [comment]
No - we won't do that. Reason: its twice work.

If there are functional changes or added features you will find informations in the commit comments. If it is "deep in the code" its not interesting most of the users. But you can find the changes by digging into the commits.

https://github.com/df8oe/UHSDR/commits/active-devel

**Comment by Groc-1** [comment]
Thank you for the reply..  closing item.
