### ISSUE TITLE
SWR don´t mark with the lasts FW

### ISSUE THREAD

**Issue by EA3BDD** [df8oe/mchf-github#1520]
# UHSDR Firmare Defect Issue (Bug) Template 1.0

Please fill out the appropriate values.  Remove inapproriate/irrelevant values, but be prepare to provide more data. This template contains the most often asked questions.
We may adjust the template over time.

Please give as much information as necessary. At the same time, try to be concise. If you want to report something else than a defect, consider using a forum first. If you want report anything else but a defect remove the template if it does not make sense for your issue. Thank you!

## Your Issue Data goes here:

Your firmware version:2.9.33
Your bootloader version: 4.0.0

### Hardware 
 * UI Board: mcHF 0.6
 * RF Board: mcHF 0.6

### Describe the issue:

Hi.
With the lasts 3 or 4 FW, the SWR don´t marks !
Tnk´s
Josep
EA3BDD

### Your relevant settings
Hint: most of the information can be seen on a screenshot of the main display.

You have audio related problems:  No more problems !!
 * DEMODULATION MODE: USB
 * Filter:  2K7 LPF
 * Noise blanker setting: 0
 * Noise reduction:  OFF

You have display (also fill if audio problem) related problems:
 * Display resolution: 320x240 / 480x320
 * Display connected via:   SPI
 * Touchscreen: Yes 
 * Magnify: 2x
 * Spectrum:  Dual
 
Other settings you consider as relevant:   No more problems

**Comment by db4ple** [comment]
Hi Josep, why did you close the issue? Is it gone?
TNX
Danilo

**Comment by EA3BDD** [comment]
Hi Danilo.4 mcHF v 0.6 with the same problem.After investigations-> SOLVED ! No FW cause.Thk's and soorry !Josep



Enviado desde mi smartphone Samsung Galaxy.
-------- Mensaje original --------De: db4ple <notifications@github.com> Fecha: 12/5/18  23:23  (GMT+01:00) Para: df8oe/UHSDR <UHSDR@noreply.github.com> Cc: EA3BDD <ea3bdd@gmail.com>, State change <state_change@noreply.github.com> Asunto: Re: [df8oe/UHSDR] SWR don´t mark with the lasts FW (#1520) 
Hi Josep, why did you close the issue? Is it gone?

TNX

Danilo

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/df8oe/UHSDR","title":"df8oe/UHSDR","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/df8oe/UHSDR"}},"updates":{"snippets":[{"icon":"PERSON","message":"@db4ple in #1520: Hi Josep, why did you close the issue? Is it gone?\r\nTNX\r\nDanilo \r\n"}],"action":{"name":"View Issue","url":"https://github.com/df8oe/UHSDR/issues/1520#issuecomment-388583964"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [df8oe/UHSDR] SWR don´t mark with the lasts FW (#1520)","sections":[{"text":"","activityTitle":"**db4ple**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@db4ple","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"df8oe/UHSDR\",\"issueId\":1520,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"targets":[{"os":"default","uri":"https://github.com/df8oe/UHSDR/issues/1520#issuecomment-388583964"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":334632875}"}],"themeColor":"26292E"}
