### ISSUE TITLE
Si5351a Question

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1521]
Does this replace the SI530 ??  
Is it a direct replacement ?
What are the advantages ?

### Hardware 
 * UI Board: mcHF 0.6  or .7
 * RF Board: mcHF 0.6 or .7

Thanks,
 Chuck WD8BXS

**Comment by df8oe** [comment]
It has nothing to do with mcHF. It is used in OVI40. Sorry - entries are not made "unvisible" if mcHF is in use.

vy 73
Andreas

**Comment by WD8BXS** [comment]
OK, Thanks
