### ISSUE TITLE
NR menu question:

### ISSUE THREAD

**Issue by Groc-1** [df8oe/mchf-github#1529]
Under the configuration menu there used to be an option "DSP NR Post-AGC" to Perform the DSP LMS noise reduction BEFORE or AFTER the AGC.
Wouldn't performing the NR before the AGC stop AGC pumping on noise pulses (e.g. lightning crashes from distant storms)?
Where did it go?? If it's been dropped, can it be reinstated?
Thank you.. 

Firmware version: 2.9.28
Bootloader version: 4.0.0

### Hardware 
 * UI Board: mcHF 0.6
 * RF Board: mcHF 0.6

**Comment by df8oe** [comment]
We do no longer have DSP LMS NR (and therefore this item is gone). It's a complete new spectral NR since about half a year.

vy 73
Andreas

**Comment by Groc-1** [comment]
Andreas, 
Thank you...
Another thing for this old dog to read about..  HI HI

73 de Dave
