### ISSUE TITLE
No IQ Adjustment

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1539]
firmware version: 2.9.34
 bootloader version: 4.0

### Hardware 
 * UI Board: mcHF 6.x
 * RF Board: mcHF 6.x

### Describe the issue:

New build, but have NO IQ adjustment.

Replaced U11 (Potato) and U19,
Re-flowed entire area.

Still no IQ adjustment , changing values has no effect.

What area do I need to look at on the MCHF RF board??

Any ideas ??? Please!

Thanks,
 Chuck
WD8BXS

**Comment by df8oe** [comment]
Not Firmware related - in principle "wrong place". You can get answers at Yahoo group or discussion group of https://www.amateurfunk-sulingen.de/forum/

One last answer for not-firmware related questions now:
Look at 90° LO inputs of mixer, 0,90,180,270 AF inputs of mixer, bad soldering at middle of output transformer or bad mixer IC.

Good luck!

**Comment by WD8BXS** [comment]
Thanks
