### ISSUE TITLE
PSK/RTTY Functionality

### ISSUE THREAD

**Issue by Jmelz** [df8oe/mchf-github#1540]
How well is PSK / RTTY working? That's vague for a reason - 

I attempted to use PSK31 last night. I thought I had everything set per the wiki, but could not get a decode. When I pressed F1 on a USB keyboard, typed, and then pressed F2, I got the impression that either my text was not being buffered, or worse, maybe not going out. I did not test with another radio yet. I wanted to ask, what indication does a user have that the text is being sent completely? If I type really fast, and hit F2 when done, the radio immediately goes to RX. Maybe the text was cut off because of this?

I'll do more testing, but just curious about this... I believe I have the correct filters in use (from other posts it looks clear), but I wonder if the radio should not be doing better at decoding... CW works very well by contrast. RTTY - I was able to decode a single station, pretty easily, but couldn't decode another one with similar strength and bandwidth (45). I'm using the June 26th firmware for 512 devices.

**Comment by Jmelz** [comment]
I made a video showing my experience. RTTY works pretty well, maybe 95% of the time I get good decoding, especially with 45...50 not so much... and PSK31 - not so much. Also transmit seems not to work very well for me... maybe I'm doing something wrong...

https://www.youtube.com/watch?v=3K09HxpeRmk

**Comment by df8oe** [comment]
PSK works well, too. But there is no mighty "AFC" function which auto-calibrates frequencies as proper as they are needed for good decoding. Such a routine eats much horse power and RAM - both not available at mcHF.... So you have to fine-tune RX frequency in 1 Hz steps to get best decoding result. It's a bit tricky - but there is no other way.

**Comment by Jmelz** [comment]
I must be awful at using it then.  I can't seem to get it working consistently. On PC, using fldigi, I have no problems decoding, and usually don't use afc. I'm using increments of 1 on the mchf, but still poor decode. Far worse than rtty or cw (cw works perfectly actually, very very good).

I haven't seen many YouTube vids about this functionality, so I made my own. 

Am I doing something wrong? I have been using this page as a tutorial:

https://github.com/df8oe/UHSDR/wiki/Digimodes

'switch demodulation mode to PSK-U or PSK-L depending on band and/or your personal preference' - to my knowledge, all psk is USB, so should always be psk-u...

'Long press TXRX switches from/to buffered/unbuffered mode. In buffered mode it returns to rx after finishing the message unless you keep typing. In unbuffered switch to rx manually.' - I could see no such effect when holding external keyboard's f1 for any length of time.

Edit: I realize now that txrx means the hidden menu item mapped to mchf's  f5. Now I see how it works. However, the decoded gibberish interferes with the buffer display:

*******Qsl*****e*er****ng*i* f**e*****

**Comment by df8oe** [comment]
We are on the edge for F4 MCU. I do not think we can improve anything else (regarding "autoadjustment" for PSK). And this is the point why it does not work like PC applications...

Regarding "F1": this is not the keyboard but the mcHF button layout we are talking about.

**Comment by phaethon** [comment]
@Jmelz Can you describe what issues you have with PSK31 transmit? Receiving part could be improved, but transmit should work well (also, compared to PC).

**Comment by Jmelz** [comment]
Last time I messed with it, as I was typing, decided gibberish text interfered with the text I typed.

**Comment by phaethon** [comment]
This description does not help much. Do you have repeatable issues with transmit that you can demonstrate? E.g. record with another radio nearby.

**Comment by Jmelz** [comment]
I'm not sure how to clarify, but it's like this...

when I switch to psk31 mode, I being typing, and the little tiny space where you expect the text you are typing to be displayed - well, it shows not only my text I'm typing, but received text as well. So, a sentence might look like this:

I type "CQ CQ CQ de W4CKA" and see on the MCHF:

C.3.#>#$>Q CQ C2##ILJ...de3l3.W.ER4CK.3ALA

Does that help?

I'd given up on using this feature because if receive doesn't work reliably, I see no reason to transmit either.

**Comment by phaethon** [comment]
Well, if you type slowly and don't use buffered input, then it just decodes rx in between characters, which is normal. Please, read wiki on buffered vs unbuffered sending.

**Comment by Jmelz** [comment]
My mistake on the wiki. However, this is not very intuitive. Again, if it doesn't work very well with decode, I'm not sure I'll ever use it again anyway. I appreciate your efforts, but this feature does not yet seem mature, or that there is much interest in maturing it.


I do appreciate everyone's efforts with the firmware, it runs great. So many features and the radio works so well, that I'm pretty happy with the functionality I get out of it. I was just hoping to not have to bring a PC when doing QRP in the field for psk31. I guess it's not a huge deal anyway, as most people seem to use ft8 now and not psk31.

**Comment by df8oe** [comment]
It works well if you tune in 1 Hz steps around the signal and find the correct frequency. This is not easy. But remeber: you do not have gigabytes of RAM and endless horse power.This is all done simultaneously to all RX stuff and so it is very good for a standalone solution.

Sadly most have switched to FT8 and that mode is definitely not to realize in RX for mcHF... So in my eyes FT8 is not a "portable working mode" at all. You will need a PC or tablet.

**Comment by Jmelz** [comment]
With a magnetic loop and hours of time, I could only get it to decode maybe 1 out of 20 times. I was using 1 HZ steps. I agree about FT8. But PSK31 on the MCHF is an exercise in frustration.

**Comment by df8oe** [comment]
Is your question answered now? If so: please close this issue.

**Comment by Jmelz** [comment]
I guess it is.
