### ISSUE TITLE
QVI40 70 watt SDR -where to buy

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1543]
Where can buy it?
RIchard WM0I

**Comment by df8oe** [comment]
Actually only UI-PCB is available. RF-PCBs are in alpha state and will follow soon. You will find informations on the project sides https://www.amateurfunk-sulingen.de/ovi40-sdr-en/#start and of course in the OVI40 section of our discussion group https://www.amateurfunk-sulingen.de/forum/index.php?board=18

vy 73
Andreas

**Comment by df8oe** [comment]
Question is off topic to UHSDR so I close it
