### ISSUE TITLE
[solved] Spurious receive firmware solution? YES! Start with clean (default) settings!

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1546]
Through much experimentation, I have just figured out that the spurious receive (12khz) stated with firmware 2.9.16

I loaded 2.9.15 and the receive is fine.

There is a firware issue somewhere.

73,
 Chuck

**Comment by df8oe** [comment]
I do not think so. I am runing all firmwares up to the newest on many different radios (mcHF and OVI40) and I cannot confirm the issue. I think your configuration is scrambled...

You can test it (and help us to make firmware more tough against malsettings):
First install firmware 2.9.43
Second please make a backup of your current settings via USB to PC. If it IS a configuration problem you can send us this file for bug hunting.
Third start mcHF with default settings and test again if the issue persists. I think not...

73
Andreas

**Comment by db4ple** [comment]
Hi Chuck,
thanks for the testing!

Like Andreas I still not understand why only you and only now have this issue. What is the differentiator between you and the rest of the users so that you have this issue and can reproduce it and others don't. 

We really should look at the  configuration as part of the problem.  For that we need the configuration data (see above and my forum post).

Now looking at the change between 2.9.15 and 2.9.16: It is not much, actually we only increased the size of a datastructure (technically two of them, but nevermind) and some code which initializes this data with zeros when the AGC startup code runs (e.g. when changing modes). 

I cannot see how this code directly could cause the mentioned issue. But still, it could have unwanted side effects especially since we increase the use of RAM (we add 96*12 ~ 1k RAM). Normally this if this is the root cause, other users should also see the issue since this is code used by all mcHF users who use the AGC. But now let us verify that this is not an issue. Please use a "mchf_small" build (it uses much less RAM in addition to using less flash space) and see if the issue is still there.

Please also report RAM size of the device(s) showing the issue.

**Comment by WD8BXS** [comment]
Unclear of how to do the backup to pc. Is this a new feature?

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 22, 2018 at 2:49 AM, DF8OE<notifications@github.com> wrote:   
I do not think so. I am runing all firmwares up to the newest on many different radios (mcHF and OVI40) and I cannot confirm the issue. I think your configuration is scrambled...

You can test it (and help us to make firmware more tough against malsettings):
First install firmware 2.9.43
Second please make a backup of your current settings via USB to PC. If it IS a configuration problem you can send us this file for bug hunting.
Third start mcHF with default settings and test again if the issue persists. I think not...

73
Andreas

**Comment by df8oe** [comment]
Please do not quote old texts on GitHub. It is confusing..

Backup feature is many weeks / some months old... Please follow Danilos link from the answer on our amateurfunk-sulingen forum to your question.

vy 73
Andreas

**Comment by WD8BXS** [comment]
OK, I reset the EEprom, I set to defaults, I loaded 2.9.43, and sll seems to be working OK now!!!

Both radios are OK right now.
I will do calibration on both and see what happens.

Thanks, so Far!

73,
 Chuck

**Comment by WD8BXS** [comment]
All seems OK now that I have cleared the EEprom and reset to defaults, loaded new firmware 2.9.43,  and calibrated.
Very confusing, but there must have been something that corrupted the info. Maybe I should do the EEprom reset before doing anything the next time!!

Thanks for putting up with me.

Very 73,
 Chuck WD8BXS

**Comment by df8oe** [comment]
Please can you attach the old (scrambled) setting zipped to your next reply? We have programmed possibility to store configurations exactly _because we need informations to hunt such "strange things"_. Without such a scrambeld configuration there is **no chance** to step on.

There is a routine in firmware which tests each setting at starting up. But it seems there are some possibilities for scrambled values to pass this routine. I would not call this "a bug" - but you see there is something that can be improved. But only with your help and contribution...

If we do not get this contribution you possibly must again and again reset your configuration and setup every setting new ::)

vy 73
Andreas

**Comment by WD8BXS** [comment]
Hi Andreas,
I was not able to get the computer to recognize and make a backup of the software. (Sorry)
It kept telling me that it did not see the radio.
Maybe I was doing it wrong as the directions were not that clear to me, I used the CMD prompt and had the USB in the Dfuse USB port.
I could see the device in the device manager.
I used the command ( uhsdr_tool.exe -p6 -b )

But Got the message:
Could not find a connected UHSDR with extended CT commmands (required)

So maybe I needed to set something in the radio first???


73,
Chuck

**Comment by db4ple** [comment]
Hi Chuck,
the older firmware versions do not support the backup via USB. The minimum firmware version is mentioned clearly in the title of the section and in the requirements list (first item, first sentence). 2.9.19 it would have been.

It is unfortunate that we don't have the problematic configuration, especially now knowing it was indeed the configuration. Next time then.

73
Danilo

**Comment by WD8BXS** [comment]
Thanks Andreas,
I have just tried again to do the backup, but to no avail.
Is there something I need to set in the radio to get this to work?

Thanks again,

73,
Chuck

**Comment by df8oe** [comment]
No. You just must set correct com port in the command line of the tool. I do not know where the comport of your radio is place by your M$ system.

vy 73
Andreas

**Comment by WD8BXS** [comment]
Yes, I have done that!! It shows up as Com 6. But still no go!
Computer says it can not find a UHSDR device.

Chuck

**Comment by df8oe** [comment]
Maybe there is a space missing between "b" and "6"...

command line is very exact ;)

vy 73
Andreas

**Comment by WD8BXS** [comment]
Possible.

Here is my command line:
uhsdr_tool.exe -p 6 -b -f uhsdr_config.json

Chuck

**Comment by df8oe** [comment]
This is my command line (Linux):

python uhsdr_tool.py -p 0 -b

Difference is missing filename option. Additionally I am not sure namings of COMs in Windows do start by "0" (as in Linux possible). Danilo - can you clarify?

vy 73
Andreas

**Comment by db4ple** [comment]
Hi,
in Windows you use the COMx number as shown in the device manager, so 6 would try to access COM6, fairly straight forward. Name option is optional but works, I did test that. And for Andreas: yes, a COM0 may exist.  In Windows these days device get a COMPORT number assigned and typically keep the one they get. A new, different device gets a different one.

Apart from the requirement to use 2.9.19 or newer there is none. 

Can you talk to the mcHF on COM6 using a CAT program? If not, it is a more fundamental problem. If this works, but the backup tool does not, there might be a problem with my backup tool. However, I developed it using Windows, so at least one Windows machine can run this.

73
Danilo

**Comment by WD8BXS** [comment]
Not sure, I will have to check that out,. but I have to leave that for another day, I will keep you posted.

Thanks,
 Chuck

**Comment by SM0GNS** [comment]
Hello
It seems that I have the same problem as Chuck with spurious frequencies.
For example, the RTTY-station on 10.100MHz is heard on 10.088, 10.112, 10.124 and 10.136MHz.
When running version 2.9.11 (and older) all is working fine but all newer version results in mirror frequencies.  I have done a total reset before installing a new version but without any luck.

A friend of mine has exact the same problem with his mcHF as I have. 
I have used the uhsdr-tool to do a backup of the config parameters if you want to check it.

73 
Peder, SM0GNS
