### ISSUE TITLE
Firmware 43 and 44 has caused problems and I can not go back to firmware 40. 

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1547]
# UHSDR Firmare Defect Issue (Bug) Template 1.0

Please fill out the appropriate values.  Remove inapproriate/irrelevant values, but be prepare to provide more data. This template contains the most often asked questions.
We may adjust the template over time.

Please give as much information as necessary. At the same time, try to be concise. If you want to report something else than a defect, consider using a forum first. If you want report anything else but a defect remove the template if it does not make sense for your issue. Thank you!

## Your Issue Data goes here:

Your firmware version:
2.9.44
Your bootloader version: 
4.1.2

### Hardware 

Clone RS918SSB 

### Describe the issue:

When I installed the new firmware 2.9.44 Nothing is the same as before. Notch filter gives clicking and does not kill a carrier. Audio is now very noisy.

I tried to reinstall older version of the firmware but will not load. All I get is the 2.9.44 version.
It will not let me go back.  I hope there is a fix to get back to earlier version of the firmware.
Please help! 

WM0I  RIchard

**Comment by df8oe** [comment]
Sorry - no aupport for illegal clones.

73
Andreas
