### ISSUE TITLE
emBitz compilation

### ISSUE THREAD

**Issue by m0nka** [df8oe/mchf-github#1551]
Hello,

Does the EmBitz project compile or everyone has moved to Linux ? The bootloader configuration seems to compile fine, but the normal and f7 main firmware give many errors, it looks like the linker can't find entry points for a lots of functions. 

Example:

<artificial>:(.text.PendSV_Handler+0x11b2): undefined reference to `ofdm_disassemble_modem_frame'
<artificial>:(.text.PendSV_Handler+0x11c4): undefined reference to `ofdm_get_demod_stats'
<artificial>:(.text.PendSV_Handler+0x12a6): undefined reference to `gp_deinterleave_comp'
<artificial>:(.text.PendSV_Handler+0x12b4): undefined reference to `gp_deinterleave_float'
<artificial>:(.text.PendSV_Handler+0x12e2): undefined reference to `interleaver_sync_state_machine'
<artificial>:(.text.PendSV_Handler+0x1712): undefined reference to `symbols_to_llrs'

Is it a case of simply not updated files in the project or something else ? Thank you!

**Comment by df8oe** [comment]
Hi Chris,

since H7 port has been merged embitz support is broken. Noone of the development team is working with embitz so nobody has started to work this out. Contributions are welcome. Normally updating all files should do the job.

**Comment by m0nka** [comment]
Ok, understand. Thank you.

**Comment by db4ple** [comment]
Hi,
I've started to look into the emBitz compilation configuration a few days ago. Unfortunately is emBitz not the most responsive IDE with larger project it seems, so it takes quite a while to test certain changes. But I think in the next days I'll finish these changes...

**Comment by m0nka** [comment]
I just installed it few days ago. My IDE of choice is the SW4STM32 as it has the best support from ST(all examples compile with ease) and have been using it for few months. But the project files have different structure. I have tried to convert your compilation, but not very successful, it is not just few hours work. In theory should be simple import, but it has to be on a file by file basis

**Comment by db4ple** [comment]
Hi,
if you have been using SW4STM32, the best choice is the GNU ARM Eclipse environment, see our wiki. Works and is for some of the developers the main IDE, so always kept in a working state.
Installation has a few steps but is well documented.

**Comment by db4ple** [comment]
And is somewhat close to SW4STM32, knows all the peripherals registers of the STM32. No one is actively using emBitz (since configuration was obviously broken long before I started looking at the H7 port addition) and no one reported.

**Comment by m0nka** [comment]
No, actually is totally different. Yours and theirs use .project and .cproject files but they have some customization, so the content of the files is not compatible. I am not that knowledgeable about Eclipse to do it. Anyway, thanks for commenting on that.

**Comment by df8oe** [comment]
Misunderstanding. Danilo does not mean the configurations are compatible but Eclipse provides everything what emBitz does (but is much more powerful) and is actively supported...

**Comment by sp9bsl** [comment]
Hi Chris,
Reffering to your first post, I use Windows IDE installed on three machines exactly like described in our Wiki. Worked at first try. I have own thoughts about SW4STM32, I use it in work since the first release: it works but have trouble when creating new project, the vector table is always empty... Last year in December ST acquired Atolic, which was in my opinion the best IDE few years ago, it just run out of the box. But the financial plans of Atolic company disabled it to large project few years ago, now ST changed it as free for all STMs. Maybe someday we'll support this IDE too...
Anyway, the recipe contained in our Wiki works, and to be compatible and trouble free - just use it.

**Comment by m0nka** [comment]
Thanks everyone, when i have some free time will look into this again.

73!
