### ISSUE TITLE
Where do I find freeDV mode on my Small 413 mchf?

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1559]
I looked for it all through the menu system. Did not find anything about it. 
Did you guys remove it?

How would I use external software on my computer to use freeDV?

Richard WM0I
best regards

**Comment by G3WKW** [comment]
I think this explains.  
https://github.com/df8oe/UHSDR/pull/1368

https://freedv.org/


Bob Thornton

**Comment by db4ple** [comment]
It was announced a while ago on Yahoo group and also in the German forum. I added the answer to Wiki FAQ:

https://github.com/df8oe/UHSDR/wiki/Firmware-FAQ#q-what-is-the-difference-between-the-full-and-small-mchf-firmware

 73
Danilo

**Comment by rensd** [comment]
Hi, 

maybe its good to notice that if you compile it yourself with gcc-arm-none-eabi-4_9 
The resulting binary with 410kb still fits into a "small 512k cpu" 

Regards Rens PA3AXA

**Comment by df8oe** [comment]
Normally this is not an issue. The use of a 1MB MCU was announced as "recommended" by me ~3 years ago. Of course there are some mcHFs which are >= 3 years old and do have small MCU, but all newer devices should have 1MB MCU. Chris M0NKA stepped to 1MB MCU ~ 2 years ago. Only chinese cloners do save some Cent by using a small one...

**Comment by DG9BFC** [comment]
and when you wanna use external software (freedv soft) that is the same as when using any other digital modes software .... select the mchf soundcard and you are done
