### ISSUE TITLE
Full touchscreen

### ISSUE THREAD

**Issue by w9kh** [df8oe/mchf-github#1572]
What are the thoughts/possibilities of using a touch screen like the Raspberry Pi 7" screen as a full radio interface?  It would contain the current screen information and replace all buttons and knobs on the front panel with a full touch screen panel.
If only I knew how to write code instead of simple minor modifications :(

**Comment by df8oe** [comment]
I cannot imagine touch resolution of 320x240 LCD will support that. 480x320 may, and 800x600 will 100%.
Radio must be operable intuitive and simple.

**Comment by DG9BFC** [comment]
he want to use a bigger screen so more scree area
but then you need more ram

**Comment by df8oe** [comment]
If this is answered please close issue.
