### ISSUE TITLE
 problems with updates  54 and 55

### ISSUE THREAD

**Issue by g7jiq** [df8oe/mchf-github#1597]
Just wondering if anyone has had the same problem.
Mchf  mcu 512kb
Locks up on boot screen with 2.9.54 and 2.9.55. (see attached picture)
2.9.53 works fine.
![20181029_181350](https://user-images.githubusercontent.com/7955628/47671299-16013780-dba7-11e8-8890-25fcf37cc951.jpg)

**Comment by db4ple** [comment]
Interesting. Honestly no idea what changes could make the 2.9.54/55 crash. I reviewed the changes between 2.9.53 and 2.9.55 and most of it is not related to the mcHF hardware or should have no impact.

Is the crash happening always at same time (i.e. the line "Firmware chan" is showing, possible a few more or les letters but roughly the same content).

If someone else has this issue, it is interesting to learn if this is a 512kb Flash or a larger machine.

**Comment by df8oe** [comment]
I cannot reproduce the issue, because of I praid since 2015 "use MCUs with 1MB of flash" and this is probably the cause of the issue. All of my mcHFs do have >= 1MB of flash and do work flawlessly.

If you want to be future-proof it is a *very good idea* to swap MCU with a 2MB 429/439 MCU.

**Comment by db4ple** [comment]
Hi, I tested the original downloads (both normal and small) and both work for me if not connected to an RF board. However, when connected to the RF board, both crash. Unfortunately, they don't crash if I connect an ST-Link debugger (and power it). There is something interesting happening here.

**Comment by g7jiq** [comment]
Yes it crashes at the same place on both 54 and 55,
re-flashing it back to 2.9.53 boots up fine.
And swapping upto bigger cpu would be great, but I am worried about trashing it as its a great little radio and It would be a shame to loose it.
If there is no option, I would be happy to stick to the software ver that currently works.

Thanks for looking into it..

**Comment by df8oe** [comment]
Here it is working on complete mchf radios rf and ui connected both versions small and normal. All is booting up and running like a charm. All devices do have MCUs with >= 1MB flash.

It would (again) be interesting what is the behaviour when started with default settings (F1-F3-F5). Another check can be starting in button test mode where not complete hardware is initialized.

**Comment by df8oe** [comment]
Another interesting information: what bootloaders do you use?

**Comment by db4ple** [comment]
BTW, I think my problem (crash without ST-Link, normale boot with ST-Link plugged and powered) may be entirely unrelated, since I have the phenomenon also with the 2.9.53 firmware and it crashes much later (after showing the boot screen fully).  I'll have to investigate further.

**Comment by g7jiq** [comment]
I am using bootloader 4.1.2,  
Button test works fine,

**Comment by db4ple** [comment]
Thanks. Button test works. Good to know.

**Comment by UR7FM** [comment]
Same problem with RS918.(512kB) re-flashing it back to 2.9.53 boots up fine. Bootloader also 4.1.2

**Comment by df8oe** [comment]
Please test default settings boot.

**Comment by UR7FM** [comment]
How to do it? Button test works well. With 2.9.53 starting normally

**Comment by db4ple** [comment]
Just press F1-F3-F5 during power-up and agree to  reset to default. Please note by cutting the power or pressing Band+  while pressing Power off, the reset will not be saved and you keep the existing configuration stored in non-volatile memory.

**Comment by df8oe** [comment]
...it looks like this is same mystery as "16KHz issue" which was present some weeks ago. Most of users never have had seen it, some do have it everytime... Change of some lines in FW fixed it for all - but for the ones who never have had it chaging the lines does not have any influence on function...

**Comment by UR7FM** [comment]
Just made test default settings boot.... Same problem:(

**Comment by db4ple** [comment]
OK. Thanks. Is it crashing more less exactly like shown on the screenshot of @g7jiq ? 
What I could do is to build a few test builds where we try to isolate the area of issue. That would work like this:
I build something and attach it here. Then you test it and report back what you see  (i.e. if it crashes or not).

**Comment by db4ple** [comment]
Just to report my findings: my problem with 2.9.x was related to my power supply current limit being set too low. With sufficiently high limit I can now boot the official 2.9.55 small and large without problems. 
So we are back to square one. I have an 192k MCU with 1MB flash, but that does not matter much, when flashed with a 2.9.55 small build.

**Comment by db4ple** [comment]
I have more questions: Is the TRX connected to a PC via USB when booting? If so, try without connected USB cable.

**Comment by df8oe** [comment]
Interesting idea. I have tried booting with connected USB cable to Linux and Windows PC: no luck - booting always flawlessly.

**Comment by db4ple** [comment]
This was a shot in the dark. Anyway, the only relevant difference between 2.9.53 and 2.9.55 are the change to a different debug mode detection and some (unused) menu entries which should not make a difference. The HMC1023 itself is not active and some minor changes in the  CAT protocol. No (hardware) initialization code was changed. Since it crashes during printing on the screen, it is very,very likely that the crash comes from interrupts. However, we haven't  change any code there. And it must have some "external" dependency we don't know yet, otherwise a larger group of machines should be affected, most notably our test machines.

**Comment by UR7FM** [comment]
Problem same as on the screenshot of @g7jiq
![problem](https://user-images.githubusercontent.com/35993313/47787957-1ae5f880-dd19-11e8-9586-92624da569c0.jpg)
USB cabe was disconnected from PC , I updated FW via  USB memory stick allways., bootloader via dfu mode

**Comment by df8oe** [comment]
Please test:
entering button test mode and then press&hold BAND- to reboot in powered mode.

**Comment by db4ple** [comment]
Okay, good. This means it is a) exactly the same issue and b) it seems to be quite deterministic in its timing.
So, would you be ready to receive some test binaries?

**Comment by db4ple** [comment]
@df8oe: The button test question was already answered, and yes, it works.  We go into button test earlier than printing this message.

**Comment by UR7FM** [comment]
Yes , I am ready

**Comment by db4ple** [comment]
Here we are. Flash it and tell us what happens. This software will not work correctly but may get you further in the boot process.

[fw-mchf.zip](https://github.com/df8oe/UHSDR/files/2534890/fw-mchf.zip)

**Comment by UR7FM** [comment]
Now  show start up normally , but trx frozen no any button work

**Comment by UR7FM** [comment]
input test work well

**Comment by df8oe** [comment]
@db4ple : I know button test works. But maybe it is different behaviour to boot from "cold" or have a little delay by coming from input test and starting with BAND- Button - having all the time power supply for STM.

**Comment by UR7FM** [comment]
No delay, same as older FW

**Comment by db4ple** [comment]
Okay. As I said, this firmware was not supposed to work normally. Buttons not working is expected, since I disabled some critical interrupt to find out if this is the trouble maker. We can conclude that it at least has an influence. I will think and upload a new binary in a few minutes.

**Comment by UR7FM** [comment]
ok

**Comment by db4ple** [comment]
Here we are: Try this and see if it stops again at the same position.
[fw-mchf (2).zip](https://github.com/df8oe/UHSDR/files/2535050/fw-mchf.2.zip)

**Comment by UR7FM** [comment]
Now work fb, no any stops! Where was problem?

**Comment by db4ple** [comment]
Here comes the thing: I have no idea. The firmware you are running has been compiled with exactly the same source code as df8oe used to compile the 2.9.55 official release. Only difference is that I did this build using Windows and Eclipse. Even the compiler is probably the version. So this leaves us with an unidentified issue sleeping somewhere in the source code. Since I can also run the official build without problems (the one which did not work for you), we are not much wiser expect that the problem is with very high degree not in the actual changes we did but somewhere hidden. 
Please try to use the official binary 2.9.55 just one more time in order to verify that this one still crashes.
Thank you!

**Comment by df8oe** [comment]
Iam actually using gcc 7-2018-q2-update as I did the last months. There is nothing during compilation that looks strange.

Strange was the "16KHz-issue". There are some parallels with this issue. I could not reproduce it here (except with scrambled sonfiguration) - but esmarties hav it all the time. Just like this issue. It is no proof, but I think there is a hardware dependency, too. Sadly an unidentified one vecause we could not take a look at a rig with issue using hardware debugging.

**Comment by UR7FM** [comment]
With official release same problem
![roblem2](https://user-images.githubusercontent.com/35993313/47801518-06185d80-dd37-11e8-9c38-c325491ee342.jpg)

**Comment by db4ple** [comment]
@df8oe: Could you do a "small/512k" build with https://github.com/df8oe/UHSDR/blob/active-devel/mchf-eclipse/drivers/audio/audio_driver.c#L737 commented out and upload here. 
@UR7FM: Please test this once uploaded...

**Comment by db4ple** [comment]
Good that I checked: I was compiling with an older compiler. Now running the build for the same one df8oe used. Lets see what happens now on my side. And see if the build works for @UR7FM.

**Comment by df8oe** [comment]
@db4ple can you build using Makefile on Windows? I wanted to build a "small build" using Eclipse but I failed. In spite of uncommenting #define IS_SMALL_BUILD the binary exceeds limit for small MCUs (its size is 468KB)

**Comment by df8oe** [comment]
OK - I refreshed Eclipse and now it is a small build. Could you pse test Gennadiy? It ia small build using same code and same compiler but Eclipse wrapper.
[fw-mchf(3).zip](https://github.com/df8oe/UHSDR/files/2535418/fw-mchf.3.zip)

**Comment by UR7FM** [comment]
Yes, it work well, alles in Ordnung:)

**Comment by df8oe** [comment]
Different behaviour of Makefile and Eclipse builds using same compiler. Just a shot in the dark but I think it is a race condition which is uncovered by different optimization / different linking rank order. Danilo is right: there is something sleeping in the code we cannot identify without debugging at a real rig which shows the issue.

**Comment by db4ple** [comment]
Yes, too sad. At least we have confirmation, that there is a real issue and not just some kind of random issue. It is a reproducable issue. Unfortunately not reproducable for the development team without someone sending an affected machine to use or give us remote access to an ST-Link debugging environment (or similar).
@UR7FM M/ @g7jiq : Could you please run md5sum on the download problematic files. If you don't have Linux the easiest way is probably http://onlinemd5.com/. This is to make sure we all have the same binary downloaded from the firmware archive.
Mine (which works on my machine): f0192336600201c108d1c7eccebd977b

**Comment by UR7FM** [comment]
Not working FW checksum: F0192336600201C108D1C7ECCEBD977B
working FW checksum: 055076D692123C1691204E72223893F6

**Comment by db4ple** [comment]
Ok, so we confirmed that we have identical downloads, and it works for me and not for you.

**Comment by df8oe** [comment]
My idea is that all those who do have 12 (or 24??) KHz issue *and* clean config does *not* work do have this issue, too. In my opinion it is the same, buried cause. To verify this every report is highly appreciated and welcome. Deiails as Danilo requested are mandatory.

**Comment by df8oe** [comment]
Actual state: not reproduceable on any machine of any developer. So no solution until we do have access to a machine showing the issue / someone who owns a machine can help us by debugging with ST-Link.

**Comment by ok1if** [comment]
Congratulation, version 2.9.59 doing with my clone RS918 withou problems (512kb flash). Good job
Milan OK1IF

**Comment by ok8oi** [comment]
Exactly the same symptom! Stops at the very same place. However, everything was solved this morning with 2.9.59 in my RS-918. Congratulations from me as well! Stelios SV1OI/OK8OI

**Comment by g7jiq** [comment]
Just tried the new 2.9.59 software and all works fine, well done.
Thanks to all for all the effort involved.

**Comment by db4ple** [comment]
Hi,
we are not done yet. We have no idea why the change we did, has this effect. It is a complete mystery to us, since the removed code is looking good. This should not cause any issue. So the problem may reappear at any time.

**Comment by df8oe** [comment]
Many thanks for all your feedback! We have found a solution - but in my eyes it is only a workaround. We do not understand, why
- the issue pops up only at Makefile builds
- the issue is only present at a handful devices.

So we want to make further investigations. I attach a build "59" with some modifications. Would you please test if this works for you?

Many thanks - we cannot test it here at any device...
[fw-59s-1.zip](https://github.com/df8oe/UHSDR/files/2543616/fw-59s-1.zip)

**Comment by df8oe** [comment]
@db4ple: I moved the code to the very beginning of main() - no changes to the code itself.... I am exited about the result...

**Comment by ok8oi** [comment]
I just tried the zipped file ( build "59" with some modifications) a few minutes ago. Unfortunately it has the same behaviour. It is stacked. It is freezing and nothing happens in the initialization procedure. No control what so ever on it. Had to unplug the power to stop it... 73 DE SV1OI/OK8OI

![thumbnail](https://user-images.githubusercontent.com/44703227/47939508-d2c90080-dee7-11e8-823a-d1f9f70a79af.jpg)

**Comment by ok8oi** [comment]
I went back to 2.9.59 from UHSDR Project Page and it works fine now... 
73 DE SV1OI/OK8OI

**Comment by df8oe** [comment]
Many thanks for testing. We must investigate further - the cause of the crash is still unidentified. Please test attached binary, too.
[fw-mchf-test-60-1.zip](https://github.com/df8oe/UHSDR/files/2544726/fw-mchf-test-60-1.zip)

**Comment by df8oe** [comment]
Another interesting question to all who do have the issue:
do you have populated oscillator or crystal (16MHz) for clock of STM?

**Comment by ok8oi** [comment]
Yes, this version (fw-mchf-test-60-1) now seems to work fine! 
I have a Chinese clone RS - 918 and I am afraid that I am not aware of previous issues concerning oscillator or crystal 16 MHz. I haven't touch the inside, anyway...
73 DE SV1OI/OK8OI
![thumbnailb](https://user-images.githubusercontent.com/44703227/47949868-629f9680-df4a-11e8-865d-38978b731376.jpg)

**Comment by df8oe** [comment]
Thanks for your report. We will publish results and clarifying the isue if we do have identified it.

**Comment by df8oe** [comment]
regarding oscillator / crystal:
We are looking for something that is identical on all devices which do have the issue. In original mcHF an oscillator is published, so most devices ran using oscillator. But crystal is some penies cheaper than oscillator - so maybe clones do have crystals. If we know what is identical on all devices which do have the issue we can think further... All we are actually doing are shots in the dark.

**Comment by g7jiq** [comment]
Ver 2.9.60 works fine and I have the oscillator block fitted.

**Comment by df8oe** [comment]
@g7jiq : important information is that "official build" as also the binary from my post (fw-mchf-test-60-1.zip) is working.

**Comment by g7jiq** [comment]
Just tried ver 60-1 from your post and all is well. (working fine)

**Comment by df8oe** [comment]
Thanks for testing. That clarifies the issue is NOT located in the code which was temporarily removed - I just moved it to another place nearby and all is working. Still unidentified but one step further...

**Comment by g7jiq** [comment]
Just tried 2.9.61 from the UHSDR Project Page and that works as well.

**Comment by df8oe** [comment]
OK. Not understand the problem, but we are knowing that there is something sleeping. Thanks to all for testing! I think issue can be closed.
