### ISSUE TITLE
Firmware 2.9.57 is not loading

### ISSUE THREAD

**Issue by WM0I** [df8oe/mchf-github#1600]
2.9.57
4.1.2

Your firmware version:
Your bootloader version: 

### Hardware 
 old clone

### Describe the issue:

Acts like it loads I get the reboot notice but when I reboot all I get is the transmitter red led on and not and not go off. I had to remove the power to get it back so I could load 2.9.47 for the SDR to work again..

Best regards
WM0I

**Comment by db4ple** [comment]
Hi,
Thanks for the report.
This is most likely the same issue as discussed here in #1597 
No solution yet, we're sorry. Please follow #1597

**Comment by UR7FM** [comment]
Same problem with 56 and 57 as before with 55.
