### ISSUE TITLE
Spectrum Magnify bug

### ISSUE THREAD

**Issue by ac0ax** [df8oe/mchf-github#1613]
Your firmware version: 2.9.68
Your bootloader version: 4.0.0

### Hardware 
 * UI Board: mcHF 0.4
 * RF Board: mcHF 0.4

### Describe the issue:

If I go toTouchsceen via menu and select  Spectrum Magnify and try to change it the radio locks up and makes a tone.

**Comment by db4ple** [comment]
Hi,
cannot reproduce. Please be more specific (which mode is running, from which zoom level to which), preferably attach your config here, see https://github.com/df8oe/UHSDR/wiki/Backup-and-Restore#backup--restore-on-external-computer-since-2919

**Comment by df8oe** [comment]
Not reproduceable here, too.

**Comment by df8oe** [comment]
Missing info: CPU type / flash.

**Comment by ac0ax** [comment]
sorry cpu is 413 512k

**Comment by db4ple** [comment]
Hi, 
maybe you were also affected by the Bootloader Issue #1610, please update your bootloader and test again. But I recommend to wait for the bootloader 5.0.1, which is fixed AND boots as fast as the old one and can do warm reboot (5.0.0 is fixed but boots slower and can't do reboots properly). Just for testing 5.0.0 is okay but you should really go for 5.0.1 once Andreas releases this one. 

73
Danilo

**Comment by ac0ax** [comment]
i just updated the bootloader to 5.0.0 and now the issue is gone,
