### ISSUE TITLE
SSB filter in CW mode

### ISSUE THREAD

**Issue by s53dz** [df8oe/mchf-github#162]
Perhaps there is my misunderstanding, but
- there is an option to set a CW filter in SSB mode (why?)
- there is no option to set a SSB filter in CW mode.

73, Bojan

**Comment by db4ple** [comment]
Both options have been around for a while. Due to restructuring and improvements in filter handling, one option is already gone, the other one remained.
In near future, you will have all these filter choices back (and more).

**Comment by s53dz** [comment]
TNX and sorry for bringing this up as an issue. You can dismiss this one.
Nice improvements in FW.

73, Bojan S53DZ
