### ISSUE TITLE
ALC TX

### ISSUE THREAD

**Issue by sv1it** [df8oe/mchf-github#1642]
how is it possible to alter the TX ALC settings from menu?

**Comment by db4ple** [comment]
Yes, see ALC entries here: https://github.com/df8oe/UHSDR/blob/active-devel/mchf-eclipse/support/ui/menu/ui_menu_structure_mdtable.md 

If you want to have individual control over ALC, you need to set the TX compressor level to CUSTOM. Now you can control the compressor parameters from menu.

**Comment by sv1it** [comment]
thanks a million
