### ISSUE TITLE
Sorry, please help

### ISSUE THREAD

**Issue by satoryboy** [df8oe/mchf-github#1648]
Sorry, please help about pool-request - commit: https://github.com/df8oe/UHSDR/commit/516be8f69868cf862da4456d19f41d22ae068a56?diff=unified

**Comment by m-chichikalov** [comment]
Hi Yuri, What's wrong?

**Comment by satoryboy** [comment]
OK, I will try to create a new actual branch and commit it.

**Comment by m-chichikalov** [comment]
Take a look into "rebase" and "cherry-pick" commands of the git and forget for a while the "revert" you do not need it usually.

In your fork of UHSDR repo I do not see any PULL comit, did you add remote repo as UPSTREAM to do pull?

PS, you can text or call me via Skype if you want rv9yw_max, 73!

**Comment by m-chichikalov** [comment]
read this -> https://github.com/df8oe/UHSDR/blob/active-devel/CONTRIBUTING.md

**Comment by satoryboy** [comment]
Hope, now it is OK.

**Comment by m-chichikalov** [comment]
:+1:

**Comment by m-chichikalov** [comment]
@df8oe , Andreas, could you close this one. I think it's not relevant anymore.

**Comment by df8oe** [comment]
I see this also. @satoryboy : please close your issues if they are no longer relevant.
