### ISSUE TITLE
Bug ver 2.11.1

### ISSUE THREAD

**Issue by ES8AS** [df8oe/mchf-github#1664]
Firmware version: 2.11.1
Bootloader version: 5.0.2
Hardware SDR TRX RS-958B

After upgrade to ver 2.11.1 the screen is blinking during booting and after boot. Transceiver switch off is only via power supply switch off.

**Comment by db4ple** [comment]
If the screen is white and the screen is blinking, this is normally the bootloader indicating a failed flash process. Try reflashing the binary. And check the binary was downloaded correctly.

**Comment by ES8AS** [comment]
The screen is not white. I can read on the screen everything, but blinking. Flash process completed without errors.

**Comment by db4ple** [comment]
Ok. That is a different issue then. 2.11.0 does not have this issue?

**Comment by ES8AS** [comment]
Tried to flash once more - result the same - blinking and can't switch off normally. The ver.2.11.0 is OK.

**Comment by db4ple** [comment]
OK, then stay on 2.11.0 until further notice.

**Comment by ES8AS** [comment]
Ok. Thanks! Happy New Year!

**Comment by df8oe** [comment]
I cannot confirm here on any device.

**Comment by SergiuEpure** [comment]
Same to me

**Comment by db4ple** [comment]
@SergiuEpure: You mean, you have no problems with 2.11.1?

**Comment by SergiuEpure** [comment]
@db4ple: Sorry for misunderstanding. Same problem to me, screen blinking and transceiver is off only via power supply switch off.

**Comment by db4ple** [comment]
@SergiuEpure: Please report your hardware type, especially processor type and size of flash/ram. It is all in the systems info menu.

**Comment by db4ple** [comment]
All of you, please also try 2.11.2 (it should not change the situation, but at least give it a try).

**Comment by SergiuEpure** [comment]
@db4ple my procesor is stm32f439, 2048kb flash and 256kb ram, boar if i remember well is v4

**Comment by db4ple** [comment]
Thanks. @ES8AS: Same information required from you. Also display connection is of interest (SPI or Parallel), also in system info menu.

**Comment by ES8AS** [comment]
From system menu: display HY28A/B Para, disp controller ILI9325, SI570/56.32Mhz, SI351A not found, EPROM 24xx1025/128K, FLASH 1024kB, RAM 192kB, RF Board - mcHF RF Board (ver?)

**Comment by db4ple** [comment]
Ok, I found the issue. No need to give me further information, I think. I pushed the fix. Once 2.11.2 is released, please test. The issue was only affecting STM32F4 users

**Comment by ES8AS** [comment]
The CPU is stm32f407VGT6 1M memory (as described on eBay)

**Comment by db4ple** [comment]
Thanks to all of you for reporting and helping to fix the issue!

**Comment by ES8AS** [comment]
You are always welcome!
