### ISSUE TITLE
Error during compile starting with Version 2.11.xx

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1691]
## Issue Data goes here (please remove text above):

Your firmware version: 2.11.xx
Your bootloader version: 5.0.3

Windows10
Eclipse v4.4.2-20180930-2018-09/20180930-0922-gnumcueclipse-4.4.2-2018-09-win32.win32.x86
ARM Toolchain 7-2018q2

### Hardware 
SParrow

### Describe the issue:
Hi folks,
since last weekend I can't compile the versions 2.11.xx and higher without errors!
I get 6 errors which all refer to "UHSDR_canary" ???
Versions up to 2.10.xx run without errors.
To build the DebugLib’s is no problem!
but the bin’s do not finish without errors:

![image001](https://user-images.githubusercontent.com/34752440/51236122-a1ea5a80-1971-11e9-9fe9-1033cef1532e.png)

any ideas?
more information needed?

thx
Thomas-DL8EBD

**Comment by db4ple** [comment]
Fixed in last PR #1690 (at least for me)

**Comment by ghost** [comment]
thanks Danilo!
I'll try it out later.

Thomas-DL8EBD

**Comment by ghost** [comment]
Andreas, Danilo
works again as usual!
Can be closed

thanks and greetings
Thomas-DL8EBD
