### ISSUE TITLE
Board Selection for McHF or OVI40 breaks Wiki build instructions.

### ISSUE THREAD

**Issue by rensd** [df8oe/mchf-github#1692]
Your firmware version: 2.11.12
Your bootloader version: 5.0.3
(Please note, we will generally not accept issue reports if your bootloader is not at least 5.0.1)

### Hardware 
 * UI Board: mcHF 0.6
 * RF Board: mcHF 0.6

### Describe the issue:

The building instruction in the Wiki no longer work.
Board selection is now part of the (g)make command and is done
in .travis.yml but that won't work if you just cd into mchf-eclipse 
for building

Update to:
cd mchf-eclipse 
make CONFIGFLAGS="-DUI_BRD_MCHF -DRF_BRD_MCHF" all

Should fix that

73's Rens | PA3AXA

**Comment by db4ple** [comment]
Hi Rens,
thanks for the note. But why not fix it yourself and get the full fame for it? If you can write an issue here, you can also fix the Wiki ;-)

**Comment by m-chichikalov** [comment]
This Issue on me, so far... 
@db4ple  As I understand we do not want to specify RF board? Should I change make and travis to build default MCHF_UI if not mention like "make all"?

**Comment by db4ple** [comment]
@m-chichikalov: I know. And next time we should keep in mind to update instructions. 

I think a simple default config for the build targets would solve this problem. Since most users do have a mcHF this is quite a safe default. Nevertheless we have to document the main idea of how to build other device targets. Not everyone knows that .travis.yml is the place to look, let alone is able  to understand travis.yml (or our makefile) without struggle.

**Comment by df8oe** [comment]
My GO for "mchf rf default". Actually we do not need special builds and complete hardware of rf board is done by lifetime identification. Maybe that will change in the future - so it is good to have a mech for that already present.

vy 73
Andreas

**Comment by m-chichikalov** [comment]
@df8oe , sorry Andreas, I did not get your point? Do you mean as long as we identify the RF board at the RUN time, there is no needs to use extra -D defines for it? If so, I agree. Will remove it later.

**Comment by db4ple** [comment]
I don't understand what `mchf rf default` is supposed to mean?
I think we are overcomplicating things here. Just set at the beginning of the Makefile the CONFIGFLAGS variable to "-DUI_BRD_MCHF -DRF_BRD_MCHF" if no CONFIGFLAGS are set. This would do the job sufficiently (in addition to a pointer where to get more information). With this the old
`make all` etc. will work 100% as before.

**Comment by df8oe** [comment]
No - misunderstood. Behaviour should be as Danilo wrote. if no board is sppecified in Makefile "-DUI_BRD_MCHF -DRF_BRD_MCHF" is set. Cannot tell what has to be done for Eclipse.

**Comment by m-chichikalov** [comment]
> I don't understand what `mchf rf default` is supposed to mean?
> I think we are overcomplicating things here. Just set at the beginning of the Makefile the CONFIGFLAGS variable to "-DUI_BRD_MCHF -DRF_BRD_MCHF" if no CONFIGFLAGS are set. This would do the job sufficiently (in addition to a pointer where to get more information). With this the old
> `make all` etc. will work 100% as before.

Added in #1694

**Comment by m-chichikalov** [comment]
Might be closed.
