### ISSUE TITLE
tapping in DSP box mutes audio if NR is engaged.

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1697]
Your firmware version:  2.11.15
Your bootloader version: 5.0.3

### Hardware 
 SParrow

### Describe the issue:
Hello, folks,
I just found out that the AF is completely switched off when I touch "NR" in the DSP box.
If I switch off the TRX with active "NR" and switch it on again, the AF stays away.
If I deactivate "NR" I still have to restart once to have AF again.

happens with all operating modes or filter settings

73!
Thomas-DL8EBD

**Comment by df8oe** [comment]
Cannot confirm here. McHF / OVI40-F7 / OVI40-H7 all work as expected related DSP.

**Comment by ghost** [comment]
Hello, Andreas,
I have tried to find out from which version on the error occurs.
After several installations of different builds the bug is no longer reproducible, not even with the current version.
...maybe a problem with my setup?
sorry for the false alert!

Edit: definitely my setup!
