### ISSUE TITLE
CW led setting

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1716]
Your firmware version: 2.11.22
Your bootloader version: 5.0.4

 version 6 mchf
### Describe the issue:

The setting for CW LED on/off will not save.
Always reverts to ON after power down.

de Chuck WD8BXS

**Comment by db4ple** [comment]
Yes, that's right. Turning the decoder of is stored (which also turns of the LED thingy), though.

**Comment by WD8BXS** [comment]
I do not understand!

Chuck

**Comment by db4ple** [comment]
The setting CW LED on/off is not stored permanently, it is forgotten once power is turned off. However, turning off the decoder (which is stored permanently) will also disable the LED blinking (the blink control is part of the CW decoder).

**Comment by WD8BXS** [comment]
OK, I understand now.  It is a pity though you can't have one without the other.

Chuck

**Comment by db4ple** [comment]
Well, the decoder is controlling the led. It is possible to make the "CW LED OFF" setting permanently stored, but I think, the reasoning for not doing it was the need to see it to have a feedback control for the right level for the CW decoder and this level is not a fixed setting.
