### ISSUE TITLE
FW 2.11.26 Tune crashes TRX

### ISSUE THREAD

**Issue by db4ple** [df8oe/mchf-github#1723]
Your firmware version: 2.11.26
Your bootloader version: ALL

### Hardware 
 * UI Board: ALL
 * RF Board: ALL

### Describe the issue:

Pressing Tune crashes the TRX, need to remove power.

**Comment by m-chichikalov** [comment]
Doesn't matter which mode?

**Comment by db4ple** [comment]
I don't know yet. And as I have multiple independent reports for that problem, I'll guess it is easy to reproduce.

**Comment by g7jur** [comment]
Same fault here, MCHF V0.6.2

**Comment by ES8AS** [comment]
I have the same bug.

**Comment by db4ple** [comment]
@g7jur @ES8AS  If anyone of you could test if this crash happens in all modes (CW,SSB,FM,AM) it might help me to fix it quicker. Of course, I can test it by myself but it would save me 10-15min maybe, and that is 10-15min closer to the fix.

THX, Danilo

**Comment by ES8AS** [comment]
The bug is true for SSB, BPSK and AM modes.

**Comment by db4ple** [comment]
Thanks, Not for FM? Interesting...

**Comment by df8oe** [comment]
FM and CW are working, the rest not.

**Comment by ES8AS** [comment]
Also are tested FM, RTTY and FreeDV - the same fault.

**Comment by df8oe** [comment]
Interesting. For me FM is working.

**Comment by ok1if** [comment]
In CW mode is all OK. Bug only with SSB.

**Comment by db4ple** [comment]
I get even more interested now after it is not happening all the time...

**Comment by ES8AS** [comment]
It is very strange - one time FM is OK, next time is fault. Downgrade to 2.11.25.

**Comment by df8oe** [comment]
CW and FM is working absolutely stable for me (100% working). SSB , AM and digimodes are absolutely instable (100% not working).

**Comment by db4ple** [comment]
@ES8AS : you will not have much fun with 2.11.25, use 2.11.24 or wait for 2.11.27

**Comment by df8oe** [comment]
For me this is fixed now - if you agree pse close issue.

**Comment by db4ple** [comment]
Fixed
