### ISSUE TITLE
Spectrograph bug 2.11.27

### ISSUE THREAD

**Issue by ok1if** [df8oe/mchf-github#1726]
Look video
http://leteckaposta.cz/884407055

In version 2.11.27 spectrograph not working OK and showing false signals.

Milan OK1IF

**Comment by df8oe** [comment]
Hi,

here no problems at all...

**Comment by mmarzial** [comment]
Same issue ... in version 2.11.27 and 2.11.26
version 2.11.25 is OK
73 marco

![img_20190201_194301](https://user-images.githubusercontent.com/29273968/52142896-59fa5180-265a-11e9-820b-8f31dd4e8ea0.jpg)

![false signals](https://user-images.githubusercontent.com/29273968/52142650-83ff4400-2659-11e9-99c8-7e974c3a2725.jpg)

**Comment by db4ple** [comment]
@mmarzial : If you switch to Magnify 1x (no zoom in spectrum, does the issue disappear?

**Comment by db4ple** [comment]
Problem identified and fixed. Thanks for reporting the issue.

**Comment by df8oe** [comment]
I very, very rarely use magnify - so I have not noticed that... VERY important to tell the settings, you see ;)

**Comment by mmarzial** [comment]
2.11.28 works 
Thank you

**Comment by ok1if** [comment]
Now is OK. Thank you
Milan
