### ISSUE TITLE
AGC allways "60" after Switch-On

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1730]
Your firmware version: 2.11.29
Your bootloader version: 5.0.4

### Hardware 
SParrow H7 CPU

Issue:
after each switch-on the AGC is set to "60" again, no matter what was previously set!
No matter if SSB, CW or SAM

73!
Thomas

**Comment by df8oe** [comment]
Thats correct. But I do not know if storing is useful. You have to change the value due to band, time of day etc. so that a stored value matches as rarely or as often as "60" ;) I have not looked into the code so that I am not sure it is a bug or a feature...

**Comment by ghost** [comment]
that's right Andreas, but "60" is a little far from the normal setting.
In my setup, the AGC is regular at 10-20. 

73
Thomas

**Comment by db4ple** [comment]
AGC is normally saved. I'll check what I broke. I have the same issue but did not notice. Thanks for reporting.

**Comment by db4ple** [comment]
Should be fixed now.

**Comment by ghost** [comment]
thanks Danilo and Andreas for the quick fix.
I close it later
