### ISSUE TITLE
Setting TCXO from C to F does not survive reboot after saving.

### ISSUE THREAD

**Issue by KJ6ZH** [df8oe/mchf-github#1734]
# UHSDR Firmware Defect Issue (Bug) Template 1.1

## Issue Data goes here (please remove text above):

Your firmware version: 2.11.24
Your bootloader version: 5.0.4
(Please note, we will generally not accept issue reports if your bootloader is not at least 5.0.1)

### Hardware 
 * UI Board: mcHF 0.6 
 * RF Board: mcHF 0.6

### Your relevant settings
All Modes, power, etc.

 * Display resolution: 320x240 
 * Display connected via: Parallel 
 * Touchscreen: Yes
 * Magnify: 2x 
 * Spectrum: Waterfall
 
Chris KJ6ZH

**Comment by db4ple** [comment]
Thanks for deleting the  issue filling instructions. Not many do. 

To the issue: Well, saving F has not been working for ages it seems from looking at the code.

**Comment by KJ6ZH** [comment]
Latest FW has fixed this issue.
Thank you very much.
This issue is now closed.

73 Chris KJ6ZH
