### ISSUE TITLE
Rotary encoders pinswap in MENU

### ISSUE THREAD

**Issue by LuboKuzman** [df8oe/mchf-github#1759]
Could you possible add to the menu ENCODERS PINSWAP? All at once or every encoder separate - by your mind. I used new encoders with metal shaft, that has swapped pins, all is working reverse, and I don´t want to cut pins and connect them with wires. 
Thank you.

**Comment by df8oe** [comment]
I by myself will not do that because it blows up the menu unneccessary - there is a simple way to solve that by hardware (cut the tracks on PCB and add wires). Maybe some of the other coders has a different view - we will see...

**Comment by LuboKuzman** [comment]
You have right Andreas. I did pinswap manually. But maybe for future.
