### ISSUE TITLE
Hello , I am wondering if New serial firmware 2.11.XX has Better Hilbert filters compared to 2.9.XX versions , Rx sound quality seems have better punch , am i wrong ?? did some thing really changed on Rx signal filtering and quality or just  better audio AGC reactivity   with new serial firmware 2.11.XX  thanks a lot for clarifications 73's  

### ISSUE THREAD

**Issue by nizar33** [df8oe/mchf-github#1772]
# UHSDR Firmware Defect Issue (Bug) Template 1.1

Please fill out the appropriate values.  Remove inapproriate/irrelevant values, but be prepare to provide more data. This template contains the most often asked questions.
We may adjust the template over time.

Please give as much information as necessary. At the same time, try to be concise. If you want to report something else than a defect, consider using a forum first. If you want report anything else but a defect remove the template if it does not make sense for your issue. Thank you!

## Issue Data goes here (please remove text above):

Your firmware version:
Your bootloader version: 
(Please note, we will generally not accept issue reports if your bootloader is not at least 5.0.1)

### Hardware 
 * UI Board: mcHF 0.x / OVI40 1.x
 * RF Board: mcHF 0.x / OVI40 1.x

### Describe the issue:

Place tell us what does not work and how others can reproduce the issue (list related settings, steps to do, etc.):

### Your relevant settings
Hint: most of the information can be seen on a screenshot of the main display.

If you have audio related problems:
 * DEMODULATION MODE: LSB/...
 * Filter:  2K7 LPF
 * Noise blanker setting: 0
 * Noise reduction: ON/OFF

If you have display (also fill if audio problem) related problems:
 * Display resolution: 320x240 / 480x320
 * Display connected via: Parallel / SPI
 * Touchscreen: Yes/No
 * Magnify: 1x / 32x
 * Spectrum: Waterfall/Scope/Dual
 
Other settings you consider as relevant:

 * ...

**Comment by nizar33** [comment]
Hello , and congratulation for excellent firmware, pse when touch screen pushed on spectrum some time we hear the Beep sound but without frequency changes , can we hear beep only if frequency will be changed to avoid confuse between valid touch screen valid pressed action and invalide ones ,  second the frequency step on touch screen to tune was fixed to 2Khz , can we reduced to 1Khz to be more confortable ....   thank you very much   73's  Nizar

**Comment by df8oe** [comment]
Between 2.9 and 2.11 are universes - sorry, I cannot tell you without deep digging into hundreds of commits if there are any changes in filtering - I do not have the time to do this. But if you are interested you can look at the commits by yourself - you do see the same as I do...

vy 73
Andreas

**Comment by nizar33** [comment]
Thank you very much Andreas for response
73s   Nizar
