### ISSUE TITLE
Something is wrong (2.11.54)...

### ISSUE THREAD

**Issue by ES8AS** [df8oe/mchf-github#1776]
The new file is downloaded from /uhsdr/archive/firmware/2.11.54/mcHF and uploaded to TRX, but on the display is 2.11.53. The same thing with the file from /uhsdr/firmware-latest/mcHF folder. What's wrong?

**Comment by df8oe** [comment]
The second is a symlink to the first, and after error by upload this morning I fetched a wrong version for upload some hours ago. If something goes wrong - it goes wrong the most impacting way. I hope all is ok now.

Thank you for your report!

**Comment by ES8AS** [comment]
OK. TRX firmware is updated. Thanks!
