### ISSUE TITLE
no PA output above 30m band (included) with >= 2.11.57

### ISSUE THREAD

**Issue by df8oe** [df8oe/mchf-github#1786]
I can confirm there is nearly no TX output with firmwares 57/58 on bands 30m and higher. No effect changing "Reduce Power on high Bands". Seems to be a bug...

vy 73
Andreas

**Comment by db4ple** [comment]
It works for 80m and 40m? What is the shown color and value of the power indicator for 30m?

**Comment by df8oe** [comment]
If you mean the blue box: it stays blue and font is white - same as on 80 and 40...

**Comment by db4ple** [comment]
Yes, this was what I wanted to know. Interesting, that 40m works and 30m doesn't. Do you hear the relays operating when switching bands between [EDIT]30m and 40m and vice versa?

**Comment by db4ple** [comment]
Please tune between bands by turning the dial and watch if the effective band indicator changes accordingly (the one with "Bnd" , to the right of the frequency) and if you can hear the relays operating when crossing the 4, 8 and 16 Mhz borders.

**Comment by df8oe** [comment]
Identifed :) ! Band relays are not switching all the time. They switch if I cross 4MHz but that is the only border they are switching. Neither changing from 80m "down" to 10m leads to relay switching nor switching from 40m to 30m.

**Comment by db4ple** [comment]
But all the display indicators are working as expected, right?

**Comment by db4ple** [comment]
Issue identified. Look at the 1600000 and 3200000 values in   mchf_rf_bandFilters: 
https://github.com/df8oe/UHSDR/blob/88acf3c8318c1040a0f81afa4b56369ee1bcfc16/mchf-eclipse/drivers/ui/radio_management.c#L1062

Well. If it only would be 16 and 32 Mhz...

**Comment by df8oe** [comment]
:) fixed now.
