### ISSUE TITLE
Band Display

### ISSUE THREAD

**Issue by MatthiasDirlinger** [df8oe/mchf-github#1801]
Your firmware version: 2.11.65
Your bootloader version: 5.0.4

### Hardware 
 * UI Board: mcHF 0.60
 * RF Board: mcHF 0.60

### Describe the issue:

Switching from 160m to 6m showes "Bnd6m m" in Display
It looks overwriting is to short for 2 digits change

**Comment by db4ple** [comment]
Indeed. Going to be fixed soon.
