### ISSUE TITLE
Band Definition / Region not saved

### ISSUE THREAD

**Issue by MatthiasDirlinger** [df8oe/mchf-github#1802]
Your firmware version: 2.11.65
Your bootloader version: 5.0.4

### Hardware 
 * UI Board: mcHF 0.60
 * RF Board: mcHF 0.60

### Describe the issue:

Band Definition in Menu is not saved to eeprom or not read on startup
Setting is back to default R1+2+3 on startup

**Comment by db4ple** [comment]
Yes. This is as intended for the moment, see #1783
