### ISSUE TITLE
V2.11.71: MHZ digit flickers

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1818]
Your firmware version: V2.11.71
Your bootloader version: 5.0.4

### Hardware 
SParrow with H7 CPU (400MHz version)

### Describe the issue:

- the MHz digit flickers during tuning

73!
Thomas

**Comment by S54AM** [comment]
Using last FWs (also on 72) I noticed similar indications (flickering and step problem). The last version without this problems, on my McHF is V2.11.69.

**Comment by db4ple** [comment]
Flickering: I have to look into this using a real machine.

**Comment by ghost** [comment]
Danilo, it looks like the MHz digit is erased and rewritten every time the frequency changes with the VFO button - not with a blank, but with a filled box

73
Thomas

**Comment by ghost** [comment]
solved, thx!
