### ISSUE TITLE
V2.11.74: the "9" on the main frequency display is "defective"

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1825]
Your firmware version: V2.11.74
Your bootloader version: 5.0.4

### Hardware
SParrow with H7 CPU (400MHz version)

### Describe the issue:
a minor bug: the "9" on the main frequency display is defective

![image](https://user-images.githubusercontent.com/34752440/69082779-19c95b80-0a41-11ea-8708-070e88fb68eb.png)

73!
Thomas

**Comment by S54AM** [comment]
By the way, also on my mcHF apears those hardly noticed dots bellow numbers 9.
P.S. 
Thanks Danilo for flickering fix.

**Comment by ghost** [comment]
solved!
thanks for the fix
