### ISSUE TITLE
wrong RAM size in System Info with 480MHz STM32H743ZIT6U

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1831]
Firmware:  D2.11.78
Bootloader: 5.0.4
Hardware: SParrow 

**only a minor bug:**
with the new H7 CPU STM32H743ZIT6U, we see a wrong RAM size in system Info

![image](https://user-images.githubusercontent.com/34752440/72128568-a0c8ef00-3373-11ea-93de-1651cede09fd.png)

73
Thomas

**Comment by db4ple** [comment]
Well, it depends what is the definition here: We show the "usable" RAM for UHSDR, i.e. not necessarily the full RAM provided by the hardware. And on the H7 we indeed use "only" 512k. The RAM is scattered (not my words, these are STM's words: https://www.st.com/en/microcontrollers-microprocessors/stm32h743-753.html ).
So it is 64 ITCM + 128 DTCM + 512 + 288 + 64 user RAM and finally 4k Backup RAM. This adds up to 1024k. We are just using the large 512k block of it.

Not sure if there is a need to fix this. Maybe we adds this to the help text.

**Comment by ghost** [comment]
Thanks Danilo!
I think we can close this issue.
There is no bug and the question has been answered.

73
Thomas
