### ISSUE TITLE
Menu Enhancement

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1833]
Hi All,  I thought since all has been going well with the new IQ adjustments , maybe you could move them all to the config menu along with the original settings. Then we can just go right down the list.

Also I think the default value would be much better set at zero.  I have found that the completed values all are close to zero.
So having the default at zero, you won't have to crank the knob as much hihi

Just a few thoughts,

Thank you so much for all you do!!

**Comment by df8oe** [comment]
Implemented with #1836

vy 73
Andreas

**Comment by WD8BXS** [comment]
Very nice, TNX,  Chuck
