### ISSUE TITLE
About Operating Manual on Wiki

### ISSUE THREAD

**Issue by satoryboy** [df8oe/mchf-github#1837]
Your firmware version: 2.11.79
Your bootloader version: 5.0.4
(Please note, we will generally not accept issue reports if your bootloader is not at least 5.0.1)

### Hardware 
 * UI Board: mcHF 0.6 (R928+ with Si570)
 * RF Board: mcHF 0.6 (R928+)

### Describe the issue:
Please supplement Operating Manual on Wiki:

In the "Key Press Map" table, a long press of BAND- or BAND+: jump down / up by frequency 
to the width of the panorama.

In the table "Color and Blink Codes of the LEDs Explained": frequent flashing of the red LED - protection operation by SWR.

**Comment by df8oe** [comment]
No need to open an issue - you can correct / add this by yourself!

**Comment by satoryboy** [comment]
OK! How?

**Comment by satoryboy** [comment]
Good day, Andreas. 
I did not find any instructions on how to edit the wiki of the project. I hope for your help. Enough links.

  
>Понедельник, 2 марта 2020, 13:41 +05:00 от DF8OE <notifications@github.com>:
> 
>Closed  #1837 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Юрий Коренев

**Comment by db4ple** [comment]
In DF8OE Github: just click on Wiki and go to page you want to change. If you are logged into your github account, you will be able to see an EDIT button in top part of the page.

**Comment by satoryboy** [comment]
Thank you very much! 73!

  
>Понедельник, 2 марта 2020, 14:06 +05:00 от db4ple <notifications@github.com>:
> 
>In DF8OE Github: just click on Wiki and go to page you want to change. If you are logged into your github account, you will be able to see an EDIT button in top part of the page.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Юрий Коренев
