### ISSUE TITLE
CW filter mis-match

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1839]
I have to wonder why we have a 300-800 setting but do not have a 500 - 800 setting.

500 - 750,  then 500-850

maybe this needs to be corrected so they match.

Thanks,
Chuck WD8BXS

Hope everyone is staying home!

**Comment by WD8BXS** [comment]
Hello, is anyone there??? hihi

**Comment by db4ple** [comment]
Hi, yes. I am here.  But I am not an expert on narrow filters, but I can share my opinion: With a fairly "flat top" 500 Hz Filter, I'd say, the filter designers thought, we don't need 50 Hz steps. 50 Hz with 300 Hz BW are 1/6 or approx. 20% of BW per step, with 100Hz per 500Hz BW we have also 20%.

**Comment by WD8BXS** [comment]
Hi There!! Thanks for answering
