### ISSUE TITLE
What tools for mcHF?

### ISSUE THREAD

**Issue by Pluscrafter** [df8oe/mchf-github#1840]
It's the false location to ask it but what tools do you need to assemble the mcHF kit with the presoldered SMD. And is a LCR meter, a multimeter an osilloscope enought for assembling? And is there any tools  I need to calibrate the radio?

**Comment by db4ple** [comment]
Indeed, wrong location. You are welcome to post to in the forum. English posters are welcome there!

In addition to your list a 50 ohm HF dummy load with at least 10W, better 20W is very helpful not not strictly necessary for PA calibration if you can use your oscilloscope for measuring the Vpp.

**Comment by db4ple** [comment]
Please close the issue!
