### ISSUE TITLE
 artefacts on TFT when entering a frequency via Touch

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#1846]
Your firmware version: 2.11.81
Your bootloader version: 5.0.4

### Hardware 
 * UI Board: SParrow H7 (480MHz)
 * RF Board: SParrow

only a minor blamish:
I have noticed that artefacts are created when entering a frequency via Touch
![38314155zt](https://user-images.githubusercontent.com/34752440/79533531-5f359780-8078-11ea-81a8-f1057d053448.jpg)

vy73
Thomas
stay healthy!

**Comment by sp9bsl** [comment]
Should be fixed with my last commit. Need some more work to enable the rest of UHSDR code to enter bigger frequency than 2^31Hz in direct mode. I think we will go in variable length font in future, this is just the patch to make slimmed dot char usable.
