### ISSUE TITLE
BD/SFT

### ISSUE THREAD

**Issue by SP5QAD** [df8oe/mchf-github#1857]
## Issue Data goes here (please remove text above):

Your firmware version: 2.11.82
Your bootloader version: 5.0.4
(Please note, we will generally not accept issue reports if your bootloader is not at least 5.0.1)

### Hardware 
 * UI Board: mcHF 0.6
 * RF Board: mcHF 0.6

### Describe the issue:

By running try RTTY I have the option in the second line of options on the display being able to change values ​​such as "BD" and "SFT".
If I press "MODE" now - I switch to "LSB" mode, but the "BD" and "SFT" change options are still active. The transition to settings compatible with the current operating mode appears only after pressing "AF" and "RF":
change from "BD" to "CMP" and change from "STF" to the speed of "AGC".

---
73, Marcin

**Comment by db4ple** [comment]
Cannot reproduce in 2.11.95 anymore. Please reopen if still happening.
