### ISSUE TITLE
what is the meaning "Nothing to build for mchf-eclipse"?

### ISSUE THREAD

**Issue by ideapad2009** [df8oe/mchf-github#1869]
project can not compile.

**Comment by df8oe** [comment]
Please can you specify your workspace? Graphical tool or build via make? I am building via make and it works perfectly.

**Comment by ideapad2009** [comment]
I import the archive into eclipse IDE and use the Build  menu. It give the tip  "Nothing to build for mchf-eclipse" in console.

**Comment by df8oe** [comment]
I haven't build using IDE since years - only building via make. Have you build mchf-libs first? Every build consists of two steps. First the libraries, then the firmware...

**Comment by ideapad2009** [comment]
mchf-libs also can not build. The ArtifactType of "Build ArtifactType" menu is null instead of "Executable".

**Comment by db4ple** [comment]
Hi, let me ask you a couple of questions, please answer ALL of them:

Did you follow the instructions given in the UHSDR Wiki to install GNU MCU Eclipse etc.? 

If not, please do so and try again with this Eclipse installation. Is it working now?

If you did install GNU MCU Eclipse and it is not working, please paste the screen shot of your Eclipse project view and the "Help->About Eclipse" window. 

THX!

**Comment by ideapad2009** [comment]
> Hi, let me ask you a couple of questions, please answer ALL of them:
> 
> Did you follow the instructions given in the UHSDR Wiki to install GNU MCU Eclipse etc.?
> 
> If not, please do so and try again with this Eclipse installation. Is it working now?
> 
> If you did install GNU MCU Eclipse and it is not working, please paste the screen shot of your Eclipse project view and the "Help->About Eclipse" window.
> 
> THX!

Hi,I do exactly as the guide again.Things changed, Build Error information: Program "arm-none-eabi-gcc" not found in PATH. I am sure I have installed arm-none-eabi-gcc.

**Comment by db4ple** [comment]
Hi, verify that on Window->Preferences->MCU the "Global ARM Toolchain Paths",  "Global Build Tool Paths", "Global OpenOCD Path" point to the right directories/settings where the respective tools are installed. Paths will not be indentical to the picture shown below, but you get an idea. The paths usually end with ".../bin"

![image](https://user-images.githubusercontent.com/17237769/88252671-5e338800-ccaf-11ea-99f0-038028f95873.png)

**Comment by ideapad2009** [comment]
> Hi, verify that on Window->Preferences->MCU the "Global ARM Toolchain Paths", "Global Build Tool Paths", "Global OpenOCD Path" point to the right directories/settings where the respective tools are installed. Paths will not be indentical to the picture shown below, but you get an idea. The paths usually end with ".../bin"
> 
> ![image](https://user-images.githubusercontent.com/17237769/88252671-5e338800-ccaf-11ea-99f0-038028f95873.png)

Per your tip,I have sucessfully compiled. Thank you.
