### ISSUE TITLE
Update 2.11.93, 2.11.94 does not work with 512kb cpu

### ISSUE THREAD

**Issue by g7jiq** [df8oe/mchf-github#1887]
Your firmware version: 2.11.92 (working)
Your bootloader version: 5.0.4
(Please note, we will generally not accept issue reports if your bootloader is not at least 5.0.1)

### Hardware 
First release of mcHF with 512kb cpu, 
 * UI Board: mcHF 0.x unknown first release
 * RF Board: mcHF 0.x unknown first release

### Describe the issue:

Has been working ok with all earler updates,
Updates 2.11.93, 2.11.94 stick on boot screen with flashing red/green leds,
reloading 2.11.92 works fine.

* Additional info *
I have just tried the latest 2.11.94 on my newer ver of the mcHF with a 1024 cpu and all works ok,

**Comment by df8oe** [comment]
very interesting.... This needs confirmation. I do not have access to 512KB MCU since a couple of years and cannot check...

**Comment by db4ple** [comment]
Looking at the changes we did between 2.11.92 and 2.11.93 I doubt it is a 512k issue.

@g7jiq : Did you ever use an "unofficial" UHSDR firmware on this machine (like the ones posted in some forums with changes)? Don't get me wrong, this is absolutely fine.
But as configuration values may have been added there without coordination with the main firmware, this can break things as there may be values left in the the configuration memory which do not work with the newer UHSDR firmware using this data for some different stuff.  Given the fact that we just added one configuration parameter in 2.11.93 this is a plausible explanation. This parameter if set to a wrong value will cause a crash of the machine.

**Comment by df8oe** [comment]
@g7jiq : you can check if this is the reason by starting mcHF while buttons F1 + F3 + F5 are pressed. If the radion starts now **it is a configuration scrambling problem**.

**Comment by db4ple** [comment]
@df8oe: Good tip. 
@g7jiq : If you pressed F1+F3+F5 => DO NOT TURN OFF MACHINE using Power button, this will overwrite all of your configuration values including calibration etc. with defaults.  Just remove the power by pulling the plug.

**Comment by df8oe** [comment]
I just got a feedback that a 512KB machine works with 93 and 94 firmware. Reason for malfunction is not MCU (flash size).

**Comment by g7jiq** [comment]
Hi, Just tried the F1+F3+F5 and it did nothing, (the LEDs just flashed a different sequence)
Re-flashed it back to 2.11.92 and it works again. (if this is down to the old hardware/mods, I am happy to leave as ver 2.11.92 and only update my newer one)
The only software updates I have used are from your github since ver 2.5.10 (I have them all backed up and this one seems to be the earlyest one I have)

**Comment by db4ple** [comment]
@g7jiq:  No need to stick on 2.11.92. We will identify the root cause for the problem and fix it. You maybe not the only one with this issue. With your help we will get this done quickly.
LEDs flashing indicate a crash and basically tell us what happened. Could you record this on video and upload it here (just drag the video into the comment)?

**Comment by g7jiq** [comment]
Just to let you you know I have just tried the latest 2.11.95, and it works fine on both my 512 and 1024 cpu radios,
Many thanks to all.
