### ISSUE TITLE
mcHF Band Edges according to the IARU region and country

### ISSUE THREAD

**Issue by HS0ZRT** [df8oe/mchf-github#1904]
A few months ago I raised a question in mcHF@groups.io about the setting of TX Band Edges in a mcHF to comply with the regulations of a country (namely Thailand).
My question was solved end of last December and I found it solved in the last firmware "UHSDR-active-devel". Now I wonder how I could set these THAI band edges in a mcHF. To be more precise there are in this source code the three IARU regions 1, 2 and 3 and added to them the 3 region with Thai specifics, how can I chose the IARU region I want to implement in the setting-up of the mcHF, with what Menu... ?
See : Added Region 3 Thailand and the concept of RX Only Ham Bands by db4ple · Pull Request #1885 · df8oe/UHSDR · GitHub

I just found in UHSDR/ui_menu_structure_mdtable.md at active-devel · df8oe/UHSDR · GitHub 
the following command :

Band Definition (Menu_Conf)
LABEL (NR)                                DESCRIPTION
CONFIG_BANDEF_SELECT     Select which band definition to use for ham bands (Original UHSDR or IARU Region 1 - 3

Where shall I find this command in a mcHF and how can I actually set-up the IARU Region in the mcHF I plan to build?

73 - Pierre - FK8IH

**Comment by db4ple** [comment]
Load the newest firmware. Go to configuration menu, find entry "Band Definition", select "Thailand". 
Done. Transceiver will have bands according to Thai regulations.

You cannot define band edges directly, you can only select one of the 5 different predefined settings.

**Comment by HS0ZRT** [comment]
Thank you very much for your answer, which I copied to the mcHF@groups.io
73 - Pierre - FK8IH
