### ISSUE TITLE
CW Straight Key operation

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#1920]
This is the first time I have ever tried to use a straight key with this radio.
I find it impossible to use, it seems to send a dash every time.
You can't just tap the key and get a dot, very strange.
I am using the latest firmware 2.12.0
Is there a setting I am missing??

TNX, Chuck

**Comment by db4ple** [comment]
Closed, as Chuck reported in the forum that it is working: https://www.amateurfunk-sulingen.de/forum/index.php?board=15;action=display;threadid=1825
