### ISSUE TITLE
Fix the CMP output levels

### ISSUE THREAD

**Issue by sp9wpn** [df8oe/mchf-github#1926]
## Issue Data goes here (please remove text above):
Your firmware version: D2.12.2
Your bootloader version:  5.0.4
(Please note, we will generally not accept issue reports if your bootloader is not at least 5.0.1)

### Hardware 
 * UI Board: mcHF 0.6.3
 * RF Board: mcHF 0.6.3

### Describe the issue:
When CMP off, radio is operating at full power, ignoring current PA setting.

When CMP is on (with any value), PA setting is respected, but the actual power output is far below chosen setting. Practically impossible to reach 2W output in the peaks.

To reproduce:
Set SSB mode, MIC input. Set PA=0.5W, set CMP=OFF.
Transmit your voice and observe power slider shooting through 5W up to 10W in the peaks.

Now set PA=5W and CMP=0 (or any other)
Transmit your voice and observe power slider always below 2W.

### Your relevant settings
Mic GAIN 87 (electret mike). Raising gain to the max does not help.

**Comment by df8oe** [comment]
I have checked with two different mcHFs: I cannot reproduce. Maximum output power is not dependent on CMP level. Of course output power of speech increases significantly when higher CMP levels are set: that is what compression should do. So I need confirmations about an issue here. Please do not check power with power sliders: they are too inaccurate. Best way of watching output is with a dummy load and an oscilloscope.

**Comment by sp9wpn** [comment]
To clarify: output power depends on CMP OFF/ON status, not CMP level set.
At http://d.wojtus.net/mcHF there's a video recording and also voice recording from remote SDR, where I cycle from OFF, then 0..3.....12 and back to OFF. This gives obvious impression of reduced power (please not: at the end of the recording I said by mistake "compression zero", while it was "OFF").
I'll try to add some oscilloscope metering later on.

**Comment by sp9wpn** [comment]
OK, I've made measurement with a scope and I've found that CMP does work perfectly. It's the CMP=OFF state when actual Tx power brutally exceeds PA settings. Video to watch this behaviour here: http://d.wojtus.net/mcHF/mcHF_cmp_power.mp4
Whether this is a bug or not - please decide.

**Comment by df8oe** [comment]
You are right. This does not bother much because you can use CMP=0 instead of OFF. So I decide to leave it as it is because it is not trivial to solve.
