### ISSUE TITLE
CHANGE:  Changed Approach for Selecting Filters 

### ISSUE THREAD

**Issue by db4ple** [df8oe/mchf-github#195]
In the current devel-DF8OE branch a different approach for selecting filters was implemented. It was necessary to change from the current model due to the high number of added filters in some modes. The existing approach for selecting filters for use did not scale was not able to cover different filters for different modes and the same bandwith.

The newly implemented approach is very different. For each of the demodulation modes the user can either choose from the full list of applicable filters using button G4 and the encoders 2 and 3; or pick one of the filters from a  predefined list of favorite filters for a demodulation mode. 

That makes the filter selection both powerful (with encoder you can quickly select any applicable filter in very short time) and convenient (the quick list is defined in less than a minute for all 4 modes which have a quick list). In order to use this,  the Filter button G4 operates as follows:

G4: Short press - Select next filter path from quick list.
G4: Long press - Activate encoder 3 and 2 as filter selector knobs. You will see a visual indication in the filter display (change of color). Return to normal with short press of G4.
Encoder 3 lets you go through the full list of applicable filters  for a given mode
Encoder 2 lets you skip to the next/prev bandwidth and selects the first/last filter in that bandwidth

SSB, CW, AM and the new SyncAM have quick lists, FM with only 3 filters simply offers all three of them.

The quick lists are defined per mode (all bands share same quick list per mode) in the Filter Selection.
All other filter selection functions (wide filter in CW / narrow filter in SSB most notably) have been "removed" as these are no longer necessary.

We ask for your comments and collaboration in this quite radical change, especially on the following topics:
- Do you need Encoder 2 (switches to first applicable filter in next higher/lower bandwidth)?
- Is the number of entries in the quick list sufficient (4), and if not, what number would be appropriate. Keep in mind that Encoder 3 allows to you go through all modes very, very quickly?
- Are filters offered for a given mode missing but available in other modes? 
  If there is a consensus on these which is different from the current experimental implementation, we can change any of these quickly.

Other changes may be more difficult to implement.

If positive feedback is received, we will remove that "old handling" from the code very soon. Keeping old and new approach working in the code makes the implementation more complex and is essentially producing "dead code".

**Comment by db4ple** [comment]
No significant changes (except for CW filter set change, which has been done) have  been asked for.
Removal of old code will commence now (actually did start already).

Thanks for  the feedback through the various communication channels.

**Comment by df8oe** [comment]
closed.
