### ISSUE TITLE
Firmware 2.12.2 for mcHF 0.5 with ESP8266 module

### ISSUE THREAD

**Issue by Dirk275** [df8oe/mchf-github#1951]
I have a mcHF 0.5 and want to add the ESP8266 Wifi module on the UI board.

Does the latest firmware 2.12.2 recognize the ESP8266 module or do I have to use a specific version of this last firmware for this purpose?
Any chance to get binaries of that version??

**Comment by df8oe** [comment]
Sorry - at the moment no support for this module. Additionally there is at the moment no active development. But contributors are always welcome ;)

**Comment by Dirk275** [comment]
Thank you for the info, Andreas!
In 2016..18 there must have been a compiler option for using the ESP8266 module. On the schematic of the mcHF 0.5 Chris noted, that after adding the ESP8266 module at its place on the UI board only the firmware would have to be recompiled in order to use the module.
So I thought, that perhaps this compiler-option still resides in the actual firmware.

**Comment by df8oe** [comment]
Maybe Chris' version supported this. UHSDR never did.

**Comment by Dirk275** [comment]
Ok, thank you.
