### ISSUE TITLE
switchoff encoder filter mode when entering menu

### ISSUE THREAD

**Issue by DD4WH** [df8oe/mchf-github#198]
If in Encoder-Filter-Select-Mode (filter display orange) it would be good that one would automatically leave this mode when you enter the menu. Otherwise you can not use encoder2 and encoder3 to toggle the menu points. When leaving the menu, it would be very nice, if the Encoder-Filter-Select-Mode (filter display orange) could be switched on again automatically (if you were in it at the moment when you entered the menu) ;-)

**Comment by df8oe** [comment]
fixed.

vy 73
Andreas
