### ISSUE TITLE
Frequency display should show inactive VFO in small freqnency display

### ISSUE THREAD

**Issue by df8oe** [df8oe/mchf-github#2]
It will be a good feature if regardless to mode the big numbers always show freqnency of active VFO and the small ones of the other VFO...

**Comment by imoldovavan** [comment]
This should be a nice way of trying the Gitflow Workflow. So the next step would be to start a feature branch from the devel. Right?

**Comment by df8oe** [comment]
So it is...

**Comment by df8oe** [comment]
This is not a wanted feature. In non-split-mode upper small frequency shows receiving frequency wihile using RIT and lower large digits show transmitting frequency. No need to change anything.
