### ISSUE TITLE
Menu entry DSP ON not stored 

### ISSUE THREAD

**Issue by HB9LFU** [df8oe/mchf-github#221]
Hello Programmers

I found that when I set the menu entry DSP (experimental) to ON it is OFF again after a restart.

vy73s
Roger

**Comment by df8oe** [comment]
Hello Roger,

that is not a bug - its a wanted behaviour.

DSP leads to instability of mcHFunder serious circumstances and therefore it is NOT stored. Everyone who wants to use this dangerous function is remained THAT IT IS DANGEROUS when he must turn it each time he powers on mcHF. If it is stored we can have left it "as it was" - and get strange bugreports which are are based on DSP malfunctions and we cannot reproduce easy.

vy73
Andreas
