### ISSUE TITLE
Stuck in button test on 0.219.27.0

### ISSUE THREAD

**Issue by wkazubski** [df8oe/mchf-github#242]
I am trying to install 0.219.27.0 version of firmware (latest stable) but it enters Button Test despite no button is pressed, except Power. The display indicates one button pressed and its name is displayed as "ff <space><space> ff". I am not shure if there are two or three spaces in middle, but it seems to be out-of-the-table read. If I press any button, its name appears and the number of button pressed is now 2. 
In earlier versions Button Test worked correctly.
I suspect two possibilities:
1) button read function reads an extra pin, which is treated as active pin,
2) something misconfigured with touch screen, which is tested togerher with buttons (if I am correct).

Wojciech SP5SMK

**Comment by df8oe** [comment]
Hello Wojciech,
firmware detects "touchscreen operation" by a low voltage on TP_IRQ wich is connected to header pin7 (PA4 of MCU). Touchscreen is interpreted as "button". The two digits which are shown are the x and y position of touched point on touchscreen. Both FF show you do not have touchscreen mod UI-04-N-026 (or mod is faulty).

Please investigate why PA4 is torn down to GND. Maybe you have fitted Q2 on rf-board which is obsolete.

That is not a firmware issue at all.

vy 73
Andreas
