### ISSUE TITLE
when using sync am then hdsdr is switched to usb (wrong cat command?)

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#256]
title says it all

when i use mchf in sync am ... and start hdsdr then hdsdr is set to usb

should be am or ecss in hdsdr

greetz

sigi

**Comment by db4ple** [comment]
Yes, this is kind of an issue. The FT 817 does not know about Sync AM, so CAT is not able to report mode correctly. Since it does not know about ECSS either, only choice is AM. Be aware, that there will be no easy way to set Sync AM from the CAT interface for the same reason.

**Comment by df8oe** [comment]
Now AM is selected (no other mode fits better)

vy 73
Andreas
