### ISSUE TITLE
Spurs 

### ISSUE THREAD

**Issue by HB9LFU** [df8oe/mchf-github#257]
![mchf 80m5w](https://cloud.githubusercontent.com/assets/17696364/14532699/41065292-0262-11e6-85db-33523afdc8e6.jpg)

This is how my mcHF's 5W signal looks when fed directly via an attenuator into the sdr transceiver.
No microphone used, only the tune button.

The strongest spur is about 35dB lower than the main signal.

**Comment by DD4WH** [comment]
I do not see the point you are making? Is there some question you would
like to ask or a problem you would like to describe? If so, please do so ;-)

Regarding the aspect of NOT taking the TUNE
 signal as the basis of any discussion about signal quality, there is some
information to be found here:

https://uk.groups.yahoo.com/neo/groups/M0NKA-mcHF/conversations/messages/5949

Have fun with the mcHF,

73 de Frank DD4WH

2016-04-14 17:02 GMT+02:00 HB9LFU notifications@github.com:

> [image: mchf 80m5w]
> https://cloud.githubusercontent.com/assets/17696364/14532699/41065292-0262-11e6-85db-33523afdc8e6.jpg
> 
> This is how my mcHF's 5W signal looks when fed directly via an attenuator
> into the sdr transceiver.
> No microphone used, only the tune button.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/df8oe/mchf-github/issues/257

## 

---

Frank - DD4WH
QTH - Dresden, Germany
Rx/Ant remote - Perseus SDR & K9AY lowband antenna
Rx/Ant local - Teensy SDR standalone homebrew ugly style Rx

## & AAA-1 Bulgarian active Antenna with double loop
