### ISSUE TITLE
[Request] One touch button for resetting 100, 10 and 1 hz

### ISSUE THREAD

**Issue by DL3NCW** [df8oe/mchf-github#263]
It would be very helpfull if one can "zero"  100, 10 and 1 hz digits by 
hitting one button. This is especially helpful if one has used the snap function.
Usually ham operators try to be on x.000.

Otherwise you have to go through with the step button and manually zero each digit

**Comment by df8oe** [comment]
I will implement this by touching "TUNE" (touchscreen function). Buttons are no longer available - most of them are actually atready used double and triple ;)

vy 73
Andreas

**Comment by df8oe** [comment]
Done.

vy 73
Andreas
