### ISSUE TITLE
Vertical Line indicating working frequency not present in Spectrum Light Mode On

### ISSUE THREAD

**Issue by HB9LFU** [df8oe/mchf-github#264]
Hi Andreas,

just hit upon the new spectrum light entry in the menu. Looks fine but could you add the vertical Line that is present in the normal mode. Best in front of the spectrum as you modified recently.

vy73s
Roger

**Comment by DD4WH** [comment]
Hi Roger,

I will add that in the next days!

73 de Frank DD4WH

2016-04-16 10:54 GMT+02:00 HB9LFU notifications@github.com:

> Hi Andreas,
> 
> just hit upon the new spectrum light entry in the menu. Looks fine but
> could you add the vertical Line that is present in the normal mode. Best in
> front of the spectrum as you modified recently.
> 
> vy73s
> Roger
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/df8oe/mchf-github/issues/264

## 

---

Frank - DD4WH
QTH - Dresden, Germany
Rx/Ant remote - Perseus SDR & K9AY lowband antenna
Rx/Ant local - Teensy SDR standalone homebrew ugly style Rx

## & AAA-1 Bulgarian active Antenna with double loop

**Comment by HB9LFU** [comment]
Hallo Frank,

yes, thanks, think it will be helpful for orientation! This spectrum light mode saves some cpu power?

vy73s
Roger

**Comment by DD4WH** [comment]
Hi Roger,

the line has been added and also the menu entries have been altered by Andreas. 

Everything fine now. 

Issue can be closed.

73 de Frank DD4WH
