### ISSUE TITLE
mcHF freezes when in AM mode

### ISSUE THREAD

**Issue by wemaus** [df8oe/mchf-github#273]
With the newest version of fw (dailyshnapshot 17.04.16) and also older ones the mcHF freezes in AM mode when DSP is in NR+Notch mode and filter is set over 2,7 kHz.

73, Werner, DG8WM

**Comment by df8oe** [comment]
Thats not an issue - its normal. DSP produces so much processor load that all other functions suffer. There is nothing to do.

vy 73
Andreas
