### ISSUE TITLE
strong signal in spectrum light mode draws into the text bar above spectrum

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#276]
if a signal is high (say a strong am station) it draws into the text bar above the spectrum view

does only happen in light view (not filled spectrum) ... zoomed and non zoomed

if signal is very high then it is not only the carrier but also sidebands that draw into the text bar

when turning dial slowly you can "wipe out" the complete bar ... means the top signal is not deleted but stays inside the text bar

(pictures needed??)

 why not delete that complete bar and gain more viewing area for spectrum?!? ... switching zoom and non zoom or switching to waterfall could be made like it was now ...

light mode has no squares (scale) ... so the 2 s units/div (or what you set in menue) ... is useless then ... so for me that complete bar is useless (except the button functions for zoom and waterfall)

dg9bfc

**Comment by DD4WH** [comment]
Andreas has now implemented menu choice whether the bar is present or not. The issue has therefore been solved. 

I am continuously thinking about improving the snap carrier, but I think with our horsepower it cannot be made much more accurate than the present +-2Hz. But I have one more idea, watch out for more in the next week ;-)

Issue can be closed.

All the best and thanks for your reports!

73 de Frank DD4WH
