### ISSUE TITLE
Keine Ausgabe auf externen Lautsprecher nach einem Bandwechsel bzw. TUNE

### ISSUE THREAD

**Issue by DC6MK** [df8oe/mchf-github#281]
Hallo,

habe die aktuelle - Firmware Stand vom : 19.04.2016 18:49:09 aufgespielt und beobachte folgendes Verhalten.
Bei einem Bandwechsel bzw. TUNE keine Sound-Ausgabe mehr auf dem externen Lautsprecher-Ausgang. Erst nach verstellen von AFG wieder Sound-Ausgabe aktiv.

73
DC6MK

**Comment by df8oe** [comment]
Will be fixed ASAP.

vy73
Andreas

**Comment by df8oe** [comment]
fixed.

vy 73
Andreas
