### ISSUE TITLE
vfo in grey numbers after power on and if vfo a and b are same numbers

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#294]
after a power on the vfo is drawn in grey (like in locked vfo mode) ...

vfo is not locked!

turning dial makes numbers white

if vfo an and b set to same qrg then the numbers change to grey if press vfo a/b ... if vfo a and b are different numbers then the dial stays white when pressing vfo a/b

pressing vfo a/b long (making vfo a and b equal) change numbers to white and pressing it short after that and the numbers are grey again

**Comment by df8oe** [comment]
ixed.

vy 73
Andreas
