### ISSUE TITLE
Menu - Hardware info does not show active touchscreen

### ISSUE THREAD

**Issue by DL3NCW** [df8oe/mchf-github#305]
Have made touchscreen mod and touchscreen is working like switching meter, choose signal in spectrum scope etc.
If going into menu - hardware info, it shows "touchscreen n/a" and touchscreen does not work in menu.

**Comment by df8oe** [comment]
I have heard this from some OMs but I cannot reproduce it here and I have no idea what can go wrong. Sorry - no solution at the moment :(

In Menu mode touchscreen gets completely different functions - at the moment for debugging purposes (not user documented).
vy 73
Andreas

**Comment by ghost** [comment]
Hi,

the same behavior here.

73, Wolfgang

**Comment by DG9BFC** [comment]
same here

touch function works but is not shown in hw info

72 sigi

**Comment by df8oe** [comment]
I see. It worked since months correctly and so I do not have tested it again.

Since ??? it does not work. I will take a look.

vy 73
Andreas

**Comment by DG9BFC** [comment]
same here ... i have not seen in hw info for many weeks (cause tp 
function worked i though in hw info it is also shown correct) ...

... sure you will find it :-)

73

sigi

Am 24.04.2016 um 14:10 schrieb DF8OE:

**Comment by df8oe** [comment]
so it is ;)

fixed.

vy 73
Andreas

**Comment by DL3NCW** [comment]
Yeahh Andreas you are my hero !
