### ISSUE TITLE
Switching from Digital - Freedv1 - etc

### ISSUE THREAD

**Issue by DL3NCW** [df8oe/mchf-github#307]
By using touchscreen one can switch from Digital to Freedv1 and so forth.
The same happens if one pushes "DSP-OFF"

**Comment by DD4WH** [comment]
as far as I know, that is absolutely intended!? That is the preparation for the digital modes.

**Comment by DL3NCW** [comment]
You are right, it is not yet implemented.
But one does not want to switch by also pressing on DSP-OFF as this button should do something else

**Comment by df8oe** [comment]
Your touchscreen is _extremely out of specs_...

Touching in DSP should not affect digital mode settings. I know one other OM from Yahoo group whose LCD is absolutely out of specs - other direction. I am not sure that this can be solved with a touchscreen calibration code ( I am just working on it). I think you have to replace LCD...

vy 73
Andreas
