### ISSUE TITLE
Frequency Display in Split Mode

### ISSUE THREAD

**Issue by HB9LFU** [df8oe/mchf-github#308]
Hello programmers,

when using split mode in mcHF we get two lines in small print. Ok

But to have most from the little display would it not be better to leave the larger line and give the other vfo that is always in grey and not doing much there in the background a different color to indicate it is active because in split mode? 

vy73s
Roger

**Comment by df8oe** [comment]
No. The little one is used for showing RIT difference.

vy 73
Andreas
