### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#310]
Firmware Stand vom : 24.04.2016 18:04:42

Hi,
- After "Save settings to serial EEPROM" the last "M" of the text remains visible in the Menu-screen.
- SSB transmit output power is apparently missing in tuning. Tune in CW works.
- When switching the VFO's it would be useful to save the setting of the tuning step additionally.

73, Wolfgang
DL2KI

**Comment by df8oe** [comment]
1) fixed
2) I cannot reproduce. TUNE works in SSB, too.
3) strange feature wish... Possible, but first we need more feedback if this is nedded by anyone else ;)

vy 73
Andreas

**Comment by ghost** [comment]
2) video-link comes via email.
3) Is not so important, was just an idea.

73, Wolfgang

**Comment by df8oe** [comment]
2) is reproducable now, we are working on it.

vy 73
Andreas

**Comment by df8oe** [comment]
fixed.
