### ISSUE TITLE
Band and VFO switching.

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#315]
Hi,

in both cases, it might be useful to save a fixed set of parameters, which then would be available after band- or VFO-switching again. e.g. Frequency, mode, VFO A / B, tuning step rate, DSP parameters, ...

The parameters could be determined perhaps by a small survey.

73, Wolfgang
DL2KI

**Comment by df8oe** [comment]
There _is_ already a set of fixed parameters saved! Frequency and mode are saved when you change bands or vfo and are restored when returning. It is possible to save DSP state (NR on/off, NOTCH on/off, manual NOTCH - _NOT_ DSP individual settings like strength, buffers etc.) and step size per band. Saving per vfo is not possible without pushing all users into completely loss of all settings (we will not do that).

vy 73
Andreas

**Comment by ghost** [comment]
Is not so important, was just an idea.

73, Wolfgang

**Comment by df8oe** [comment]
ok ;) Let's see. There is ONE free byte in band storing and we will decide carefully what to do with it...

vy 73
Andreas
