### ISSUE TITLE
fm mode not stored when power off/on

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#322]
when i have set a 10m fm frequency ... and power off and back on ... the mchf is then set to usb instead of fm ...

band changing does work fine (example when back on 10m it is set to fm again) ... but with power off /on it switches to usb

73

dg9bfc, sigi

**Comment by db4ple** [comment]
Yes. Fixed in #321

**Comment by df8oe** [comment]
fixed
