### ISSUE TITLE
Request: store peak filter and notch filter setting with power off

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#347]
when i have set peak filter to 700hz ... or the manual notch to any setting ... i would like to have the same setting after power off / on again ... so can we make those settings stored with power off??

73 sigi

ps: can we make the peak filter default to 700hz ???

**Comment by ghost** [comment]
Hi,

why just 700Hz?

73, Wolfgang

**Comment by DG9BFC** [comment]
many digital modes in cw mode has 700hz as default

i also have set my hdsdr offset (for cw mode only) to that 700hz

and ... many users prefer a lower tonne for cw (some even go down to 
400hz or so!!)

....

the reason for asking for 700 instead of 750 is ... cause it is a common 
value for cw offset

many conventional rig also have those 700hz as default for the cw offset

.....

now clear??

greetz

sigi dg9bfc

Am 07.05.2016 um 15:03 schrieb dl2ki:

**Comment by DG9BFC** [comment]
Thank you programmers for adding :-)
