### ISSUE TITLE
Request: AGC setting on display 

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#360]
we now have 3 values in a row ... so far so good (i like the new look ... thumbs up)
would it be posible to add agc setting in display ... (slow med fast custom and if selected custom then display the number from menue and make it changeable with encoder)

what do you think??

**Comment by db4ple** [comment]
Hi Sigi,

yes. This is possible. See comments for #361. However, we should collect ideas for use of these boxes. With the current layout up to 12 boxes are possible in future but getting more than 12 will be hard to achieve. So we should be careful here.

**Comment by DG9BFC** [comment]
12 boxes ??? ... yes then we could add agc setting

if using of noiseblanker lowers the agc value (means desensing rig) then 
selecting a faster agc does help (so sensitivity is faster back in a 
higher level) ... that is why i would like to have it on the display

....

using dsp (nr) does change the tone somewhat ... and that is why i would 
like to have bass and treble on display (permanent) ... and setting 
should be stored with power off!!!

73

sigi

Am 13.05.2016 um 06:48 schrieb db4ple:

**Comment by df8oe** [comment]
closed
