### ISSUE TITLE
Problem with Power box

### ISSUE THREAD

**Issue by DL3NCW** [df8oe/mchf-github#365]
in the daily the power box is now shown above the mode box.
If i tap the S-meter box to change from SWR to AVD and so on, 
only 1/4 of the power box is shown.

The power meter cannot be choosen anymore.

73 de Joachim, DL3NCW

**Comment by df8oe** [comment]
Thanks for your report!

Bugfix redraw meter box is published.

Power box changes automatically with s-meter box when you RX/TX -no need to show both at the same time :)

vy 73
Andreas
