### ISSUE TITLE
minus sign in bass and treble box

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#372]
if you turn bass and treble below -9 (-10, -11, etc) and turn it back higher then the minus sign is not deleted
if you go below zero but not below -9 all is well ... means turning up higher to plus the minus sigtn is deleted ... but if minus sign is one digit more on left side (turned lower as minus 9) ... then that minus sign stays in the box ... even if you then switch boxes with button below enc2 (change to dsp or nr that minus sign is still in that box (looks a bit funny if you read minus 10 or so in noise blanker or dsp box...)

**Comment by db4ple** [comment]
Fixed, please verify and close
