### ISSUE TITLE
DSP NR engaged : No fast tuning

### ISSUE THREAD

**Issue by DL3NCW** [df8oe/mchf-github#379]
While DSP is set to NR no fast tuning is possible despite the
fact that it is activated through touchscreen.

**Comment by db4ple** [comment]
Haven't tested it, but most likely the NR settings are causing to much cpu load and this causes the encoder to be queried to slowly to detect the tuning speed correctly. NR is a first class performance eater, unfortunately. There is for sure no code which  disables the dynamic tuning if NR is turn  on.
Could you please also state the version of the firmware and the type of display (SPI vs. parallel) you are using? Thank you.

**Comment by DL3NCW** [comment]
I am using daily from May 17 morning.
Display is in SPI mode.
If it is so, can't you change the step of DSP from DSP OFF - NR - DSP A-NOTCH... to
DSP OFF - DSP A-Notch - NR...
That would prevent  switching NR on if G2 button is pressed accidentialy

**Comment by DG9BFC** [comment]
seems as the programmers now switch nr off when using fast tuning (or bigger tuning steps) ...
when i tune in BIG steps (means 100kc) or have fast tune switched on (with tapping on stepsize button on the touch pad)  then nr is switched off ... and to reengange i have to turn the af gain a bit (up or down) ... turning the encoder for nr does change value in nr box but does not switch the nr function back on (if switched off by fast tune) .... only turn of af gain switches the nr function back on

**Comment by DG9BFC** [comment]
so ... we can close this issue i guess
