### ISSUE TITLE
Request: Temporary frequency  memory

### ISSUE THREAD

**Issue by dm6tt** [df8oe/mchf-github#384]
It would be nice to have a possibility to store an interesting frequency when 'scanning' the band manually. This can be done as round robin with about 10 memories places.
Pressing one button enables the temp. Memory. One encoder can be used to select the memory for reading. This functionality is similar to the TS-850 Quick memory.
I would suggest doing in band independly.
Since it is temporary it need not stored in the eeprom.

It would be very helpful to easily reach the interesting stations that were heard while scanning the bands.

73, Marcus, DM6TT

**Comment by db4ple** [comment]
The function itself is not a big deal. But have you an idea which of the existing buttons should activate this function when? This is where the fun starts...

**Comment by df8oe** [comment]
The only way to implement this in an intuitive manner is creating a touchscreen ui. If we do this we can implement much more nice features and they can be reached in a self-explaining way ;)

vy 73
Andreas

**Comment by db4ple** [comment]
To give an more or less complete overview, I added the key assignments to the Wiki page (Thanks Andreas for the initial list): https://github.com/df8oe/mchf-github/wiki/Operating-Manual

BTW, even with touchscreen: It is not endless space. But some is there, I agree.

**Comment by df8oe** [comment]
I think you can use VFO-B. Closed for now.
