### ISSUE TITLE
Daily snapshot should have it's own versioning system

### ISSUE THREAD

**Issue by Rescue9** [df8oe/mchf-github#392]
Having all daily's output mchf.bin is okay as long as there is a specific version number that shows up on boot. However, currently, this only shows the stable version number. It would be better to have download location with the bin's labeled as such mchf_daily_19-06-2016.bin in addition to the daily version number on the boot screen.

**Comment by df8oe** [comment]
I don't want to spent so much time with this so I must deny. Information about this you can find here:

https://github.com/df8oe/mchf-github/wiki/New-Firmware-and-Bootloader-Versioning-Scheme-Explanation

Much of the download links are created automated and depend on the filename "mchf.bin". I have spend much time and programmed phps to make a "one-click-download" possible not only for the German project group (where daily snaopshots are available much longer than in international group) but for international group, too. . My release of daily snapshots is automated, too. This only works when name of the file is always "mchf.bin".

So please be so kind and see it as "your donation" to live with this...
