### ISSUE TITLE
Proposals for SDR MCHF program

### ISSUE THREAD

**Issue by ly2bok** [df8oe/mchf-github#419]
Referral to the SDR MCHF programmers.

Very please take our request is not the first for the SDR MCHF software improvement and development of some functions. This is very important work aired on the machine.
The first stage
 Rx Tx USB / LSB I / Q balance by bands. This is very important and it is unclear why no one does not pay attention to it. Settings are very different and it is natural for working in different stirrers for Tx and Rx. . To all users, these numbers will be different. I give an example of what numbers I / Q is to me.

```
    RX                                                            TX
           Balansas           Fazė                                 Balansas           Fazė 
```

3,6 mHz     14                   -14                        3,6 mHz         26              -8
7,0 mHz     12                  -18                         7,0 mHz         38              -8
10 mHz        5                   -22                         10 mHz         38             -7
14 mHz       -3                   -23                         14 mHz        99 ?            -5
18 mHz       0                     -36                        18 mHz        57              -7
21 mHz        4                    -34                         21 mHz        89            -13
24 mHz       7                     -70                         24 mHz        92               6
28 mHz       -10                  -56                         28 mHz        26              24

It is obvious that these figures should be (according to the ranges and USB / LSB) stored into memory and automatically changing the ranges they are read from the EEPROM memory.
Fig. SETUP

RX I / Q (LSB) - 80m - I  -23
                                    Q -  2
                        - 40m - I  -14
                                     Q  -2,     etc.
RX I / Q (USB) -
TX I / Q (LSB) -
TX I / Q (USB) -
Second Stage.
Can not record the changes in memory setup on features dBm display OFF. This feature raises doubts as to its necessity. MCHF SDR is not a measurement device.
The third stage
Can not record the changes in memory setup on features and BAS TRB "Uncomfortable after each start to establish the.
Fourth phase.
Tx mode power "Pw" is measured by the S meter scale. Tx mode requires that it be "Pw" scale.
Fifth stage
"Scope" function to correct the signal level is displayed on the upper db grid lines.

We would be very grateful if you will implement these much-needed adjustments in the program. We wish good creative thought to the team thanks for your job.
Release for the mistakes in the letter. This is a machine translation.

With respect - LY3BD Alexander, LY2BOK Justas, LY2HT Vidmantas, LY3BFN Rimgaudas, LY3MJ Jonas LY3RD Antanas..
73!

**Comment by df8oe** [comment]
This is double of

"Request: Change storage Image rejection for mode to Image rejection for frequency"

We know this already and are thinking how to implement. Priority is not so high because worstest adjustment now is better than best before our improvement ov IQ settings - and hundreds (or thousands??) have lived without noticed that.

So please: be patient...

vy 73
Andreas
