### ISSUE TITLE
BAND+ and BAND- loose tracking after using RigControl 

### ISSUE THREAD

**Issue by steinhj** [df8oe/mchf-github#420]
mchf fw: 1.0.0
I am testing the Rig Control in CQRLOG. It works fine but:
When I use rig control to change band, the band selector on the mchf seems to loose tracking.
In ex: 
- I start the mchf and using the mchf band selector this works fine. 
- Then I stop on 14MHz
- Then I select 7MHz using Rig Control
- BAND+ gives now 18MHz.
- BAND- which should send me back from 18 to 14MHz sends me back to 7MHz. 

The 14MHz is gone from the menu. It is no way to come back to 14MHz without using the Rig Control again.

**Comment by df8oe** [comment]
Thats an operating feature...

If you don't want that CAT destroys band memory you must select in Configuration Menu "CAT Running in Sandbox - ON". Otherwise your CAT settings will be stored on the band storage place where you start CAT.

vy73
Andreas
