### ISSUE TITLE
Just for fun

### ISSUE THREAD

**Issue by PA3CCE** [df8oe/mchf-github#476]
![2 tone](https://cloud.githubusercontent.com/assets/14205041/17217764/d343f4e0-54e5-11e6-84e6-4f9d81a90824.png)
![single tone](https://cloud.githubusercontent.com/assets/14205041/17217783/e06630de-54e5-11e6-904e-56c149f40f75.png)

**Comment by DD4WH** [comment]
Your highest spur is about -50dBc. Thats not too bad, but we can do better. Please wait a few weeks, then hopefully we will have fixed. The latest preliminary version (not in github yet) has -57dBc and we would like to still improve it ;-).
73 de Frank

**Comment by PA3CCE** [comment]
OK Frank, I found these results not too bad indeed.
I'm anxious to see the results of the inprovements, but don't hurry, 
take your time.
73  de Jos

Op 28-7-2016 om 17:31 schreef DD4WH:

**Comment by DD4WH** [comment]
. . . and IMD3 of 37dBc PEP is also very good! What TX power was that?

**Comment by PA3CCE** [comment]
Op 28-7-2016 om 20:17 schreef DD4WH:

**Comment by PA3CCE** [comment]
Op 28-7-2016 om 20:17 schreef DD4WH:

**Comment by df8oe** [comment]
Nice to see.  Not sooooo bad !!

But it will get better ;)

73
Andreas

**Comment by PA3CCE** [comment]
Op 11-8-2016 om 16:35 schreef DF8OE:
