### ISSUE TITLE
Feature: Make LINEIN Channel Selection an configuration option.

### ISSUE THREAD

**Issue by hogthrob** [df8oe/mchf-github#49]
MCHF uses by default the left channel data for line in. Like in my case, the right channel would be the right channel. I would suggest to implement this as additional option in Menu 060 Mic/Line Select to be now MIC / LINE-L / LINE-R with MIC being the default. This would be 100% backward compatible but would solve my problem.

**Comment by df8oe** [comment]
Thats absolutely ok. Feature does not afect anything and maybe helps others, too.

vy 73
Andreas

**Comment by hogthrob** [comment]
Implementation is done, only issue I could imagine is the slight change in the UI interaction:
M3 long press now toggles through "MIC"-"LIN"-"L-R" since I opted to reuse the existing tx_audio_source parameter. That means you need two long press instead of one to get back to microphone. I don't know if this creates a usability issue. If so, it can be implemented with an additional  parameter which tells which line to use and you have to select the left/right in the config menu. With this switching between MIC and LINEIN and selecting the LINEIN channel would be separate choices. Both ways have its pros and cons.
