### ISSUE TITLE
Poor spectrum in Tx

### ISSUE THREAD

**Issue by PA3CCE** [df8oe/mchf-github#498]
This morning I flashed latest firmware and found poor Tx spectrum compared to previous firmware
![aug 9 2016](https://cloud.githubusercontent.com/assets/14205041/17516332/03c9dee8-5e3e-11e6-8bec-30caae644567.jpg)
![aug 7 2016](https://cloud.githubusercontent.com/assets/14205041/17516347/107fa30c-5e3e-11e6-8ef4-90d7448c4e6a.jpg)

This time I measured PA included.
vy 73
Jos

**Comment by df8oe** [comment]
Thzat was a bug - it is already fixed.

73
Andreas
