### ISSUE TITLE
tapping in dsp box "mutes" audio if dsp is engaged

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#503]
if i tap in dsp box the codec should be restarted ... and audio should work
but it does not ... audio is completely dead after tapping in tha t box
it switches to completely silence (even keybeep does not work anymore ... only power off / on does help)
that is only when nr is switched on and then tapping in the box
....
switching nr off and tapping again does not help ... (as reported only power off/on works)

greetz
sigi dg9bfc

**Comment by df8oe** [comment]
I cannot reproduce here. Everything works as expected...

**Comment by DG9BFC** [comment]
just took last daily from 12.08. ... and there the fault is gone :-) so issue closed
