### ISSUE TITLE
I Q MODE does not work anymore!!!!

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#505]
i tested backwards the different versions
and from 1.1.3 upwards the iq mode does not work anymore
there is a bad hum noise added (changing sound every few seconds)
1.1.2 is fine
1.1.3 and 1.1.4 have that bad noise added
greetz sigi dg9bfc

**Comment by db4ple** [comment]
You're right, there is an issue. Found source, will fix it soon.

**Comment by DG9BFC** [comment]
issue fixed ... iq mode now is back to normal
that was fast :-)
tnx de dg9bfc sigi
