### ISSUE TITLE
Menu Item 230

### ISSUE THREAD

**Issue by GeorgeG4ONV** [df8oe/mchf-github#52]
Hello Andreas,

Menu 230 Calibrate has too high a step value.

73
George G4ONV

**Comment by df8oe** [comment]
Hello George,

please set step with "STEP+" and "STEP-" buttons.

vy 73
Andreas

**Comment by GeorgeG4ONV** [comment]
Thanks Andreas,

Great additions/Mods to the software.

George.

**Comment by df8oe** [comment]
Tnx for your feedback!

Please feel free to test and report any bug you found. In this case here it is a bug "not in the manual".

I will look in Yahoo-NG for eople who will help to actualize operators manual from Clint. Meanwhile there are many new features badly documented :(

vy 73
Andreas
