### ISSUE TITLE
tapping in am mode on display rounds to next 5kc value but in sync am it does not

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#521]
when i tune around listening to normal bc stations the tapping on a signal and round to next 5 kc value does work in am ... superb to jump to next station
but it should also do that in sync am (snap grid to 5kc stepping) ... but there it does not
,,, so please could you also add that function to sync am??
greetz
sigi dg9bfc

**Comment by df8oe** [comment]
I will implement that next hours.

**Comment by df8oe** [comment]
finished.
