### ISSUE TITLE
Build In Antenna Analyser

### ISSUE THREAD

**Issue by DK8XK** [df8oe/mchf-github#550]
As can be seen at the Arduino Project "K6BEZ Antenna Analyser" a simple swr chart is a helpful piece. All the hardware needed is already on board. So I like to suggest to have at "TUNE" a swr-chart on the waterfall's place. The selected band can be shown or a adjustable range around the actual. Maybe automatically display the best-swr-frequency and the current with vertical lines. Tuning the antenna at remote places might be easier instead of having only the bar. 
vy de Willi_DK8XK

German reading hams may have a look here:
http://www.dg7eao.de/arduino/antennen-analysator/
http://www.dk2jk.darc.de/vna_dk2jk/dokumentation/13dez2014/antennen_analyser_Baumappe%20v2.pdf
http://www.kh-gps.de/ant_analyzer.htm
http://www.dj7jc.de/doc/Antennentag2014.pdf

**Comment by df8oe** [comment]
I don't think we will do that.
mcHF needs tx power >=5W to show some reliable SWR (BTW: I think it is not reliable at all...) It is not ok to tune with 5W across the bands just for getting a SWR of an antenna.

Better way is to use equipment with integrated amplifiers where tx power is reduced much (<= 50mW) like SARK100.
