### ISSUE TITLE
HW Info, RAM

### ISSUE THREAD

**Issue by dm6tt** [df8oe/mchf-github#563]
I swirched the processor to the recommended 2MB flash / 256 KB model.
The HW info shows:
CPU: 419h
Flash: 2048
RAM: 0

There is a problem with recognizing the 256kB.

73, Marcus, DM6TT

**Comment by db4ple** [comment]
Hello Marcus,

thanks for reporting. Good news is, the recognition of RAM size works, only the display of information doesn't. We'll have to fix that. Should not be a big deal but may take some time.

73, Danilo

**Comment by db4ple** [comment]
Please verify that next  daily build works for you. Should fix the issue. In this close, any other case please report.
Thank you, Danilo

**Comment by dm6tt** [comment]
Hi Danilo,
just check the daily build. The RAM is now displayed correctly with 256K.

Thanks a lot

Marcus
