### ISSUE TITLE
Build failed for testing.

### ISSUE THREAD

**Issue by imoldovavan** [df8oe/mchf-github#58]
I was able to compile the master, but testing gives me this error:

       [cc] C:\Users\ionut\Documents\GitStuff\df8oe\mchf-eclipse\usb\otg\src\usb_otg.c: In function 'USB_OTG_HandleConnectorIDStatusChange_ISR':
       [cc] C:\Users\ionut\Documents\GitStuff\df8oe\mchf-eclipse\usb\otg\src\usb_otg.c:285:9: error: 'USB_OTG_CORE_HANDLE' has no member named 'otg'
       [cc] C:\Users\ionut\Documents\GitStuff\df8oe\mchf-eclipse\usb\otg\src\usb_otg.c:292:9: error: 'USB_OTG_CORE_HANDLE' has no member named 'otg'
       [cc] C:\Users\ionut\Documents\GitStuff\df8oe\mchf-eclipse\usb\otg\src\usb_otg.c: In function 'USB_OTG_GetCurrentState':
       [cc] C:\Users\ionut\Documents\GitStuff\df8oe\mchf-eclipse\usb\otg\src\usb_otg.c:402:14: error: 'USB_OTG_CORE_HANDLE' has no member named 'otg'
       [cc] C:\Users\ionut\Documents\GitStuff\df8oe\mchf-eclipse\usb\otg\src\usb_otg.c:403:1: warning: control reaches end of non-void function [-Wreturn-type]

BUILD FAILED
Total time: 21 seconds

using coocox 1.7.8 and 4.7 troolchain.

73's
de KC8CDQ

**Comment by df8oe** [comment]
At this time eclipse and CooCox configuration in "testing" is broken (works in master and devel) - it will be fixed next testing version. You can fix it by yourself in excluding mchf-eclipse\usb\otg\src\usb_otg.c from building.

vy 73
Andreas
