### ISSUE TITLE
FreeDV: Button and touch use different sidebands

### ISSUE THREAD

**Issue by dm6tt** [df8oe/mchf-github#594]
I just tested the new FW from today 06.10.2016 16:10:20.
- 40m band (7.190)
- switching with Mode-button to DI-U (DI-L does not appear)
  --> Upper sideband is used (due to waterfall)
- choosing LSB
- switching via touch panel to FreeDV
  ---> LSB is used

73, Marcus, DM6TT

**Comment by db4ple** [comment]
Try to press the Mode button  a little longer. This will switch sidebands.

73
Danilo

**Comment by dm6tt** [comment]
Thanks.
