### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by oz8gw** [df8oe/mchf-github#596]
In the new version FW the choise of digital mode is not saved when closing down.
Vy 73 de OZ8GW, Leif.

**Comment by db4ple** [comment]
Hi,

thanks for report. 

We'll fix that. There is now a separate mode available called Digital (multiple short presses of Mode). If you use this mode, it is remembered even after switching of. It does not remember the sideband it was in, though. We'll have to do that, too.

Thanks again for the feedback 👍 

Danilo

**Comment by df8oe** [comment]
closed
