### ISSUE TITLE
HRD soft control error.

### ISSUE THREAD

**Issue by BI3MEK** [df8oe/mchf-github#598]
i use the HamRadioDeluxe software to control the machine, when LSB (USB, AM) change to FM mode, return LSB (USB, AM) mode, the machine is mute, adjust the volume is invalid.

**Comment by db4ple** [comment]
Hi,

please help us with some additional information:

Version  (git commit id) are you using: ?
Version (git commit id( you first experienced the problem with?
Did you build the firmware by yourself?
How to reproduce? -> Is there anything else to do in addition to your description to reproduce the error?
Does this always happen if we follow the instructions for reproducing the problem or does it happen only sometimes?

Thank you!

**Comment by BI3MEK** [comment]
I use firmware1.31.
Download from this website.
 HamRadioDeluxe ver 7.2
using FT-817 protcol.
 reproduce:
1.LSB
2.FM
![1111](https://cloud.githubusercontent.com/assets/18715486/19241705/73212eba-8f42-11e6-9df6-8db75a7e75d1.png)

the machine is mute, adjust the volume is invalid.

**Comment by db4ple** [comment]
Thank you for the quick answer. We will look into this. First step will be to reproduce the issue (I will not be able to do this until mid of this week).

**Comment by df8oe** [comment]
I do not have HRD (because of I am running LINUX). But I have tested with flrig and fldigi.

I can toggle all modes - audio is always present. Of course if FM is choosen, squelch is active so no audio to hear. But if I change back to any other mode audio is present. This is normal behaviour...

**Comment by df8oe** [comment]
Additional information: the second encoder is "sql" in FM...

**Comment by BI3MEK** [comment]
Sorry, this problem is tested again today, reset the HRD settings, and no more errors.

73
