### ISSUE TITLE
pse add tuning indicator (if possible) for freedv

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#611]
is it possible to add a tuning helper for freedv???  cause you do not hear anything when not tuned to correct qrg you also do not know if you are right on the qrg that the other uses
would it be possible that you have a visual helper ?? (tuning aid)
i do not mean an afc function ... but maybe soft can tell mistunig (an arrow to left and right) and a "tuned" indicator

**Comment by df8oe** [comment]
There is no possibility actually. And additional: no need.... You can see signal in spectrum / waterfall and adjust "by viewing". FDV can correct +/- 75 Hz.
