### ISSUE TITLE
Eprom not detected/recognized

### ISSUE THREAD

**Issue by inlinerbutch** [df8oe/mchf-github#675]
With Daily build from 28.12.2016 15:00:30 is my Eprom not detected/recognized (Wrong Signatur/OB)

In FW 1.5.3 it was working perfectly.

**Comment by db4ple** [comment]
Reverted increased speed back to original (very slow settings). Please report what HW you are using and if the boards are connected via longer than normal wires. Or if you did any modifications on I2C side.

Next build should work for you again.

Thanks,
Danilo

**Comment by inlinerbutch** [comment]
I am using the MICROCHIP  24LC1026-I/SM  EEPROM, AEC-Q100, Seriell I2C, 1 Mbit, 128K x 8 bit, 400 kHz, SOIJ chip (Farnell 1971897). I don't have any modification on I2C side or long wires. Let me know please if it is better to replace it. I will test the daily and give you feedback.

Cheers,
Uwe

**Comment by inlinerbutch** [comment]
I have tested the daily 29.12.2016 08:49:59 and the Eeprom is detected again. Please advise if it better to use a different part instead of the upon listed Eeprom.

Cheers,
Uwe

**Comment by db4ple** [comment]
Hi Uwe,
no, I2C EEPROM is fine. We tested with higher I2C Speeds and it turns out the I2C resistors are too high for the higher speeds.  Stay tuned.

73
Danilo

**Comment by df8oe** [comment]
Problem is a hardware design error. The two pullup resistors R6 and R7 for I2C-bus 2 are too high. Please fit 1K instead of 4K7 and try next daily build which has enabled high I2C-speed again. Using 4K7 makes it impossible to use higher I2C speed.

73
Andreas

**Comment by inlinerbutch** [comment]
I am fine with this solution. Please add this mod (recommendation) to the list on your modification side.

Cheers,
Uwe

**Comment by df8oe** [comment]
We were experimenting at the moment. If neccessary, we wil add this of course. Actual builds are working without modifications increasing EEPROM and audio codec I2C speed x 8

73
Andreas
