### ISSUE TITLE
store step size and mode for each band automatically

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#731]
not a must have, but it would be a nice feature to store automatically the last step size (e.g. 100Hz, 1kHz, 10kHz...) and the last mode (e.g. USB, LSB, SAM-L....) for each band separate
thx
Thomas

**Comment by df8oe** [comment]
Mode is already stored for each band (it is stored DÒUBLE - for each VFO seperate...)

Step size does not make any sense - I think. It is not specific to band than to my condition (do I want to tune whole band / do I want to fine tune to station). So please explain what advantage there is when I store it band specific - I do not see that...

**Comment by db4ple** [comment]
Mode is stored, sideband is not (except USB/LSB which are two modes technically).

**Comment by DG9BFC** [comment]
step size makes sense if you use one mode with a bigger step size (example fm or am) while you prefer smaller steps in other modes (ssb or cw) so ... it would be nice if step size would be stored to the used mode
switch from am (5kc) to cw and automagically step size changes to (example) 100hz ... change band to 10m (and fm mode) and step size changes to 10 kc
if you change from a wideband mode to a narrower mode then also step size change ... i think that is not a bad idea
