### ISSUE TITLE
It would be nice to have snap button can snap CW signals, too...

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#737]
I think it would be nice to use the snap button to snap a CW signal to match your ST tone. This is the same function that the Auto Tune button on the IC-7600.

Thanks,
 Chuck WD8BXS

**Comment by db4ple** [comment]
Please rename the enhancement to indicate the enhancement asked for...

**Comment by WD8BXS** [comment]
I guess this should be named auto tune for CW, so when you hit the button it would automaitcally tune the signal to your peak CW tune frequency.

**Comment by roelandjansen** [comment]
remove the "guess" part -- it indeed is autotune. It also could be aplied to AM. Just like the Icom TRX we know.

**Comment by df8oe** [comment]
I have tried - does not work as expected. This only works if there is no sronger signal in the neigbourhood of the signal you want to snap on. Trying on band with normal CW activities it snaps mostly to the "wrong" signal so it is much better to do this manually.
