### ISSUE TITLE
curious signs where earlier the band was displayed

### ISSUE THREAD

**Issue by HB9LFU** [df8oe/mchf-github#742]
![mchf strange signs](https://cloud.githubusercontent.com/assets/17696364/21928773/0207db4e-d98d-11e6-8049-c8d6c4e02d6d.jpg)

the last about three firmware releases produce this strange box.

vy73s
Roger

**Comment by df8oe** [comment]
What kind of LCD do you use (SPI / parallel, 2.8 / 3.2)? What kind of dBm display is activated?

vy 73
Andreas

**Comment by HB9LFU** [comment]
Andreas, I use the small display in parallel mode! Dbm display is off. And s-meter is based on dBm. The moment I switch from s-meter based on dBm to s-meter old school style. The bug is gone.

vy73s
Roger

>
> What kind of LCD do you use (SPI / parallel, 2.8 / 3.2)?
>
> vy 73
> Andreas
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Erstellt mit Operas revolutionärem E-Mail-Modul: http://www.opera.com/mail/

**Comment by df8oe** [comment]
Hi Roger,

I think your configuration was slightly damaged and by setting dBm display to a defined state all was ok...

I don't think we must leave this open (if its not reproducable)...

73 de
Andreas
