### ISSUE TITLE
Odd ASCII symbols flashing by 

### ISSUE THREAD

**Issue by Haasoperator** [df8oe/mchf-github#746]
On the latest daily snapshot (and 1.5.6), ASCII symbols keep flashing by on the blue colored bar next to the bar that shows what output power the radio is set for. WHen I switch from "Scope" to "waterfall", the symbols freeze, but are still there. If I switch back to "Scope", the symbols start flashing by again. Also, when I try to scroll through the bands using the "band+" button, eventually it says "mm" instead of "m" after the band number.

**Comment by db4ple** [comment]
Strange symbols: Will be fixed in the next daily
However, the "m" issue should not have appeared in the recent daily builds only in 1.5.6 . Please confirm.

**Comment by df8oe** [comment]
This is a duplicate of [#742](https://github.com/df8oe/mchf-github/issues/742)

Please try and report.

73
Andreas

**Comment by db4ple** [comment]
As I said, it is a bug. This happens if you had new style S meter (dbm or dbmhz) but not enabled the numeric display of Dbm or dbmhz.

**Comment by db4ple** [comment]
Please close issue, if it does no longer appear with daily builds.
Thank you!

**Comment by Haasoperator** [comment]
Loaded the daily build with yesterday's date. Does not appear to have odd symbols or the "mm" problem.
