### ISSUE TITLE
Problems LCD

### ISSUE THREAD

**Issue by AngelSerra** [df8oe/mchf-github#748]
It's already the third LCD I put and I always have the screen blank.
My configuration is MI2 and MI0 placed resistance sms in as it indicates the lcd plate and the file found in yahoo M0NKA HY28B display.jpg, I asked in yahoo M0NKA that configuration is the correct one for touch screen but I have not found possible solution, they told me that MI2 alone.
How I put them Cutting the printed circuit of the lcd near the pins because neither with desoldador of hot air exits the LCD.

**Comment by df8oe** [comment]
Do you want to run LCD in parallel or SPI mode?

**Comment by AngelSerra** [comment]
Which would be better of the two configurations?

**Comment by df8oe** [comment]
SPI. It is the one which does not waste GPIOs and the first modification which depends on LCD in SPI mode is already out: "acivating real time clock of STM32" :)

Jumpers on LCD are IM0 and IM1 set. You have to do modification for running LCD in SPI mode.

**Comment by DG9BFC** [comment]
and here we see it again why not to solder the lcd :-)

**Comment by df8oe** [comment]
Good luck! It is a *very good idea* NOT to solder LCD but put it on heaaders...
