### ISSUE TITLE
RF Gain & Signal meter

### ISSUE THREAD

**Issue by g7jiq** [df8oe/mchf-github#756]
Signal meter and spectrum scope doesn't react to RF gain level.
Signal meter also seems to be at constant high or very low depending on menu setting, RX signal shows very little change on RX station strenght.

**Comment by df8oe** [comment]
This must be a hardware related problem or result of a damaged configuration - not a general firmware issue. Could you please test if resetting configuration to default solves your problem?

73 de
Andreas

**Comment by g7jiq** [comment]
Thankyou for your reply,
I will do that and get back to you.

**Comment by df8oe** [comment]
If it is ok now please close this issue.
