### ISSUE TITLE
DTR for CW carier

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#773]
Wow, this looks like a great add, I do not get it to work in fldigi, Where exactly do I set it up in the fldigi?
I have selected DTR for PTT but no luch.

Thanks,
 de Chuck WD8BXS

**Comment by db4ple** [comment]
Hi,
it is NOT PTT via DTR it is CW Key via DTR, PTT is still only FT-817 CAT. The DTR line can be used like a straight key in order to enable / disable carrier (when TX was enabled by CAT PTT command).

**Comment by WD8BXS** [comment]
I do not understand, Is this something that can be used in fldigi to send CW with the rig in CW mode? Here is a pic of my screen, I see no where to address what yo are talking about.
![rigcat](https://cloud.githubusercontent.com/assets/25059155/22618901/a0f0e5f4-eab6-11e6-9f17-0f01de4ce2d9.jpg)

**Comment by db4ple** [comment]
I have no idea how fldigi does CW. I have also no clue how rigcat works, never used it, only Hamlib. 
The request is based on the problem to get UCXLOG to work, not fldigi. 

BTW, in the current daily this function does not work at all correctly.

**Comment by df8oe** [comment]
It is not a neccessary feature for most external software. Normally you can control mcHF via CAT commands (this works for SSB and CW). The best choice is to use "only CAT commands".

Helpers like "PTT via RTS" or "DTR" are from many years ago when CAT does not support switching PTT or doing CW via CAT.

73 de
Andreas

**Comment by dm6tt** [comment]
As much as I know fldigi uses the right audio channel with a 1600Hz tone to do cw-keying.
http://www.w1hkj.com/FldigiHelp-3.21/html/cw_keying_page.html

**Comment by DG9BFC** [comment]
ptt via rts would be a nice add on for digital mdes software that can not cntrol ptt via cat command
then any software that can toggle rts can be used with mchf

**Comment by df8oe** [comment]
If it is ok now please close this issue.
