### ISSUE TITLE
AM filter bw

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#79]
If you select 5 kc am in menue ... then pressing long on filter bw button gives you the narrow cw filters (that are useless in receiving am cause we already have narrow am filters and the cw filters are too narrow)

could a longer press sswitch to WIDER am filter instead (7.5 and 10) ??

some radio stations transmit in wideband with more high tones ... (hifi am ... grin) ... and with a long press we then could swittch to wideband am filter (maybe also useful on 10m fm wide/narrow but that would be a different story)

**Comment by df8oe** [comment]
Filter selection will be modified completely in the next days so this function is obsolete.

vy 73
Andreas
