### ISSUE TITLE
TX Audio Compress setting

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#815]
if i go in menue to tx audio compress and turn it upwards to custom and then back down the "cu" is still shown (only cosmetic thing)
seems as you have to replace the number against some spacers with number

x (where x is the setting)
has to be replaced against
_______x (so the spaces overwrite the cu at the beginning of the word custom)

**Comment by df8oe** [comment]
please check and close if solved...

**Comment by DG9BFC** [comment]
solved :-)
