### ISSUE TITLE
idea RTC via I2c module?

### ISSUE THREAD

**Issue by AngelSerra** [df8oe/mchf-github#822]
Can the RTC be implemented via i2c?. For example the module that is used in arduino, chip use DS1302, DS1307 or modern DS3231 with eeprom at24c32, that only one would have to read the address of the eeprom since it is kept the hour the day the month the year the day of the week,to reduce the noise of the i2c the cpu would only read for a certain time the eeprom address alone, few modifications would be needed on the board to implement this type of rtc as it has battery and the mchf off the rtc would still work with just a simple reading When closing the mchf.

**Comment by db4ple** [comment]
Hi,
of course, you can do that, but why, if you just need to follow this mod:

https://github.com/df8oe/mchf-github/wiki/Recommended-Modifications#ui-0405-n-031-enable-stm32-real-time-clock

**Comment by df8oe** [comment]
I see same way. We already have a very good running solution included software correction . So there is absolutely no need to implement new ones. BTW: the EEPROM which is present on this modules do disturb existing EEPROM on mcHF so you have to modify the modules....

**Comment by s53dz** [comment]
I fully agree. The RTC as implemented here using an internal STM's RTC works really good. I do not miss any other function here.

**Comment by AngelSerra** [comment]
Yes, via software only no backup batery

**Comment by df8oe** [comment]
?? No backup battery? What are you talking about??

**Comment by db4ple** [comment]
The implemented STM32 RTC is using the RTC hardware inside the STM32 and a battery as described in the link I provided. It runs 100% independent from the firmware (same as it would be with an separate i2c module) AND it needs a battery, just like the external module.
And as Andreas pointed out, the modules with I2C EEPROM are not good at all, due the the EEPROM possible interferring with the existing one (if the RTC is connected to the same I2C bus).      
Please read the description of the mod again and get back if you have questions.

Thank you!
