### ISSUE TITLE
Compression overboosts silence

### ISSUE THREAD

**Issue by gerryk** [df8oe/mchf-github#823]
When compression values are set high (>6), silence or ambient noise is boosted to very high levels.
Perhaps some gating of audio levels below some threshold would be useful.
This would involve an additional configuration parameter (silence threshold) and some code added to audio_driver.c to squash audio levels that fall below this threshold.

**Comment by df8oe** [comment]
Each gating will result in distortion because it is unlinear behaviour. Try to reduce microphone gain and everything will work well ;)
