### ISSUE TITLE
TouchScreen reverse can not save.

### ISSUE THREAD

**Issue by BI3MEK** [df8oe/mchf-github#845]
bootloader 3.2
fw 2.2

73

**Comment by df8oe** [comment]
I cannot confirm. Works for me (using serial EEPROM). Do you have installed serial EEPROM?

73

**Comment by BI3MEK** [comment]
I use 24cm01

**Comment by db4ple** [comment]
Hi,
how did you find out that the reverse is not saved? Key Test Screen?

**Comment by BI3MEK** [comment]
1. Set “Reverse Touchscreen”  ON
2. Touch normal
3. Press the POWER button to turn off the machine
4. Turn on
5. “Reverse Touchscreen” display ON,but Touch screen the x direction to reverse.


73

**Comment by db4ple** [comment]
Thanks, that helps. Other settings such as receive frequencies are stored at power off (and restored when starting)?

**Comment by BI3MEK** [comment]
Other settings are normal。

**Comment by db4ple** [comment]
Hi,
I'll attach a new firmware binary to this comment. Please try this. Should fix the problem (if I am right, that is).

[mchf.zip](https://github.com/df8oe/mchf-github/files/870820/mchf.zip)

**Comment by BI3MEK** [comment]
ok!!The problem fixed. thank you!

73

**Comment by db4ple** [comment]
Ok, will push this fix to the repository and it will appear in the next firmware builds.
Thank you for reporting the issue!

**Comment by BI3MEK** [comment]
I will close this issue.
