### ISSUE TITLE
MChf error

### ISSUE THREAD

**Issue by oz9hi** [df8oe/mchf-github#860]
mchf issue 4 problem?
Transmitter dont Work while the codex  output from the mic. (Lout and Rout) not let it out.
Setup the power is not possible, you cant change the numbers.
Processer and codex are replaced.
I hope you can help me.

BR Jorgen oz9hi

**Comment by df8oe** [comment]
This cannot be a bug because of hundreds other mcHFs do work properly. So it is an operational problem.

Please try first adjusting power using "TUNE" function. Values can only be changed at TX on specific band in specific power! Normally they are "not changeable". Adjust all power settings for every band in FULL and 5W position.

**Comment by oz9hi** [comment]
Thanks for quick answer
As mensient  it is not possible to chance the power numbers, its lockt
BR Jorgen

**Comment by oz9hi** [comment]
By the way the TUNE button when prest is red

**Comment by df8oe** [comment]
Cannot confirm. Nothing is "locked" :)

So step by step:

1) switch to 80m and tune to a frequency within allowed frequency range (mcHF only transmits in ham bands)
2) set mode to LSB or CW
3) set power to "FULL" using button G3
4) in PA CONFIGURATION set "Tune Power Level" to "as TX PWR"
5) now in PA CONFIGURATION select "80m Full PWR Adjust" (the number is WHITE)
6) now press short "TUNE" and adjust power level

I just tested at my mcHF - is working properly.

**Comment by oz9hi** [comment]
Thanks its ok now
Next problem
Noisereduction on, transmitter on and of, - an 3v signal from codex LHPout to speaker amp, and no more sound. Reset and all is ok Again.
I think its a known failure, what do you mean?

Thanks for your help
73 oz9hi@io.dk 
Jorgen

**Comment by df8oe** [comment]
Yes its a known problem. NB is eating so much horse power that mcHF sometimes stops working. Also it does not reduce noise, so do not use it :)
