### ISSUE TITLE
FM and Freq xlate BUG

### ISSUE THREAD

**Issue by BI3MEK** [df8oe/mchf-github#867]
1.Turn on
2.change RX/TX Freq Xlate to RX -12KHZ
3. changr FM MODE to ON
4. change mode to FM
5.change RX/TX Freq Xlate to "OFF!"
6.the machine mute,change mode to ssb,cw,am mute too!

**Comment by df8oe** [comment]
Thank you!

Am and FM are modes that are only possible in Xlate mode - that is mathamaticla law. It should be impossible to switch Xlate OFF when you are using AM or FM. That is a bug! Of course system completely crashes if it is possible to switch it off :)

Will be fixed ASAP.

73
Andreas

**Comment by df8oe** [comment]
This bug is fixed in our neweset daily snapshot.

Thanks for your contribution!
