### ISSUE TITLE
missing links to images on the DSP wiki page

### ISSUE THREAD

**Issue by k3it** [df8oe/mchf-github#871]
two links to hilbert filter imgs appear to be broken in 
https://github.com/df8oe/mchf-github/wiki/How-does-your-mcHF-software-DSP-work

`https://github.com/DD4WH/mchf-github/raw/active-devel/mchf-eclipse/useful_manuals/Hilbert%203k6%20mcHF%20old.png
`
and 

`https://github.com/DD4WH/mchf-github/raw/active-devel/mchf-eclipse/useful_manuals/Hilbert%203k6%20mcHF%20new.png`

**Comment by DD4WH** [comment]
Hi!
thanks for the hint!
I uploaded them again. I hope it works now and the figures are there . . .
73 de Frank DD4WH

**Comment by k3it** [comment]
Looks good now. Thank you for a nice article!
