### ISSUE TITLE
 dmod_mode  vary (uchar,uint8_t,uint16_t,uint32_t)

### ISSUE THREAD

**Issue by AsbjornPettersen** [df8oe/mchf-github#875]
I'm looking into cat_driver.c and i see these variables:

void CatDriver_HandleProtocol()
{
 ..
  uint32_t new_mode = ts.dmod_mode;
  uint32_t new_lsb = ts.cw_lsb;
-----------
should be:
  uint8_t new_mode = ts.dmod_mode;
  bool new_lsb = ts.cw_lsb;
}

The define of ts.dmod_mode variable/parameter seems to vary a lot:   

Usage of dmod_mode (uchar,uint8_t,uint16_t,uint32_t):

In struct TransceiverState:
uchar 	dmod_mode;

void AudioDriver_TxFilterInit(uint8_t dmod_mode)
void AudioDriver_SetRxAudioProcessing(uint8_t dmod_mode, bool reset_dsp_nr)
void RadioManagement_SetDemodMode(uint32_t new_mode)
void AudioManagement_SetSidetoneForDemodMode(uint16_t dmod_mode, bool tune_mode)

The uint16_t dmod_mode parameter for AudioManagement_SetSidetoneForDemodMode() looks
like it was designed for ts.demod_mode_disable (but it isn't) :
uint16_t	demod_mode_disable;  /* bit flags !! */

My Suggestion for dmod_mode:
uint8_t 	dmod_mode;  /* 0..6 */
void AudioDriver_TxFilterInit(uint8_t dmod_mode)
void AudioDriver_SetRxAudioProcessing(uint8_t dmod_mode, bool reset_dsp_nr)
void RadioManagement_SetDemodMode(uint8_t new_mode)
void AudioManagement_SetSidetoneForDemodMode(uint8_t dmod_mode, bool tune_mode)

**Comment by db4ple** [comment]
Hi Asbjorn,
please close. Is fixed now.
