### ISSUE TITLE
Dynamic tuning

### ISSUE THREAD

**Issue by n5mf** [df8oe/mchf-github#883]
Is it possible to add a menu item to activate the Dynamic Tuning for those who dont have a touchscreen?

Thanks

Mark
N5MF

**Comment by df8oe** [comment]
A would be a very good idea to add touchscreen because you get much more functionality... mcHF *is a touchscreen radio*! Or would you use a plane without wings? ;)

73
Andreas

**Comment by n5mf** [comment]
Actually, as an air traffic controller i wouldnt advise that.  However,  i think my screen is defective and since it is soldered in i really didnt want to remove it and risk damaging the board since everything else works perfectly. 
Mark


Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: DF8OE <notifications@github.com> Date: 5/25/17  10:24 AM  (GMT-07:00) To: df8oe/mchf-github <mchf-github@noreply.github.com> Cc: n5mf <n5mf@dfn.com>, Author <author@noreply.github.com> Subject: Re: [df8oe/mchf-github] Dynamic tuning (#883) 
A would be a very good idea to add touchscreen because you get much more functionality... mcHF is a touchscreen radio! Or would you use a plane without wings? ;)
73

Andreas

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/df8oe/mchf-github","title":"df8oe/mchf-github","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/df8oe/mchf-github"}},"updates":{"snippets":[{"icon":"PERSON","message":"@df8oe in #883: A would be a very good idea to add touchscreen because you get much more functionality... mcHF *is a touchscreen radio*! Or would you use a plane without wings? ;)\r\n\r\n73\r\nAndreas"}],"action":{"name":"View Issue","url":"https://github.com/df8oe/mchf-github/issues/883#issuecomment-304054519"}}}
