### ISSUE TITLE
EmBitz build error

### ISSUE THREAD

**Issue by AsbjornPettersen** [df8oe/mchf-github#892]
The EmBitz system wont build with latest code:

Here is my local patches to get it working again:

bootloader.ebp 

1 Remove:
  ..\mchf-eclipse\basesw\mcHF\Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Src\usbd_cdc.c
  ..\mchf-eclipse\basesw\mcHF\Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Src\usbd_cdc_if_template.c
  ..\mchf-eclipse\basesw\mcHF\Src\usb_device.c
  ..\mchf-eclipse\basesw\mcHF\Src\usb_host.c
  ..\mchf-eclipse\basesw\mcHF\Src\usbd_cdc_if.c
  ..\mchf-eclipse\basesw\mcHF\Src\usbd_conf.c
  ..\mchf-eclipse\basesw\mcHF\Src\usbd_desc.c

2 Add:
 ..\mchf-eclipse\drivers\usb\app\usbd_desc.c

mchf.ebp

1 Remove
 ..\mchf-eclipse\basesw\mcHF\Middlewares\ST\STM32_USB_Device_Library\Class\AUDIO\Src\usbd_audio_cdc_comp.c
 ..\mchf-eclipse\basesw\mcHF\Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Src\usbd_cdc.c
 ..\mchf-eclipse\basesw\mcHF\Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Src\usbd_cdc_if_template.c

 ..\mchf-eclipse\basesw\mcHF\Src\usb_device.c
 ..\mchf-eclipse\basesw\mcHF\Src\usbd_cdc_if.c
 ..\mchf-eclipse\basesw\mcHF\Src\usbd_desc.c
 ..\mchf-eclipse\basesw\mcHF\Src\usbd_audio_if.c

2 Add directory
..\mchf-eclipse\drivers\usb\device\class\AUDIO\Inc

**Comment by db4ple** [comment]
Pull Request, please.
