### ISSUE TITLE
CW memories and CW keyboard

### ISSUE THREAD

**Issue by ok1cdj** [df8oe/mchf-github#921]
It will be nice to have some memories for CW operation. Record memory from paddle or (i don't know if it is possible) connect usb keyboard to mcHF for  memory editing. Also send CW from keyboard will nice feature.

73 Ondra OK1CDJ

**Comment by df8oe** [comment]
This is a far-in-future-feature. It is a "nice to have" of course. But not simple at all and takes much time and man-power. Its priority is not so high - but it is now on the wish-list :)

73
Andreas, DF8OE

**Comment by pa7n** [comment]
Andreas,
Would CW memory without a keyboard easier to implement? Instead of the keyboard you could just dial in the characters with the encoder knobs. Not as easy as with a keyboard but workable I think.

73,
Erwin PA7N

**Comment by df8oe** [comment]
It is much work, too. If we implement selecting characters via ancoders we have to implement selecting characters via touchscreen, too (it is much more comfortable than using encoders). I think it is nearly the same R&D so better wait until USB activation using keyboard will bei implemented. That is perfect solution. Or start it by yourself - it is already on 2do list.

73, Andreas

**Comment by pa7n** [comment]
A qwerty keyboard on the touchscreen :) That would be fun!

**Comment by ok1cdj** [comment]
Insert memory by  encoders is also ok for me. You don't need change it very often.
I am not fan of touch screen and i have no touch screen in my 0.4.

73 Ondra

**Comment by df8oe** [comment]
Hi Ondra,

you may think so about touchscreen - but we must look at all users! And many users like touchscreen very much (included me). It makes many operations very intuitive, fast and simple and mcHF would not be the same radio when there is no touchscreen... So encoders is bundled with touchscreen. Or support via USB-Keyboard or USB Key (textfile).

73
Andreas

**Comment by ok1cdj** [comment]
Hi Andreas USB key is also nice idea...

**Comment by phaethon** [comment]
@ok1cdj have you checked out the cw keyer functionality committed lately? See description at the end of Digimodes section in the wiki: https://github.com/df8oe/UHSDR/wiki/Digimodes
