### ISSUE TITLE
green led

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#946]
works as rx indikation .. so far so good
would it be possible to add "squelch" additionally to the green led??
means if sq is closed green led is off ... if sq is open then led is on
in all other modes as fm then the led would be steady on  in rx (cause we do only have sq in fm mode)

if we later add squelch to the other modes (like ssb and cw) ... then we would have already the sq function to the led added

**Comment by df8oe** [comment]
So if you have switched off LCD and squelch is closed you cannot see if radio is on or off.... I do not think this is a good idea.
