### ISSUE TITLE
band freq define error

### ISSUE THREAD

**Issue by power3000** [df8oe/mchf-github#959]
File: https://github.com/df8oe/UHSDR/blob/active-devel/mchf-eclipse/hardware/uhsdr_board.h

from line 248 , as the following:
	//
#define	BAND_MODE_23			13
#define	BAND_FREQ_23			450000*KHZ_MULT		// 1240000 kHz
#define	BAND_SIZE_23			10000*KHZ_MULT		// 60000 kHz in size (Region 1)

**Comment by df8oe** [comment]
This is unused for mcHF and will be forever unused. If there are other hardware platforms that will support it all defines will be reworked.

73
Andreas

**Comment by power3000** [comment]
ok, I see, thanks for your quick reply！

73
bg5uer
