### ISSUE TITLE
Back up config question

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#960]
I would be neat to be able to back up and restore you configuration settings to thumb drive.

Chuck

**Comment by df8oe** [comment]
Hi Chuck,

this is already on our todo list.

73
Andreas

**Comment by WD8BXS** [comment]
Thanks Andreas,

Also I have one here on the bench, that has a crackling from the speaker and I see the S meter scale flashing red a lot, but not on another rig I have here.

Any ideas?

Chuck

**Comment by df8oe** [comment]
There can be many reasons. It is located in audio path from I2S-stream input to STM32 to rx preamp. It can be a bad soldering or a malfunctioning semiconductor (audio codec, operational amp, rx mixer) and can also be in the LO input section of rx mixer. There is no possibility to guess something out of that bunch.

Andreas

**Comment by WD8BXS** [comment]
Noticing that this receiver is also showing much higher receive signals that the other one, I put the receive gain to 30 and they match there, but still getting the red scale and 
it sounds like there is a storm outside with static like crashes.

Strange that it would be so much more sensitive.
Chuck

**Comment by WD8BXS** [comment]
Thanks
