### ISSUE TITLE
Saving and Loading Configuration from USB

### ISSUE THREAD

**Issue by sa4dht** [df8oe/mchf-github#963]
It would be great to be able to save the mchf configuration to a usb stick or via usb to a pc.

**Comment by db4ple** [comment]
Please Andreas, leave this open and rename it to "Saving and Loading Configuration from USB", so that we don't get this newly entered all the time.

@sa4dht: This is a duplicate of #960 and some others.

**Comment by df8oe** [comment]
This is already on our 2do list.

**Comment by sa4dht** [comment]
Ok, great. As soon as I find some free time I will download the Eclipse IDE in order to be able to contribute with code changes as well. Normally I use Crossworks for ARM but I think it is easier to use the same IDE as you.

**Comment by df8oe** [comment]
Reopened because of others must see this is already asked.

**Comment by Lars-mcHF** [comment]
Thanks, I spoke before I found this

**Comment by db4ple** [comment]
There is the uhsdr_tool to do just that. See https://github.com/df8oe/UHSDR/wiki/Backup-and-Restore
