### ISSUE TITLE
in freedv mode the load indicator and the "ber" value (plus freedv text) does overlap

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#964]
title says it all ... load should be shifted upwards (below cmp box) in the same row as the agc and mode box

when switching freedv off (change mode) behind the load indicator there are some text fragments (some crap that is left over from freedv text)

**Comment by df8oe** [comment]
It cannot be shifted upwards because then it conflicts with RTC display. I think we simply remove the "load" indicator - there is no more space left on LCD.

**Comment by db4ple** [comment]
Hello Andreas, please just disable with #if 0
I will find another way to place this, it is an important debug tool.

**Comment by df8oe** [comment]
It is now conditionally enabled (if show_tp_coordinates is activated by pressing on "dB" on S-Meter when menu mode is active). We can also move freedv display to dsp-box because if digital modes are running DSP always is OFF - just an idea...

Fixed.
