### ISSUE TITLE
SideTone volume not linear

### ISSUE THREAD

**Issue by wk8s** [df8oe/mchf-github#970]
Installed latest firmware from Thursday's Daily Snapshot 8/2/2017 - Volume as adjusted in STG/AF gain was either to low at setting 1 or 2 or jumps to extremely loud at setting 3 and above. Not linear at all. I went back to 2.5.11 and the side tone was again linearly adjustable.

**Comment by db4ple** [comment]
Yes, this was a recently introduced regression, we fixed that, wait for the next daily build.

**Comment by wk8s** [comment]
Thanks - no worries. 

Pete Meier
pmeier@me.com
Amateur Radio Callsign: WK8S
|| I never lose. If I don't win, I learn. - unknown author ||

**Comment by s53dz** [comment]
I suppose both AF and the STG gain should follow the power-logarithmic rule to be near the human ear's perception and not the voltage-linear one.

73 Bojan

**Comment by db4ple** [comment]
The codec internally maps linear values to a decibel-based gain change. So this requirement is fulfilled. The bug was just a bug causing a huge jump between sidetone gain steps (instead of 5 db as intended it was 25db per step).

**Comment by db4ple** [comment]
Pete, if the issue is gone, please close it.

TNX, Danilo

**Comment by s53dz** [comment]
Just a report,

For me, in FW 2.5.32 the issue is gone.
TNX 73 Bojan

**Comment by wk8s** [comment]
The issue is resolved- thank you
