### ISSUE TITLE
Let's free the pins!

### ISSUE THREAD

**Issue by jkramarz** [df8oe/mchf-github#98]
Hi all,

What do you think about following modification to UI board (yes, it'd require 21 bodge wires):
1. unpopulate C50..C65
2. lift one leg of S1..S16
3. run them to new daughterboard featuring PCA8575 port expander
4. use PB8 as interrupt input and share PB10..11 I2C interface
5. use a compile-time flag to provide backward compatiblity, provide both precompiled firmware images
6. make fun and profit of 15 free mCU pins
I think there are no other easily reclaimable pins in current board iterration and I'm looking for any to support my planned extension boards.

Best regards,
Jakub

**Comment by df8oe** [comment]
Better lets use LCD in SPI mode instead of this hardware modification... SPI mode now nearly has same speed as parallel mode.

vy 73
Andreas
