### ISSUE TITLE
new noiseblanker produces "hum noise"

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#986]
title says all
if i switch on the new nb (on a free frequency so it can be heard easy) i hear some hum noise
that seems only to be present in am mode and if i use low pass filters in ssb mode (in bpf filters that hum noise seems to be surpressed) ... in sync am i also can hear it (but it is almost burried in the noise)

so .. to hear that hum noise ... switch to am on a clear frequency (or use a lowpass filter in ssb) and switch the new noiseblanker on and off .... i can clearly hear that hum noise coming out of my speaker

i have some electric fences here and i can say that the new noise blanker does not help much (not much better then the old one) ... only thing that does help a bit is the new agc (wdsp agc) ... but i tried all combinations of agc and nb settings and can not surpress the fences noise :-(

(a comment ... that is not on all frequencies that you can hear that hum noise ... maybe something from the display???)

**Comment by df8oe** [comment]
I cannot confirm using my working conditions. My "electricfence" which is probably 300m away vanishes completely if I turn on new noise blanker and there is no hum noise. I am working in SSB and CW (no AM - no SAM) and prefer BPF filters (for they are better in SSB).

**Comment by Lars-mcHF** [comment]
Is there a way to export, and then email, and then import settings such as freq, DSP BW & Mode to replicate settings to help identify and discover problems and solutions?

**Comment by df8oe** [comment]
Is issue gone? if so: pse close it.

**Comment by DG9BFC** [comment]
no issue is still present
but i run display in parallel mode ... and the hum noise seems to be dependant on what you see on the screen
so maybe a side effect of the "helicopter noise" ?!?

**Comment by DG9BFC** [comment]
issue seems to be solved ... i can not hear that noise anymore
