### ISSUE TITLE
load indicator needed

### ISSUE THREAD

**Issue by DD4WH** [df8oe/mchf-github#995]
in the last firmware versions the load indicator showing the processor load was eliminated.
However, it is a very useful tool to see how different parts of the software contribute to processor load.
Would it be possible to reimplement it (maybe switchable in the DEBUG menu) ?

**Comment by db4ple** [comment]
Debug Menu: Enable Debug Info Display. Right now the indicator is above the band info. Will change that in future but here it is.

**Comment by DD4WH** [comment]
Thanks a lot for the quick answer! Solved!
