### ISSUE TITLE
5W adjustment

### ISSUE THREAD

**Issue by pa5ca** [df8oe/mchf-github#997]
Preforming the 5W calibration (adjustment) it came to my knowledge that the mcHF switches to full power, this can be observed in the power box on the display. At this moment you are not able to set the 5w gain..
The work around, if you have pressed the tune button to press the power button in such way that the power pox on the display shows 5W. From this moment you are able to set the 5W gain.

I'm not sure if this is an known issue I just like to report it. In the mean while I have add some information on the PA calibration page.

yours,
Frans...

**Comment by db4ple** [comment]
Hi,
okay, now I got your problem. Saw your changes in the Wiki! I fixed the missing piece in the instructions (and removed your workaround description). You may want to check back and see the hidden secrect piece of information we were not about to give out. Thanks for reporting, makes the instructions better the rest of the world!

**Comment by db4ple** [comment]
I think, we can close this now, what do you think, Frans? That would be your job then.

73
Danilo

**Comment by pa5ca** [comment]
Hi Danilo, I still have doubts about you text modification..setting the power to 5w in step 3 will not work.. that's why I wrote to do it while the tune is active!!! 
If you set it at step 3 and you press tune the tx power jumps back to FULL power..
So we leave the issue open..:-))

I think it is also a software issue.. because the power jumps to FULL power as soon you press TUNE..

greetzzz Frans...

**Comment by df8oe** [comment]
Hi Frans,

the possibility to set TUNE POWER as a user-defined value was introduced about 1.5 years ago and all who do possess a mcHF do know this...

But now description is absolutely clear - I think. If you set TUNE POWER AS TX POWER (or TUNE POWER to 5W) everything will work as expected. I think we also we can close this... I do not see any issue. Nothing "jumps back to full power (just confirmed).

73
Andreas

**Comment by pa5ca** [comment]
Hi Andreas,
Nice to make your acquaintance... I'm not sure if we discuss the the same issue... 
I believe there is an error while setting the 5W gain. I noticed that when I  tried to set the gain while the TX power showed FULL nothing happened... and my power meter did not showed any  in or de grease of TX power. It only changed when I set the TX power to 5W while tune was active...
I assumed that the TX power set at 5W stays at 5W while you are in PA 5W calibration mode but in my case it did not...
So that's why I had added my comments at the manual..
73
Frans.. 

P.S,
Perhaps it is a case of RTFM from my site.. Hi

**Comment by df8oe** [comment]
Hi Frans,

I have tried the following two possibilities:

1) Setting TUNE POWER AS TX POWER
and
2) Setting TUNE POWER to 5W

In case 1) you have (of course) first to set TX power with button G3 to 5W, in case 2) there is nothing special to do.

Just press "TUNE" and you are TXing with 5W and you can adjust power levels for each band. Absolutely un-misunderstandable and easy to do... Of course you must first select 5W output before you can adjust it - that's now in the description.

The only reason why your TUNE power changes was that you do not have used 1) or 2) from above :)
73
Andreas

**Comment by pa5ca** [comment]
Give it a try this evening... thanks for the comments... and assist keep you posted...
I'll close the the issue..

73 Frans
